### ISSUE TITLE
Exception when compiling `var` pattern with a binding with parametrized opaque type

### ISSUE THREAD

**Issue by utaal** [dafny-lang/dafny#1074]
The following code:
```
module Test {
  type {:extern "predefined"} container<A>

  datatype Node = Leaf | Node(children: container<Node>)

  method Test(node: Node)
  requires node.Node?
  {
    var Node(children) := node; // <- offending line
  }
}
```

when compiled with `/compile:0 /noVerify /spillTargetCode:3` throws this exception (in the compiler):

```
Dafny program verifier did not attempt verification
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Microsoft.Dafny.Compiler.TrCasePatternOpt[VT](CasePattern`1 pat, Expression rhs, String rhs_string, Type rhsType, IToken rhsTok, TargetWriter wr, Boolean inLetExprBody) in dafny/Source/Dafny/Compiler.cs:line 2157
   at Microsoft.Dafny.Compiler.TrCasePatternOpt[VT](CasePattern`1 pat, Expression rhs, TargetWriter wr, Boolean inLetExprBody) in dafny/Source/Dafny/Compiler.cs:line 2103
   at Microsoft.Dafny.Compiler.TrStmt(Statement stmt, TargetWriter wr) in dafny/Source/Dafny/Compiler.cs:line 2891
   at Microsoft.Dafny.Compiler.TrStmtList(List`1 stmts, TargetWriter writer) in dafny/Source/Dafny/Compiler.cs:line 3913
   at Microsoft.Dafny.Compiler.CompileMethod(Method m, IClassWriter cw, Boolean lookasideBody) in dafny/Source/Dafny/Compiler.cs:line 2080
   at Microsoft.Dafny.Compiler.CompileClassMembers(TopLevelDeclWithMembers c, IClassWriter classWriter) in dafny/Source/Dafny/Compiler.cs:line 1644
   at Microsoft.Dafny.Compiler.Compile(Program program, TargetWriter wrx) in dafny/Source/Dafny/Compiler.cs:line 1202
   at Microsoft.Dafny.DafnyDriver.CompileDafnyProgram(Program dafnyProgram, String dafnyProgramName, ReadOnlyCollection`1 otherFileNames, Boolean invokeCompiler, TextWriter outputWriter) in dafny/Source/DafnyDriver/DafnyDriver.cs:line 654
   at Microsoft.Dafny.DafnyDriver.Compile(String fileName, ReadOnlyCollection`1 otherFileNames, Program dafnyProgram, PipelineOutcome oc, Dictionary`2 statss, Boolean verified) in dafny/Source/DafnyDriver/DafnyDriver.cs:line 442
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in dafny/Source/DafnyDriver/DafnyDriver.cs:line 276
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in dafny/Source/DafnyDriver/DafnyDriver.cs:line 58
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass1_0.<Main>b__0() in dafny/Source/DafnyDriver/DafnyDriver.cs:line 34
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
./Scripts/dafny: line 34: 22598 Abort trap: 6           "$DOTNET" "$DAFNY" "$@"
```

cc @Chris-Hawblitzel

**Comment by davidcok** [comment]
The crash happens near this load, L2155 in Compiler.cs

            var sw = new TargetWriter(wr.IndentLevel, true);
            EmitDestructor(tmp_name, formal, k, ctor, ((DatatypeValue)pat.Expr).InferredTypeArgs, arg.Expr.Type, sw);
            Type targetType = formal.Type;
            if (targetType.IsTypeParameter) targetType = ((DatatypeValue) pat.Expr).InferredTypeArgs[0];

Here targetType is both an OpaqueType and a TypeParameter. The if condition on the last line is true, but there are actually no InferredTypeArgs -- hence the crash.

My question is why formal.Type is marked as a TypeParameter.

**Comment by RustanLeino** [comment]
I think the `if` statement is trying to instantiate the formal type parameters of the datatype with the actual type parameters. But it's doing so incorrectly--`targetType` can be an opaque type, which registers as `.IsTypeParameter` (which is what happens in the repro), and the code never replaces formal type parameters contained further inside the `targetType` (e.g., `seq<X>` where `X` is a type parameter of the datatype.
