### ISSUE TITLE
Dafny crashes when using inductive datatype update in lambda

### ISSUE THREAD

**Issue by mschlaipfer** [dafny-lang/dafny#1211]
```dafny
  function method apply<T,U>(op: T --> U): ()
  {
    ()
  }

  datatype D = O | LD(c: D, thunk: () -> D)
  {
    
    function method e(d: D): ()
    {
        apply((x: D) requires x.LD? => x.(c := d))
    }
  }
  ```
  
  crashes with 
  ```
  > $ dafny/dafny /compile:4 tmp/Doc.dfy

Dafny program verifier finished with 1 verified, 0 errors
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: Microsoft.Dafny.BoundVar
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.Dafny.Translator.Substituter.SubstituteCasePattern(CasePattern`1 pat, Boolean forceSubstitutionOfBoundVars) in /Users/leino/Source/dafny/Source/Dafny/Translator.cs:line 18905
   ...
   ```

**Comment by keyboardDrummer** [comment]
Note that this issue doesn't occur when expanding the member update into:
```dafny
function method e(d: D): ()
{
  apply((x: D) requires x.LD? => 
     var dt_update_tmp := x; 
     var dt_update_c := d; 
     LD(dt_update_c, dt_update_tmp.thunk)
  )
}
```

**Comment by keyboardDrummer** [comment]
https://github.com/dafny-lang/dafny/pull/1273
