### ISSUE TITLE
Assumption failed from too deeply nested AST, resulting in a hard crash

### ISSUE THREAD

**Issue by sorawee** [dafny-lang/dafny#1331]
```
method Main () 
{
  var x := [[[[(() => () => [[[[[1]]]]])]]]];
  var _ := [[[[(() => () => [[[[[1]]]]])]]]] + x;
}
```

results in:

```
Process terminated. Assumption failed.
   at Microsoft.Dafny.Resolver.Reaches(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6198
   at Microsoft.Dafny.Resolver.<>c__DisplayClass112_0.<Reaches_aux>b__0(Type su) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6227
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Dafny.Resolver.Reaches_aux(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6227
   at Microsoft.Dafny.Resolver.Reaches(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6201
   at Microsoft.Dafny.Resolver.<>c__DisplayClass112_0.<Reaches_aux>b__0(Type su) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6227
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Dafny.Resolver.Reaches_aux(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6227
   at Microsoft.Dafny.Resolver.Reaches(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6201
   at Microsoft.Dafny.Resolver.<>c__DisplayClass112_0.<Reaches_aux>b__0(Type su) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6227
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Dafny.Resolver.Reaches_aux(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6227
   at Microsoft.Dafny.Resolver.Reaches(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6201
   at Microsoft.Dafny.Resolver.<>c__DisplayClass112_0.<Reaches_aux>b__0(Type su) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6227
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Dafny.Resolver.Reaches_aux(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6227
   at Microsoft.Dafny.Resolver.Reaches(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6201
   at Microsoft.Dafny.Resolver.<>c__DisplayClass112_0.<Reaches_aux>b__0(Type su) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6227
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Dafny.Resolver.Reaches_aux(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6227
   at Microsoft.Dafny.Resolver.Reaches(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6201
   at Microsoft.Dafny.Resolver.Reaches_aux(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6216
   at Microsoft.Dafny.Resolver.Reaches(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6201
   at Microsoft.Dafny.Resolver.Reaches_aux(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6216
   at Microsoft.Dafny.Resolver.Reaches(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6201
   at Microsoft.Dafny.Resolver.Reaches_aux(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6216
   at Microsoft.Dafny.Resolver.Reaches(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6201
   at Microsoft.Dafny.Resolver.Reaches_aux(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6216
   at Microsoft.Dafny.Resolver.Reaches(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6201
   at Microsoft.Dafny.Resolver.Reaches_aux(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6216
   at Microsoft.Dafny.Resolver.Reaches(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6201
   at Microsoft.Dafny.Resolver.Reaches_aux(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6216
   at Microsoft.Dafny.Resolver.Reaches(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6201
   at Microsoft.Dafny.Resolver.Reaches_aux(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6216
   at Microsoft.Dafny.Resolver.Reaches(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6201
   at Microsoft.Dafny.Resolver.<>c__DisplayClass112_0.<Reaches_aux>b__0(Type su) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6227
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Dafny.Resolver.Reaches_aux(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6227
   at Microsoft.Dafny.Resolver.Reaches(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6201
   at Microsoft.Dafny.Resolver.<>c__DisplayClass112_0.<Reaches_aux>b__0(Type su) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6227
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Dafny.Resolver.Reaches_aux(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6227
   at Microsoft.Dafny.Resolver.Reaches(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6201
   at Microsoft.Dafny.Resolver.<>c__DisplayClass112_0.<Reaches_aux>b__0(Type su) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6227
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Dafny.Resolver.Reaches_aux(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6227
   at Microsoft.Dafny.Resolver.Reaches(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6201
   at Microsoft.Dafny.Resolver.<>c__DisplayClass112_0.<Reaches_aux>b__0(Type su) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6227
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Dafny.Resolver.Reaches_aux(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6227
   at Microsoft.Dafny.Resolver.Reaches(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6201
   at Microsoft.Dafny.Resolver.Reaches_aux(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6216
   at Microsoft.Dafny.Resolver.Reaches(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6201
   at Microsoft.Dafny.Resolver.Reaches_aux(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6216
   at Microsoft.Dafny.Resolver.Reaches(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6201
   at Microsoft.Dafny.Resolver.Reaches_aux(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6216
   at Microsoft.Dafny.Resolver.Reaches(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6201
   at Microsoft.Dafny.Resolver.Reaches_aux(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6216
   at Microsoft.Dafny.Resolver.Reaches(Type t, TypeProxy proxy, Int32 direction, HashSet`1 visited) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 6201
   at Microsoft.Dafny.Resolver.AssignKnownEnd(TypeProxy proxy, Boolean keepConstraints, Boolean fullStrength) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 5933
   at Microsoft.Dafny.Resolver.ConstrainSubtypeRelation_Aux(Type super, Type sub, TypeConstraint c, Boolean keepConstraints, Boolean allowDecisions) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 4327
   at Microsoft.Dafny.Resolver.ConstrainSubtypeRelation(Type super, Type sub, ErrorMsg errMsg, Boolean keepConstraints, Boolean allowDecisions) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 4303
   at Microsoft.Dafny.Resolver.ConstrainSubtypeRelation(Type super, Type sub, IToken tok, String msg, Object[] msgArgs) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 4171
   at Microsoft.Dafny.Resolver.ResolveExpression(Expression expr, ResolveOpts opts) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 14957
   at Microsoft.Dafny.Resolver.ResolveUpdateStmt(UpdateStmt update, ICodeContext codeContext, Int32 errorCountBeforeCheckingLhs) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 12654
   at Microsoft.Dafny.Resolver.ResolveConcreteUpdateStmt(ConcreteUpdateStatement s, ICodeContext codeContext) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 12619
   at Microsoft.Dafny.Resolver.ResolveStatement(Statement stmt, ICodeContext codeContext) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 10895
   at Microsoft.Dafny.Resolver.ResolveStatementWithLabels(Statement stmt, ICodeContext codeContext) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 13272
   at Microsoft.Dafny.Resolver.ResolveBlockStatement(BlockStmt blockStmt, ICodeContext codeContext) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 13242
   at Microsoft.Dafny.Resolver.ResolveMethod(Method m) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 10091
   at Microsoft.Dafny.Resolver.ResolveClassMemberBodies(TopLevelDeclWithMembers cl) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 9322
   at Microsoft.Dafny.Resolver.ResolveTopLevelDecls_Core(List`1 declarations, Graph`1 datatypeDependencies, Graph`1 codatatypeDependencies, Boolean isAnExport) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 2755
   at Microsoft.Dafny.Resolver.ResolveModuleDefinition(ModuleDefinition m, ModuleSignature sig, Boolean isAnExport) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 1004
   at Microsoft.Dafny.Resolver.ResolveProgram(Program prog) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 487
   at Microsoft.Dafny.Main.Resolve(Program program, ErrorReporter reporter) in /Users/sorawee/projects/dafny/Source/Dafny/DafnyMain.cs:line 165
   at Microsoft.Dafny.Main.ParseCheck(IList`1 files, String programName, ErrorReporter reporter, Program& program) in /Users/sorawee/projects/dafny/Source/Dafny/DafnyMain.cs:line 113
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in /Users/sorawee/projects/dafny/Source/DafnyDriver/DafnyDriver.cs:line 265
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in /Users/sorawee/projects/dafny/Source/DafnyDriver/DafnyDriver.cs:line 57
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass1_0.<Main>b__0() in /Users/sorawee/projects/dafny/Source/DafnyDriver/DafnyDriver.cs:line 36
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
../Dafny/Scripts/dafny: line 34: 13110 Abort trap: 6           "$DOTNET" "$DAFNY" "$@"
```

Note that 

```
method Main () 
{
  var x := [[[[(() => () => [[[[[1]]]]])]]]];
  var _ := x + x;
}
```

works fine.

**Comment by sorawee** [comment]
Ah, well, looks like this is expected, though the error message perhaps could be improved.

https://github.com/dafny-lang/dafny/blob/master/Source/Dafny/Resolver.cs#L6197

**Comment by keyboardDrummer** [comment]
I think this is a bug, at least the reporting should be better :) Thanks for reporting.

**Comment by olivier-aws** [comment]
Closing the issue as it cannot be reproduced with latest Dafny release (4.9.1).
