### ISSUE TITLE
NullReferenceException in Compiler 

### ISSUE THREAD

**Issue by IsaacOscar** [dafny-lang/dafny#1411]
Bassically this code won't compile (I made it as simple as possible while still crashing)

```
function method {:verify false} pointless(a: nat): seq<nat> {
	if true then
		[] + pointless(0)
	else
		var rec := pointless(0);
		rec }
```
It produces:

```

Dafny program verifier finished with 0 verified, 0 errors
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dafny.IdentifierExpr..ctor(IToken tok, IVariable v) in /Users/leino/Source/dafny/Source/Dafny/DafnyAst.cs:line 9988
   at Microsoft.Dafny.Compiler.TrExprOpt(Expression expr, Type resultType, ConcreteSyntaxTree wr, IVariable accumulatorVar) in /Users/leino/Source/dafny/Source/Dafny/Compiler.cs:line 2435
   at Microsoft.Dafny.Compiler.TrExprOpt(Expression expr, Type resultType, ConcreteSyntaxTree wr, IVariable accumulatorVar) in /Users/leino/Source/dafny/Source/Dafny/Compiler.cs:line 2342
   at Microsoft.Dafny.Compiler.CompileReturnBody(Expression body, Type originalResultType, ConcreteSyntaxTree wr, IVariable accumulatorVar) in /Users/leino/Source/dafny/Source/Dafny/Compiler.cs:line 2512
   at Microsoft.Dafny.Compiler.CompileFunction(Function f, IClassWriter cw, Boolean lookasideBody) in /Users/leino/Source/dafny/Source/Dafny/Compiler.cs:line 2168
   at Microsoft.Dafny.Compiler.CompileClassMembers(Program program, TopLevelDeclWithMembers c, IClassWriter classWriter) in /Users/leino/Source/dafny/Source/Dafny/Compiler.cs:line 1739
   at Microsoft.Dafny.Compiler.Compile(Program program, ConcreteSyntaxTree wrx) in /Users/leino/Source/dafny/Source/Dafny/Compiler.cs:line 1207
   at Microsoft.Dafny.DafnyDriver.CompileDafnyProgram(Program dafnyProgram, String dafnyProgramName, ReadOnlyCollection`1 otherFileNames, Boolean invokeCompiler, TextWriter outputWriter) in /Users/leino/Source/dafny/Source/DafnyDriver/DafnyDriver.cs:line 666
   at Microsoft.Dafny.DafnyDriver.Compile(String fileName, ReadOnlyCollection`1 otherFileNames, Program dafnyProgram, PipelineOutcome oc, Dictionary`2 statss, Boolean verified) in /Users/leino/Source/dafny/Source/DafnyDriver/DafnyDriver.cs:line 441
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in /Users/leino/Source/dafny/Source/DafnyDriver/DafnyDriver.cs:line 281
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in /Users/leino/Source/dafny/Source/DafnyDriver/DafnyDriver.cs:line 60
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass1_0.<Main>b__0() in /Users/leino/Source/dafny/Source/DafnyDriver/DafnyDriver.cs:line 36
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by olivier-aws** [comment]
Closing the issue as it cannot be reproduced with latest Dafny release (4.9.1).
