### ISSUE TITLE
Incorrect compile-time error reporting: NullReferenceException

### ISSUE THREAD

**Issue by sorawee** [dafny-lang/dafny#1438]
```
method Main () 
{
  y :| y in x;
}
```

fails with:

```
/Users/sorawee/projects/dsmith/tmp.dfy(5,2): Error: unresolved identifier: y
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dafny.ErrorReporter.Error(MessageSource source, Expression e, String msg, Object[] args) in /Users/sorawee/projects/dafny/Source/Dafny/Reporting.cs:line 96
   at Microsoft.Dafny.Resolver.CheckIsLvalue(Expression lhs, ICodeContext codeContext) in /Users/sorawee/projects/dafny/Source/Dafny/Resolver.cs:line 13347
...
```

The error on the first line is of course expected, but it should not result in `NullReferenceException`.

**Comment by olivier-aws** [comment]
Closing the issue as it cannot be reproduced with latest Dafny release (4.9.1).
