### ISSUE TITLE
Resolution crash when refining a module and defining a const with a subset type

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#1481]
Reported in the context of https://github.com/dafny-lang/libraries/pull/15#discussion_r711335661

```dafny
module Test {
  type LessThan10 = x | 0 <= x < 10
  const C: LessThan10
}

module Test' refines Test {
  const C: LessThan10 := 5
}
```

```
Process terminated. Assertion failed.
   at Microsoft.Dafny.Resolver.ResolveTopLevelDecls_Core(List`1 declarations, Graph`1 datatypeDependencies, Graph`1 codatatypeDependencies, Boolean isAnExport) in /private/tmp/dafny-20210205-34509-rqus4y/dafny-3.0.0/Source/Dafny/Resolver.cs:line 2644
   at Microsoft.Dafny.Resolver.ResolveModuleDefinition(ModuleDefinition m, ModuleSignature sig, Boolean isAnExport) in /private/tmp/dafny-20210205-34509-rqus4y/dafny-3.0.0/Source/Dafny/Resolver.cs:line 1002
...
```

**Comment by olivier-aws** [comment]
Closing the issue as it cannot be reproduced with latest Dafny release (4.9.1).
