### ISSUE TITLE
System.InvalidCastException when datatype ctor has "Keys" parameter

### ISSUE THREAD

**Issue by alex-chew** [dafny-lang/dafny#1587]
Given `Tmp.dfy` containing
```dafny
datatype Foo = Foo(Keys: ())
```

then running `dotnet Dafny.dll Tmp.dfy /verifyAllModules /compile:1 /spillTargetCode:1 /out:bin/Tmp` throws the following exception:
```
$ "/usr/local/share/dotnet/dotnet" "/Users/alexchew/.vscode/extensions/correctnesslab.dafny-vscode-2.0.1/out/resources/dafny/Dafny.dll" "<redacted>/Tmp.dfy" /verifyAllModules /compile:1 /spillTargetCode:1 /out:bin/Tmp
Unhandled exception. System.InvalidCastException: Unable to cast object of type 'Microsoft.Dafny.UserDefinedType' to type 'Microsoft.Dafny.SetType'.
   at Microsoft.Dafny.Translator.GetReadonlyField(Field f) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Verifier/Translator.cs:line 9427
   at Microsoft.Dafny.Translator.<>c__DisplayClass103_1.<AddDatatype>b__0(Boolean is_alloc) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Verifier/Translator.cs:line 1385
   at Microsoft.Dafny.Translator.MapM[A](IEnumerable`1 xs, Action`1 K) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Verifier/Translator.cs:line 13714
   at Microsoft.Dafny.Translator.AddDatatype(DatatypeDecl dt) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Verifier/Translator.cs:line 1337
   at Microsoft.Dafny.Translator.AddTypeDecl(RevealableTypeDecl d) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Verifier/Translator.cs:line 1154
   at Microsoft.Dafny.Translator.DoTranslation(Program p, ModuleDefinition forModule) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Verifier/Translator.cs:line 745
   at Microsoft.Dafny.Translator.Translate(Program p, ErrorReporter reporter, TranslatorFlags flags)+MoveNext() in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Verifier/Translator.cs:line 816
   at Microsoft.Dafny.DafnyDriver.Translate(Program dafnyProgram)+MoveNext() in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyDriver/DafnyDriver.cs:line 338
   at Microsoft.Dafny.DafnyDriver.Boogie(String baseName, IEnumerable`1 boogiePrograms, String programId, Dictionary`2& statss, PipelineOutcome& oc) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyDriver/DafnyDriver.cs:line 392
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyDriver/DafnyDriver.cs:line 285
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyDriver/DafnyDriver.cs:line 53
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass1_0.<Main>b__0() in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyDriver/DafnyDriver.cs:line 34
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Abort trap: 6
```

But changing the name of the `Keys` parameter to something else, such as
```dafny
datatype Foo = Foo(keys: ())
// or
datatype Foo = Foo(Bar: ())
```
gives the expected output:
```
$ "/usr/local/share/dotnet/dotnet" "/Users/alexchew/.vscode/extensions/correctnesslab.dafny-vscode-2.0.1/out/resources/dafny/Dafny.dll" "<redacted>/Tmp.dfy" /verifyAllModules /compile:1 /spillTargetCode:1 /out:bin/Tmp

Dafny program verifier finished with 0 verified, 0 errors
Wrote textual form of target program to Tmp.cs
Compiled assembly into Tmp.dll
```

**Comment by alex-chew** [comment]
This line in `Microsoft.Dafny.Translator.GetReadonlyField(Field f)` is suspect: https://github.com/dafny-lang/dafny/blob/d949560518e09c5c3eb042b0ddba361948c01eef/Source/Dafny/Verifier/Translator.cs#L9442

**Comment by robin-aws** [comment]
Agreed, looks like the verifier is assuming those special fields can't be declared by user Dafny code. I've labelled this with both `verifier` and `resolver` because the proper fix MIGHT be to reject the use of these special names earlier in the pipeline, although I'd rather allow them unless it's really difficult to fix the verifier.
