### ISSUE TITLE
System.NullReferenceException on abstract module import containing function using `calc`

### ISSUE THREAD

**Issue by alex-chew** [dafny-lang/dafny#1639]
Given the following in MWE.dfy:

```dafny
module Foo {
  function NoOp(): () {
    calc { 0; } ()
  }
}

abstract module Bar {
  import MyFoo : Foo
}
```

The Dafny compiler fails to handle a NullReferenceException:
```
$ "/usr/local/share/dotnet/dotnet" "/Users/alexchew/.vscode/extensions/correctnesslab.dafny-vscode-2.0.2/out/resources/dafny/Dafny.dll" "/Users/alexchew/wp/tmp/dafny-test/abstract-module-bug/MWE.dfy"
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dafny.Resolver.ResolveStatement(Statement stmt, ICodeContext codeContext) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Resolver.cs:line 11478
   at Microsoft.Dafny.Resolver.ResolveExpression(Expression expr, ResolveOpts opts) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Resolver.cs:line 15148
   at Microsoft.Dafny.Resolver.ResolveFunction(Function f) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Resolver.cs:line 10072
   at Microsoft.Dafny.Resolver.ResolveClassMemberBodies(TopLevelDeclWithMembers cl) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Resolver.cs:line 9475
   at Microsoft.Dafny.Resolver.ResolveTopLevelDecls_Core(List`1 declarations, Graph`1 datatypeDependencies, Graph`1 codatatypeDependencies, Boolean isAnExport) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Resolver.cs:line 2781
   at Microsoft.Dafny.Resolver.ResolveModuleDefinition(ModuleDefinition m, ModuleSignature sig, Boolean isAnExport) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Resolver.cs:line 1004
   at Microsoft.Dafny.Resolver.MakeAbstractSignature(ModuleSignature p, String Name, Int32 Height, Dictionary`2 mods, Dictionary`2 compilationModuleClones) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Resolver.cs:line 2344
   at Microsoft.Dafny.Resolver.ResolveProgram(Program prog) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Resolver.cs:line 551
   at Microsoft.Dafny.Main.Resolve(Program program, ErrorReporter reporter) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/DafnyMain.cs:line 161
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyDriver/DafnyDriver.cs:line 278
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyDriver/DafnyDriver.cs:line 53
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass1_0.<Main>b__0() in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyDriver/DafnyDriver.cs:line 34
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
Abort trap: 6
```

The file compiles/verifies as expected under the following changes:
- Changing `NoOp` to a (non-function) method, and removing the return type/value correspondingly
- Removing the contents of the `calc` statement (i.e. everything within the braces)
- Removing the `calc` statement
- Replacing the `calc` statement with an equivalent `assert` statement
- Removing the abstract `Foo` module import within the `Bar` module, with or without also removing the `Foo` module entirely
- Removing the `Bar` module entirely

The same exception is thrown under the following changes:
- Changing the names of `Foo` and `Bar`
- Making `Foo` abstract
- Changing `NoOp` to a function method
- Changing the return type and return value of `NoOp`
- Changing the contents of the `calc` statement to `0; 0;` or `true;` or other non-empty contents

Version information:
```
$ "/usr/local/share/dotnet/dotnet" "/Users/alexchew/.vscode/extensions/correctnesslab.dafny-vscode-2.0.2/out/resources/dafny/Dafny.dll" /version
Dafny 3.3.0.31104

$ "/usr/local/share/dotnet/dotnet" --version
5.0.402
```

**Comment by alex-chew** [comment]
When `Foo` is abstractly imported into `Bar` in the example above, Dafny's `Resolver.CloneDeclaration` [attempts to clone](https://github.com/dafny-lang/dafny/blob/65ae35bfc0ab237975b6a2594c55d67adf2a8eee/Source/Dafny/Resolver.cs#L2403) `Foo`'s contents using an `AbstractSignatureCloner`.

But `AbstractSignatureCloner` overrides `CloneBlockStmt` such that it always returns `null`. So when the `calc` statement is "cloned", the cloned `CalcStmt.Hints` (represented as `BlockStmt`s) are all null, ultimately causing a NullReferenceException where the hints are later assumed to be non-null.

It remains to decide whether `AbstractSignatureCloner` should be implemented a bit more precisely (i.e. to be more selective about what kinds of statements are cloned as null), or whether code referencing `CalcStmt.Hints` should not assume that the elements are non-null.
