### ISSUE TITLE
Improve error reporting in LSP server

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/dafny#1644]
When given incorrect input the LSP server tends to fail silently.  Here's an example trace:

```
Content-Length: 272

{
 "jsonrpc": "2.0",
 "method": "initialize",
 "params": {
  "processId": 11928,
  "clientInfo": {
   "name": "Dafny diff tester"
  },
  "rootUri": "file:///c:/Users/cpitcla/wip/difftests",
  "capabilities": {
   "publishDiagnostics": {}
  }
 },
 "id": 0
}
Content-Length: 68

{
 "jsonrpc": "2.0",
 "method": "initialized",
 "params": {}
}
Content-Length: 306

{
 "jsonrpc": "2.0",
 "method": "textDocument/didOpen",
 "params": {
  "textDocument": {
   "uri": "file:///c:/Users/cpitcla/wip/difftests/snaps.dfy",
   "languageId": "dafny",
   "version": 0,
   "text": "method t0() { assert 1 == 1; assert 1 == 1; assert 1 == 1; assert 1 == 0; }\n"
  }
 }
}
Content-Length: 336

{
 "jsonrpc": "2.0",
 "method": "textDocument/didChange",
 "params": {
  "textDocument": {
   "uri": "file:///c:/Users/cpitcla/wip/difftests/snaps.dfy",
   "languageId": "dafny",
   "version": 1
  },
  "contentChanges": {
   "text": "method t0() { assert 1 == 1; assert 1 == 1; assert 1 == 1; assert 1 == 1; }\n"
  }
 }
}
```

This produces no output after the last input, but it prints this to the log:

```
[17:15:52 INF Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier] 
[17:15:52 INF Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier] Verifying Impl$$_module.__default.t0 ...
[17:15:52 INF Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier] error
[17:16:01 FTL OmniSharp.Extensions.JsonRpc.InputHandler] Unknown error handling notification
Newtonsoft.Json.JsonSerializationException: Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'OmniSharp.Extensions.LanguageServer.Protocol.Models.Container`1[OmniSharp.Extensions.LanguageServer.Protocol.Models.TextDocumentContentChangeEvent]' because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'params.contentChanges.text', line 11, position 10.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at OmniSharp.Extensions.LanguageServer.Shared.LspRequestRouter.FindDescriptor(String method, JToken params)
   at OmniSharp.Extensions.LanguageServer.Shared.LspRequestRouter.FindDescriptor(IMethodWithParams instance)
   at OmniSharp.Extensions.LanguageServer.Shared.LspRequestRouter.GetDescriptors(Notification notification)
   at OmniSharp.Extensions.LanguageServer.Shared.LspRequestRouter.OmniSharp.Extensions.JsonRpc.IRequestRouter<OmniSharp.Extensions.JsonRpc.IHandlerDescriptor>.GetDescriptors(Notification notification)
   at OmniSharp.Extensions.JsonRpc.InputHandler.HandleRequest(ReadOnlySequence`1& request)
```

You can reproduce the issue by running `dotnet DafnyLanguageServer.dll --documents:verify=onchange --verifier:timelimit=0 --verifier:vcscores=0 --ghost:markStatements=true` and then pasting the commands from the trace one by one (make sure to use `\r\n` as the line terminator when pasting stuff to the server)

It would be nice to report the errors directly through the LSP protocol, or even exit with an error message; currently the server waits silently instead, which is confusing.

CC @camrein

**Comment by cpitclaudel** [comment]
To clarify the example above, the last notification sent by the client is invalid (it sends a single change instead of an array of changes), so the server is right to reject it; but because the server fails silently, it's harder to diagnose that issue.

Also, the spec [says](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#textDocumentContentChangeEvent) *If range and rangeLength are omitted the new text is considered to be the full content of the document.*, but our server also rejects that; is that something we want to fix?

```
[17:54:20 ERR Microsoft.Dafny.LanguageServer.Handlers.DafnyTextDocumentHandler] error while handling document event
System.InvalidOperationException: the range of the change must not be null
   at Microsoft.Dafny.LanguageServer.Workspace.ChangeProcessors.TextChangeProcessor.ApplyTextChange(String text, TextDocumentContentChangeEvent change, CancellationToken cancellationToken) in c:\Users\cpitcla\git\dafny\Source\DafnyLanguageServer\Workspace\ChangeProcessors\TextChangeProcessor.cs:line 26
   at Microsoft.Dafny.LanguageServer.Workspace.ChangeProcessors.TextChangeProcessor.ApplyTextChanges(String originalText, Container`1 changes, CancellationToken cancellationToken) in c:\Users\cpitcla\git\dafny\Source\DafnyLanguageServer\Workspace\ChangeProcessors\TextChangeProcessor.cs:line 19
   at Microsoft.Dafny.LanguageServer.Workspace.ChangeProcessors.TextChangeProcessor.ApplyChange(TextDocumentItem originalTextDocument, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken) in c:\Users\cpitcla\git\dafny\Source\DafnyLanguageServer\Workspace\ChangeProcessors\TextChangeProcessor.cs:line 9
```

**Comment by camrein** [comment]
Thanks for your proposal and for sharing the example trace.

> It would be nice to report the errors directly through the LSP protocol, or even exit with an error message; currently the server waits silently instead, which is confusing.

I understand that it's confusing. Since you're working directly with the JSON request, I believe you're implementing an LSP client yourself, or at least interacting with the language server through the LSP. The request is rejected by the language server library we use (OmniSharp), and I haven't seen a possibility to track these yet. However, I haven't had the time to dive deep here yet, so I might have missed something.
The exception is handled and logged by `OmniSharp.Extensions.JsonRpc.InputHandler`. We configure a `Debug` and a `File` logger by default. Besides using `trail` on the file, you may attach a debugger to the console application to improve your debugging/logging experience for now.
A general improvement would be creating a Serilog sink that sends critical errors to the LSP client. But I think this should be the last resort if we cannot explicitly track these errors.

> Also, the spec [says](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#textDocumentContentChangeEvent) _If range and rangeLength are omitted the new text is considered to be the full content of the document._, but our server also rejects that; is that something we want to fix?

The language server informs the client that it wants [incremental changes](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#textDocumentSyncKind). Therefore, I believe it's correct to reject change notifications that don't contain the necessary information.
Extending the language server to support full updates is straightforward (only minor changes to [TextChangeProcessor](https://github.com/dafny-lang/dafny/blob/master/Source/DafnyLanguageServer/Workspace/ChangeProcessors/TextChangeProcessor.cs) and [SymbolTableRelocator](https://github.com/dafny-lang/dafny/blob/master/Source/DafnyLanguageServer/Workspace/ChangeProcessors/SymbolTableRelocator.cs)). However, some features won't work to their full potential. For example, if a document cannot be parsed or resolved, the incremental change allows relocating the document symbols according to the change to preserve the lookup feature partially.

**Comment by cpitclaudel** [comment]
Thanks for this very helpful answer.  Just a quick point: maybe it would be enough to have a mode in which we *don't* catch errors?  I think that's how the omnisharp server works by default, since from time to time on C# projects it actually gives me backtraces:


```
Warning (lsp-mode): c:\Users\cpitcla\git\dafny\third_party\Coco\src\Coco.csproj: Microsoft.Build.Exceptions.InvalidProjectFileException: The expression "[Microsoft.Build.Utilities.ToolLocationHelper]::GetPathToStandardLibraries(.NETFramework, net5.0, '', AnyCPU, '', '')" cannot be evaluated. Input string was not in a correct format.  c:\Users\cpitcla\.emacs.d\.cache\lsp\omnisharp-roslyn\latest\omnisharp-roslyn\.msbuild\Current\Bin\Microsoft.Common.CurrentVersion.targets

   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)

   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject[T1,T2](IElementLocation elementLocation, String resourceName, T1 arg0, T2 arg1)

   at Microsoft.Build.Evaluation.Expander`2.Function`1.Execute(Object objectInstance, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation)

   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertyBody(String propertyBody, Object propertyValue, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties, IFileSystem fileSystem)

   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveTypedAndEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties, IFileSystem fileSystem)

   at Microsoft.Build.Evaluation.Expander`2.PropertyExpander`1.ExpandPropertiesLeaveEscaped(String expression, IPropertyProvider`1 properties, ExpanderOptions options, IElementLocation elementLocation, UsedUninitializedProperties usedUninitializedProperties, IFileSystem fileSystem)

   at Microsoft.Build.Evaluation.Expander`2.ExpandIntoStringLeaveEscaped(String expression, ExpanderOptions options, IElementLocation elementLocation)

   at Microsoft.Build.Evaluation.Evaluator`4.EvaluatePropertyElement(ProjectPropertyElement propertyElement)

   at Microsoft.Build.Evaluation.Evaluator`4.EvaluatePropertyGroupElement(ProjectPropertyGroupElement propertyGroupElement)

   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)

   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)

   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)

   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)

   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)

   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)

   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)

   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)

   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)

   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()

   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCacheBase projectRootElementCache, BuildEventContext buildEventContext, ISdkResolverService sdkResolverService, Int32 submissionId, EvaluationContext evaluationContext, Boolean interactive)

   at Microsoft.Build.Evaluation.Project.ProjectImpl.Reevaluate(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)

   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)

   at Microsoft.Build.Evaluation.Project.ProjectImpl.ReevaluateIfNecessary(EvaluationContext evaluationContext)

   at Microsoft.Build.Evaluation.Project.ProjectImpl.Initialize(IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)

   at Microsoft.Build.Evaluation.Project..ctor(String projectFile, IDictionary`2 globalProperties, String toolsVersion, String subToolsetVersion, ProjectCollection projectCollection, ProjectLoadSettings loadSettings, EvaluationContext evaluationContext)

   at Microsoft.Build.Evaluation.ProjectCollection.LoadProject(String fileName, IDictionary`2 globalProperties, String toolsVersion)

   at OmniSharp.MSBuild.ProjectLoader.EvaluateProjectFileCore(String filePath, IReadOnlyDictionary`2 projectConfigurationsInSolution) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectLoader.cs:line 157

   at OmniSharp.MSBuild.ProjectLoader.BuildProject(String filePath, IReadOnlyDictionary`2 configurationsInSolution) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectLoader.cs:line 75

   at OmniSharp.MSBuild.ProjectFile.ProjectFileInfo.Load(String filePath, ProjectIdInfo projectIdInfo, ProjectLoader loader, Guid sessionId, DotNetInfo dotNetInfo) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectFile\ProjectFileInfo.cs:line 117

   at OmniSharp.MSBuild.ProjectManager.<>c__DisplayClass31_0.<LoadProject>b__0() in D:\a\1\s\src\OmniSharp.MSBuild\ProjectManager.cs:line 304

   at OmniSharp.MSBuild.ProjectManager.LoadOrReloadProject(String projectFilePath, Func`1 loader) in D:\a\1\s\src\OmniSharp.MSBuild\ProjectManager.cs:line 315
```

At least this makes it immediately clear that something is wrong.

**Comment by camrein** [comment]
> Just a quick point: maybe it would be enough to have a mode in which we _don't_ catch errors?

This essentially doesn't work anymore after we introduced concurrent document updates. We no longer use the "request thread" to handle document updates and cannot return information to it since it completes long before the document update is completed inside the language server. Such a feature would require that we disable the concurrent document updates. However, we could make this configurable to restore the original behavior prior #1456. This would make debugging easier but sacrifices the responsiveness. Essentially, it's only a matter of replacing the calls to `HandleUpdateAndPublishDiagnosticsAsync` inside [DafnyTextDocumentHandler](https://github.com/dafny-lang/dafny/blob/23d4b90a9aa4af67ae6b35f90b944de1d04c7869/Source/DafnyLanguageServer/Handlers/DafnyTextDocumentHandler.cs) with `await <inner call>`.
