### ISSUE TITLE
Unhandled NullReferenceException in ExprRhs..ctor

### ISSUE THREAD

**Issue by dijkstracula** [dafny-lang/dafny#1682]
Dear Dafny team,

While typing the following silly and incomplete Dafny program:

```
method IsUnique(str: array<char>) returns (ret: bool)
    ensures forall i, j :: 0 <= i < j < str.Length ==> ret ==> str[i] != str[j]
{
    ret := multiset
}
```

 immediately upon typing the `multiset` token the VSCode language plugin crashes with the following stacktrace:

```
[Error - 4:07:07 PM] Request textDocument/completion failed.
  Message: Internal Error - System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dafny.ExprRhs..ctor(Expression expr, Attributes attrs) in /Users/ntaylor/code/dafny/Source/Dafny/AST/DafnyAst.cs:line 7262
   at Microsoft.Dafny.Parser.Rhs(AssignmentRhs& r) in /Users/ntaylor/code/dafny/Source/Dafny/Parser.cs:line 4049
   at Microsoft.Dafny.Parser.UpdateStmt(Statement& s) in /Users/ntaylor/code/dafny/Source/Dafny/Parser.cs:line 3232
   at Microsoft.Dafny.Parser.OneStmt(Statement& s) in /Users/ntaylor/code/dafny/Source/Dafny/Parser.cs:line 3121
   at Microsoft.Dafny.Parser.Stmt(List`1 ss) in /Users/ntaylor/code/dafny/Source/Dafny/Parser.cs:line 3103
   at Microsoft.Dafny.Parser.BlockStmt(BlockStmt& block, IToken& bodyStart, IToken& bodyEnd) in /Users/ntaylor/code/dafny/Source/Dafny/Parser.cs:line 2682
   at Microsoft.Dafny.Parser.MethodDecl(DeclModifierData dmod, Boolean allowConstructor, Method& m) in /Users/ntaylor/code/dafny/Source/Dafny/Parser.cs:line 2148
   at Microsoft.Dafny.Parser.ClassMemberDecl(DeclModifierData dmod, List`1 mm, Boolean allowConstructors, Boolean isValueType, Boolean moduleLevelDecl) in /Users/ntaylor/code/dafny/Source/Dafny/Parser.cs:line 1415
   at Microsoft.Dafny.Parser.TopDecl(ModuleDefinition module, List`1 membersDefaultClass, Boolean isTopLevel, Boolean isAbstract) in /Users/ntaylor/code/dafny/Source/Dafny/Parser.cs:line 973
   at Microsoft.Dafny.Parser.Dafny() in /Users/ntaylor/code/dafny/Source/Dafny/Parser.cs:line 897
   at Microsoft.Dafny.Parser.Parse() in /Users/ntaylor/code/dafny/Source/Dafny/Parser.cs:line 6192
   at Microsoft.Dafny.Parser.Parse(String s, String fullFilename, String filename, Include include, ModuleDecl module, BuiltIns builtIns, Errors errors, Boolean verifyThisFile, Boolean compileThisFile) in /Users/ntaylor/code/dafny/Source/Dafny/Parser.cs:line 286
   at Microsoft.Dafny.Parser.Parse(String s, String fullFilename, String filename, ModuleDecl module, BuiltIns builtIns, ErrorReporter reporter, Boolean verifyThisFile, Boolean compileThisFile) in /Users/ntaylor/code/dafny/Source/Dafny/Parser.cs:line 251
   at Microsoft.Dafny.LanguageServer.Language.DafnyLangParser.Parse(TextDocumentItem document, ErrorReporter errorReporter, CancellationToken cancellationToken) in /Users/ntaylor/code/dafny/Source/DafnyLanguageServer/Language/DafnyLangParser.cs:line 63
   at Microsoft.Dafny.LanguageServer.Workspace.TextDocumentLoader.LoadInternal(LoadRequest loadRequest) in /Users/ntaylor/code/dafny/Source/DafnyLanguageServer/Workspace/TextDocumentLoader.cs:line 109
   at Microsoft.Dafny.LanguageServer.Workspace.TextDocumentLoader.Run() in /Users/ntaylor/code/dafny/Source/DafnyLanguageServer/Workspace/TextDocumentLoader.cs:line 93
--- End of stack trace from previous location ---
   at Microsoft.Dafny.LanguageServer.Workspace.TextDocumentLoader.LoadAsync(TextDocumentItem textDocument, CancellationToken cancellationToken) in /Users/ntaylor/code/dafny/Source/DafnyLanguageServer/Workspace/TextDocumentLoader.cs:line 82
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.LoadAndVerifyAsync(TextDocumentItem textDocument, Boolean verify, CancellationToken cancellationToken) in /Users/ntaylor/code/dafny/Source/DafnyLanguageServer/Workspace/DocumentDatabase.cs:line 93
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(DafnyDocument oldDocument, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken) in /Users/ntaylor/code/dafny/Source/DafnyLanguageServer/Workspace/DocumentDatabase.cs:line 130
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.<>c__DisplayClass19_0.<<UpdateDocumentAsync>b__0>d.MoveNext() in /Users/ntaylor/code/dafny/Source/DafnyLanguageServer/Workspace/DocumentDatabase.cs:line 119
--- End of stack trace from previous location ---
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.GetDocumentAsync(TextDocumentIdentifier documentId) in /Users/ntaylor/code/dafny/Source/DafnyLanguageServer/Workspace/DocumentDatabase.cs:line 184
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyCompletionHandler.Handle(CompletionParams request, CancellationToken cancellationToken) in /Users/ntaylor/code/dafny/Source/DafnyLanguageServer/Handlers/DafnyCompletionHandler.cs:line 42
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext()
  Code: -32603 
```

Even though the top of the throwing stack is inside Dafny and not the IDE plugin, I wasn't sure that it was necessarily a problem with the former or the latter.  To try to suss that out, I saved the file and tried to verify it on the command line, and got the same exception unhandled.

```
➜  Binaries git:(master) git log --abbrev-commit --oneline | head -n 1
09ee1c75  fix(lsp): Don't get stuck when onsave verification is cancelled (#1652)
➜  Binaries git:(master) cat ~/school/phd/projects/dafny_sandbox/cracking_1.dfy
/// Implement an algorithm to determine whether a string
/// has all unique characters.
method IsUnique(str: array<char>) returns (ret: bool)
    ensures forall i, j :: 0 <= i < j < str.Length ==> ret ==> str[i] != str[j]
{
    ret := multiset
}%
➜  Binaries git:(master) ./dafny ~/school/phd/projects/dafny_sandbox/cracking_1.dfy
/Users/ntaylor/school/phd/projects/dafny_sandbox/cracking_1.dfy(6,11): Error: invalid PrimaryExpression
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dafny.ExprRhs..ctor(Expression expr, Attributes attrs) in /Users/ntaylor/code/dafny/Source/Dafny/AST/DafnyAst.cs:line 7262
   at Microsoft.Dafny.Parser.Rhs(AssignmentRhs& r) in /Users/ntaylor/code/dafny/Source/Dafny/Parser.cs:line 4049
   at Microsoft.Dafny.Parser.UpdateStmt(Statement& s) in /Users/ntaylor/code/dafny/Source/Dafny/Parser.cs:line 3232
   at Microsoft.Dafny.Parser.OneStmt(Statement& s) in /Users/ntaylor/code/dafny/Source/Dafny/Parser.cs:line 3121
   at Microsoft.Dafny.Parser.Stmt(List`1 ss) in /Users/ntaylor/code/dafny/Source/Dafny/Parser.cs:line 3103
   at Microsoft.Dafny.Parser.BlockStmt(BlockStmt& block, IToken& bodyStart, IToken& bodyEnd) in /Users/ntaylor/code/dafny/Source/Dafny/Parser.cs:line 2682
   at Microsoft.Dafny.Parser.MethodDecl(DeclModifierData dmod, Boolean allowConstructor, Method& m) in /Users/ntaylor/code/dafny/Source/Dafny/Parser.cs:line 2148
   at Microsoft.Dafny.Parser.ClassMemberDecl(DeclModifierData dmod, List`1 mm, Boolean allowConstructors, Boolean isValueType, Boolean moduleLevelDecl) in /Users/ntaylor/code/dafny/Source/Dafny/Parser.cs:line 1415
   at Microsoft.Dafny.Parser.TopDecl(ModuleDefinition module, List`1 membersDefaultClass, Boolean isTopLevel, Boolean isAbstract) in /Users/ntaylor/code/dafny/Source/Dafny/Parser.cs:line 973
   at Microsoft.Dafny.Parser.Dafny() in /Users/ntaylor/code/dafny/Source/Dafny/Parser.cs:line 897
   at Microsoft.Dafny.Parser.Parse() in /Users/ntaylor/code/dafny/Source/Dafny/Parser.cs:line 6192
   at Microsoft.Dafny.Parser.Parse(String s, String fullFilename, String filename, Include include, ModuleDecl module, BuiltIns builtIns, Errors errors, Boolean verifyThisFile, Boolean compileThisFile) in /Users/ntaylor/code/dafny/Source/Dafny/Parser.cs:line 286
   at Microsoft.Dafny.Parser.Parse(Boolean useStdin, String filename, Include include, ModuleDecl module, BuiltIns builtIns, Errors errors, Boolean verifyThisFile, Boolean compileThisFile) in /Users/ntaylor/code/dafny/Source/Dafny/Parser.cs:line 236
   at Microsoft.Dafny.Main.ParseFile(DafnyFile dafnyFile, Include include, ModuleDecl module, BuiltIns builtIns, Errors errs, Boolean verifyThisFile, Boolean compileThisFile) in /Users/ntaylor/code/dafny/Source/Dafny/DafnyMain.cs:line 222
   at Microsoft.Dafny.Main.Parse(IList`1 files, String programName, ErrorReporter reporter, Program& program) in /Users/ntaylor/code/dafny/Source/Dafny/DafnyMain.cs:line 131
   at Microsoft.Dafny.Main.ParseCheck(IList`1 files, String programName, ErrorReporter reporter, Program& program) in /Users/ntaylor/code/dafny/Source/Dafny/DafnyMain.cs:line 107
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in /Users/ntaylor/code/dafny/Source/DafnyDriver/DafnyDriver.cs:line 288
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in /Users/ntaylor/code/dafny/Source/DafnyDriver/DafnyDriver.cs:line 55
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass1_0.<Main>b__0() in /Users/ntaylor/code/dafny/Source/DafnyDriver/DafnyDriver.cs:line 36
   at System.Threading.Thread.StartCallback()
[1]    23944 abort      ./dafny ~/school/phd/projects/dafny_sandbox/cracking_1.dfy
➜  Binaries git:(master)
```

Note that I have compiled my own Dafny binaries from Git; however, I can also reproduce it with the 3.3 binary release, it seems (albeit with a slightly different stack trace: it's now in `Parser.Rhs` rather than the `ExprRhs` constructor):

```
➜  dafny ./dafny /version
Dafny 3.3.0.31104
➜  dafny ./dafny ~/school/phd/projects/dafny_sandbox/cracking_1.dfy
/Users/ntaylor/school/phd/projects/dafny_sandbox/cracking_1.dfy(6,11): Error: invalid PrimaryExpression
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dafny.Parser.Rhs(AssignmentRhs& r) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Parser.cs:line 4049
   at Microsoft.Dafny.Parser.UpdateStmt(Statement& s) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Parser.cs:line 3232
   at Microsoft.Dafny.Parser.OneStmt(Statement& s) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Parser.cs:line 3121
   at Microsoft.Dafny.Parser.BlockStmt(BlockStmt& block, IToken& bodyStart, IToken& bodyEnd) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Parser.cs:line 2682
   at Microsoft.Dafny.Parser.MethodDecl(DeclModifierData dmod, Boolean allowConstructor, Method& m) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Parser.cs:line 2148
   at Microsoft.Dafny.Parser.ClassMemberDecl(DeclModifierData dmod, List`1 mm, Boolean allowConstructors, Boolean isValueType, Boolean moduleLevelDecl) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Parser.cs:line 1415
   at Microsoft.Dafny.Parser.TopDecl(ModuleDefinition module, List`1 membersDefaultClass, Boolean isTopLevel, Boolean isAbstract) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Parser.cs:line 973
   at Microsoft.Dafny.Parser.Dafny() in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Parser.cs:line 897
   at Microsoft.Dafny.Parser.Parse() in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Parser.cs:line 6191
   at Microsoft.Dafny.Parser.Parse(String s, String fullFilename, String filename, Include include, ModuleDecl module, BuiltIns builtIns, Errors errors, Boolean verifyThisFile, Boolean compileThisFile) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Parser.cs:line 285
   at Microsoft.Dafny.Parser.Parse(Boolean useStdin, String filename, Include include, ModuleDecl module, BuiltIns builtIns, Errors errors, Boolean verifyThisFile, Boolean compileThisFile) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/Parser.cs:line 235
   at Microsoft.Dafny.Main.ParseFile(DafnyFile dafnyFile, Include include, ModuleDecl module, BuiltIns builtIns, Errors errs, Boolean verifyThisFile, Boolean compileThisFile) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/DafnyMain.cs:line 222
   at Microsoft.Dafny.Main.Parse(IList`1 files, String programName, ErrorReporter reporter, Program& program) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/Dafny/DafnyMain.cs:line 131
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyDriver/DafnyDriver.cs:line 278
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyDriver/DafnyDriver.cs:line 53
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass1_0.<Main>b__0() in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyDriver/DafnyDriver.cs:line 34
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
[1]    24026 abort      ./dafny ~/school/phd/projects/dafny_sandbox/cracking_1.dfy
➜  dafny
```

Of course, I shouldn't expect Dafny to not complain about this program, as, indeed, the RHS of the assignment's invalid.  However, that the NPE gets thrown means that I wasn't able to type something that _might_ have been valid since this is enough to crash the language server.  Thanks!

**Comment by MikaelMayer** [comment]
Indeed ! I was able to reproduce it on my machine. Let me figure out what happens.

**Comment by MikaelMayer** [comment]
I even see three problems in one here:
1) I am able to reproduce it with an even smaller example
```
method IsUnique(str: int) returns (ret: bool)
{
    ret := multiset
}
```
2) It keeps the previous status message in the IDE ("Successfully verified" in my case) instead of saying something like "Parsing..." without indication that there has been a problem, until the user types in some characters
3) After the first crash, the Language Server  no longer responds to any request. and the IDE needs to be restarted
