### ISSUE TITLE
Dafny installation on Docker (Ubuntu focal) crashes on startup

### ISSUE THREAD

**Issue by ssm951** [dafny-lang/dafny#1705]
To save our students time, I decided to create a Docker devcontainer configured for VS Code to allow students to run Dafny no matter the platform. However, I am running into an issue where the dafny installation would show this error when verifying a file, or even running quicktest.sh:
```
Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at VC.Split.get_ProverTask()
   at VC.SplitAndVerifyWorker.DoWork(Split split)
   at VC.SplitAndVerifyWorker.WorkUntilDone()
   --- End of inner exception stack trace ---
   at System.AggregateException.Handle(Func`2 predicate)
   at Microsoft.Boogie.ExecutionEngine.InferAndVerify(Program program, PipelineStatistics stats, String programId, ErrorReporterDelegate er, String requestId)
   at Microsoft.Dafny.DafnyDriver.BoogiePipelineWithRerun(Program program, String bplFileName, PipelineStatistics& stats, String programId) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyDriver/DafnyDriver.cs:line 532
   at Microsoft.Dafny.DafnyDriver.BoogieOnce(String baseFile, String moduleName, Program boogieProgram, String programId, PipelineStatistics& stats, PipelineOutcome& oc) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyDriver/DafnyDriver.cs:line 370
   at Microsoft.Dafny.DafnyDriver.Boogie(String baseName, IEnumerable`1 boogiePrograms, String programId, Dictionary`2& statss, PipelineOutcome& oc) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyDriver/DafnyDriver.cs:line 394
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyDriver/DafnyDriver.cs:line 285
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyDriver/DafnyDriver.cs:line 53
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass1_0.<Main>b__0() in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyDriver/DafnyDriver.cs:line 34
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```
This issue happens whether I used dafny through the CLI or installed Dafny through the extension `dafny-lang.ide-vscode`. Installing through the extension showed that dotnet was installed properly, so I got stumped on what could be the issue. I'm wondering if others that understand this repository better can decipher the error and see what is the issue.

I was trying to build a docker image from the official dotnet base (using Ubuntu focal) and also VS Code's Ubuntu development container with dotnet manually installed. My dafny installation in WSL (Ubuntu) works just fine so I'm not sure of the reason why this error occurs in the container.

Thanks!

**Comment by ssm951** [comment]
I tried looking for other Dockerfile configurations for Dafny and found this implementation: 
https://github.com/franck44/dafny-docker/blob/master/Dockerfile
It added an installation of libgomp1, which is apparently needed for Z3.

Installing that fixed my issue.
