### ISSUE TITLE
Language server exception on iterator with a datatype parameter

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#1790]
To reproduce, open a fresh empty file and paste this code:
```
datatype Node = Node(value: nat)

iterator NodeIterator(n: Node) {}
```

This exception appears in the Dafny Language Server output. Once it does, it recurs on every edit until the tab is closed.

```
[Error - 9:56:34 AM] Request textDocument/documentSymbol failed.
  Message: Internal Error - System.ArgumentException: An item with the same key has already been added. Key: Node
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at Microsoft.Dafny.LanguageServer.Language.Symbols.SymbolTableFactory.DesignatorVisitor.Visit(Formal formal) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/Symbols/SymbolTableFactory.cs:line 125
   at Microsoft.Dafny.LanguageServer.Language.SyntaxTreeVisitor.Visit(Method method) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/SyntaxTreeVisitor.cs:line 87
   at Microsoft.Dafny.LanguageServer.Language.Symbols.SymbolTableFactory.DesignatorVisitor.ProcessNestedScope(Object node, IToken token, Action visit) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/Symbols/SymbolTableFactory.cs:line 201
   at Microsoft.Dafny.LanguageServer.Language.SyntaxTreeVisitor.Visit(ClassDecl classDeclaration) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/SyntaxTreeVisitor.cs:line 49
   at Microsoft.Dafny.LanguageServer.Language.Symbols.SymbolTableFactory.DesignatorVisitor.ProcessNestedScope(Object node, IToken token, Action visit) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/Symbols/SymbolTableFactory.cs:line 201
   at Microsoft.Dafny.LanguageServer.Language.Symbols.SymbolTableFactory.DesignatorVisitor.VisitTopLevelDeclarationWithMembers(TopLevelDeclWithMembers declaration, Action visit) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/Symbols/SymbolTableFactory.cs:line 104
   at Microsoft.Dafny.LanguageServer.Language.SyntaxTreeVisitor.Visit(ModuleDefinition moduleDefinition) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/SyntaxTreeVisitor.cs:line 24
   at Microsoft.Dafny.LanguageServer.Language.Symbols.SymbolTableFactory.DesignatorVisitor.ProcessNestedScope(Object node, IToken token, Action visit) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/Symbols/SymbolTableFactory.cs:line 201
   at Microsoft.Dafny.LanguageServer.Language.SyntaxTreeVisitor.Visit(Program program) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/SyntaxTreeVisitor.cs:line 18
   at Microsoft.Dafny.LanguageServer.Language.Symbols.SymbolTableFactory.CreateFrom(Program program, CompilationUnit compilationUnit, CancellationToken cancellationToken) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Language/Symbols/SymbolTableFactory.cs:line 36
   at Microsoft.Dafny.LanguageServer.Workspace.TextDocumentLoader.LoadInternal(LoadRequest loadRequest) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Workspace/TextDocumentLoader.cs:line 111
   at Microsoft.Dafny.LanguageServer.Workspace.TextDocumentLoader.Run() in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Workspace/TextDocumentLoader.cs:line 83
--- End of stack trace from previous location ---
   at Microsoft.Dafny.LanguageServer.Workspace.TextDocumentLoader.LoadAsync(TextDocumentItem textDocument, CancellationToken cancellationToken) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Workspace/TextDocumentLoader.cs:line 73
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.LoadAndVerifyAsync(TextDocumentItem textDocument, Boolean verify, CancellationToken cancellationToken) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Workspace/DocumentDatabase.cs:line 91
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.OpenAndVerifyAsync(TextDocumentItem textDocument, CancellationToken cancellationToken) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Workspace/DocumentDatabase.cs:line 83
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.<>c__DisplayClass18_0.<<UpdateDocumentAsync>b__0>d.MoveNext() in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Workspace/DocumentDatabase.cs:line 105
--- End of stack trace from previous location ---
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.GetDocumentAsync(TextDocumentIdentifier documentId) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Workspace/DocumentDatabase.cs:line 173
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyDocumentSymbolHandler.Handle(DocumentSymbolParams request, CancellationToken cancellationToken) in /Users/salkeldr/Documents/GitHub/dafny-release/Source/DafnyLanguageServer/Handlers/DafnyDocumentSymbolHandler.cs:line 44
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext()
  Code: -32603 
```

**Comment by MikaelMayer** [comment]
Can't reproduce
