### ISSUE TITLE
Crash in Microsoft.Dafny.Resolver.SanitizeForBoundDiscovery

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/dafny#1948]
The following snippet crashes Dafny as of today:

```
method Example_Forall() {
  assert forall a, b :: a / b * a <= a;
}
```

The error message:

```
tmp.dfy(3,24): Error: the type of this variable is underspecified
tmp.dfy(3,16): Error: type of bound variable 'a' could not be determined; please specify the type explicitly
tmp.dfy(3,19): Error: type of bound variable 'b' could not be determined; please specify the type explicitly
Process terminated. Assumption failed.
   at Microsoft.Dafny.BinaryExpr.get_ResolvedOp() in <path>\Source\Dafny\AST\DafnyAst.cs:line 10946
   at Microsoft.Dafny.Resolver.SanitizeForBoundDiscovery[VT](List`1 boundVars, Int32 bvi, ResolvedOpcode op, List`1 knownBounds, Expression& e0, Expression& e1) in <path>\Source\Dafny\Resolver.cs:line 17515
   at Microsoft.Dafny.Resolver.DiscoverAllBounds_Aux_SingleVar[VT](List`1 bvars, Int32 j, Expression expr, Boolean polarity, List`1 knownBounds) in <path>\Source\Dafny\Resolver.cs:line 17348
   at Microsoft.Dafny.Resolver.DiscoverAllBounds_Aux_MultipleVars[VT](List`1 bvars, Expression expr, Boolean polarity, PoolVirtues requiredVirtues) in <path>\Source\Dafny\Resolver.cs:line 17272
   at Microsoft.Dafny.Resolver.DiscoverBestBounds_MultipleVars[VT](List`1 bvars, Expression expr, Boolean polarity, PoolVirtues requiredVirtues) in <path>\Source\Dafny\Resolver.cs:line 17253
   at Microsoft.Dafny.Resolver.DiscoverBestBounds_MultipleVars_AllowReordering[VT](List`1 bvars, Expression expr, Boolean polarity, PoolVirtues requiredVirtues) in <path>\Source\Dafny\Resolver.cs:line 17206
   at Microsoft.Dafny.Resolver.CheckTypeInference_Visitor.VisitOneExpr(Expression expr) in <path>\Source\Dafny\Resolver.cs:line 6722
   at Microsoft.Dafny.BottomUpVisitor.Visit(Expression expr) in <path>\Source\Dafny\AST\DafnyAst.cs:line 13134
   at Microsoft.Boogie.LinqExtender.Iter[T](IEnumerable`1 coll, Action`1 fn)
   at Microsoft.Dafny.BottomUpVisitor.Visit(Statement stmt) in <path>\Source\Dafny\AST\DafnyAst.cs:line 13139
   at Microsoft.Boogie.LinqExtender.Iter[T](IEnumerable`1 coll, Action`1 fn)
   at Microsoft.Dafny.BottomUpVisitor.Visit(Statement stmt) in <path>\Source\Dafny\AST\DafnyAst.cs:line 13140
   at Microsoft.Dafny.Resolver.CheckTypeInference(Statement stmt, ICodeContext codeContext) in <path>\Source\Dafny\Resolver.cs:line 6615
   at Microsoft.Dafny.Resolver.CheckTypeInference_Member(MemberDecl member) in <path>\Source\Dafny\Resolver.cs:line 6543
   at Microsoft.Dafny.Resolver.ResolveClassMembers_Pass1(TopLevelDeclWithMembers cl) in <path>\Source\Dafny\Resolver.cs:line 3551
   at Microsoft.Dafny.Resolver.ResolveTopLevelDecls_Core(List`1 declarations, Graph`1 datatypeDependencies, Graph`1 codatatypeDependencies, Boolean isAnExport) in <path>\Source\Dafny\Resolver.cs:line 2861
   at Microsoft.Dafny.Resolver.ResolveModuleDefinition(ModuleDefinition m, ModuleSignature sig, Boolean isAnExport) in <path>\Source\Dafny\Resolver.cs:line 1022
   at Microsoft.Dafny.Resolver.ResolveProgram(Program prog) in <path>\Source\Dafny\Resolver.cs:line 497
   at Microsoft.Dafny.Main.Resolve(Program program, ErrorReporter reporter) in <path>\Source\Dafny\DafnyMain.cs:line 162
   at Microsoft.Dafny.Main.ParseCheck(IList`1 files, String programName, ErrorReporter reporter, Program& program) in <path>\Source\Dafny\DafnyMain.cs:line 113
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in <path>\Source\DafnyDriver\DafnyDriver.cs:line 249
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId)
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in <path>\Source\DafnyDriver\DafnyDriver.cs:line 67
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass6_0.<Main>b__0() in <path>\Source\DafnyDriver\DafnyDriver.cs:line 47
   at System.Threading.Thread.StartCallback()
```

**Comment by olivier-aws** [comment]
Closing the issue as it cannot be reproduced with latest Dafny release (4.9.1).
