### ISSUE TITLE
DafnyPipelineTest fails

### ISSUE THREAD

**Issue by hmijail** [dafny-lang/dafny#2043]
Dafny commit https://github.com/dafny-lang/dafny/commit/0e4b2bbd7f4adcb6fcc23a11e28bdbbcabbf5cee
macOS 12.3.1 (on Apple Silicon, in case that matters)

This test was mentioned together with the DafnyLanguageServer.Test, so I ran it even though I have no idea when/whether it matters. (Some explanation would be nice).

The test failed.

```
 dotnet test ./Source/DafnyPipeline.Test
  Determining projects to restore...
  All projects are up-to-date for restore.
  Compiling DafnyRuntimeJava to DafnyRuntimeJava/build/libs/DafnyRuntime.jar...
  DafnyPipeline -> /Users/mija/repos/dafny/dafny/Source/Dafny/bin/Debug/net6.0/DafnyPipeline.dll
  DafnyServer -> /Users/mija/repos/dafny/dafny/Source/DafnyServer/bin/Debug/DafnyServer.dll
  DafnyTestGeneration -> /Users/mija/repos/dafny/dafny/Source/DafnyTestGeneration/bin/Debug/net6.0/DafnyTestGeneration.dll
  DafnyRuntime -> /Users/mija/repos/dafny/dafny/Binaries/net6.0/DafnyRuntime.dll
  Compiling DafnyRuntimeJava to DafnyRuntimeJava/build/libs/DafnyRuntime.jar...
  DafnyDriver -> /Users/mija/repos/dafny/dafny/Binaries/Dafny.dll
  DafnyPipeline.Test -> /Users/mija/repos/dafny/dafny/Source/DafnyPipeline.Test/bin/Debug/net6.0/DafnyPipeline.Test.dll
Test run for /Users/mija/repos/dafny/dafny/Source/DafnyPipeline.Test/bin/Debug/net6.0/DafnyPipeline.Test.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.1.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
dafnyDirectory: /Users/mija/repos/dafny/dafny
DafnyDriverProjectFile: /Users/mija/repos/dafny/dafny/Source/DafnyDriver/DafnyDriver.csproj
foo(6,0): Error: A postcondition might not hold on this return path.
foo(4,17): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    foo(8,21): anon5_Else
foo(35,0): Error: A postcondition might not hold on this return path.
foo(33,17): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    foo(37,21): anon5_Else
foo(75,0): Error: A postcondition might not hold on this return path.
foo(73,17): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    foo(77,21): anon5_Else
foo(35,0): Error: A postcondition might not hold on this return path.
foo(33,17): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    foo(37,21): anon5_Else
foo(36,0): Error: A postcondition might not hold on this return path.
foo(34,18): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    foo(38,22): anon5_Else
foo(35,0): Error: A postcondition might not hold on this return path.
foo(33,17): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    foo(37,21): anon5_Else

Dafny program verifier finished with 0 verified, 0 errors
Wrote textual form of target program to warnings-as-errors.cs
[xUnit.net 00:00:10.53]     DafnyPipeline.Test.RelativePaths.Test [FAIL]
  Failed DafnyPipeline.Test.RelativePaths.Test [426 ms]
  Error Message:
   System.AggregateException : One or more errors occurred. (Could not load file or assembly '10, Version=0.0.0.0, Culture=owerOf10, PublicKeyToken=null'. File is corrupt. (0x8013110E))
---- System.BadImageFormatException : Could not load file or assembly '10, Version=0.0.0.0, Culture=owerOf10, PublicKeyToken=null'. File is corrupt. (0x8013110E)
-------- System.BadImageFormatException : File is corrupt. (0x8013110E)
  Stack Trace:
     at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in /Users/mija/repos/dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 67
   at DafnyPipeline.Test.RelativePaths.Test() in /Users/mija/repos/dafny/dafny/Source/DafnyPipeline.Test/RelativePaths.cs:line 11
----- Inner Stack Trace -----
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoadFromPath(String assemblyPath, String nativeImagePath)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFile(String path)
   at Microsoft.Dafny.Compilers.CsharpCompiler.CompileTargetProgram(String dafnyProgramName, String targetProgramText, String callToMain, String targetFilename, ReadOnlyCollection`1 otherFileNames, Boolean runAfterCompile, TextWriter outputWriter, Object& compilationResult) in /Users/mija/repos/dafny/dafny/Source/Dafny/Compilers/Compiler-Csharp.cs:line 3203
   at Microsoft.Dafny.DafnyDriver.CompileDafnyProgram(Program dafnyProgram, String dafnyProgramName, ReadOnlyCollection`1 otherFileNames, Boolean invokeCompiler, TextWriter outputWriter) in /Users/mija/repos/dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 618
   at Microsoft.Dafny.DafnyDriver.Compile(String fileName, ReadOnlyCollection`1 otherFileNames, Program dafnyProgram, PipelineOutcome oc, IDictionary`2 moduleStats, Boolean verified) in /Users/mija/repos/dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 440
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in /Users/mija/repos/dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 260
----- Inner Stack Trace -----


Failed!  - Failed:     1, Passed:     8, Skipped:     0, Total:     9, Duration: 8 s - /Users/mija/repos/dafny/dafny/Source/DafnyPipeline.Test/bin/Debug/net6.0/DafnyPipeline.Test.dll (net6.0)
```

**Comment by atomb** [comment]
I wonder whether a `dotnet clean` would clear this up?

**Comment by hmijail** [comment]
Actually it's stranger than that. I just re-ran the test without a `clean`, and this time it passed.

I tried reproducing the problem, but I only managed to make the problem happen again once, with a slightly different error message:
```
❯ dotnet test ./Source/DafnyPipeline.Test
  Determining projects to restore...
  All projects are up-to-date for restore.
  Compiling DafnyRuntimeJava to DafnyRuntimeJava/build/libs/DafnyRuntime.jar...
  DafnyPipeline -> /Users/mija/repos/dafny/dafny/Source/Dafny/bin/Debug/net6.0/DafnyPipeline.dll
  DafnyServer -> /Users/mija/repos/dafny/dafny/Source/DafnyServer/bin/Debug/DafnyServer.dll
  DafnyTestGeneration -> /Users/mija/repos/dafny/dafny/Source/DafnyTestGeneration/bin/Debug/net6.0/DafnyTestGeneration.dll
  DafnyRuntime -> /Users/mija/repos/dafny/dafny/Binaries/net6.0/DafnyRuntime.dll
  Compiling DafnyRuntimeJava to DafnyRuntimeJava/build/libs/DafnyRuntime.jar...
  DafnyDriver -> /Users/mija/repos/dafny/dafny/Binaries/Dafny.dll
  DafnyPipeline.Test -> /Users/mija/repos/dafny/dafny/Source/DafnyPipeline.Test/bin/Debug/net6.0/DafnyPipeline.Test.dll
Test run for /Users/mija/repos/dafny/dafny/Source/DafnyPipeline.Test/bin/Debug/net6.0/DafnyPipeline.Test.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.1.0
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
dafnyDirectory: /Users/mija/repos/dafny/dafny
DafnyDriverProjectFile: /Users/mija/repos/dafny/dafny/Source/DafnyDriver/DafnyDriver.csproj
foo(6,0): Error: A postcondition might not hold on this return path.
foo(4,17): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    foo(8,21): anon5_Else
foo(35,0): Error: A postcondition might not hold on this return path.
foo(33,17): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    foo(37,21): anon5_Else
foo(75,0): Error: A postcondition might not hold on this return path.
foo(73,17): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    foo(77,21): anon5_Else
foo(35,0): Error: A postcondition might not hold on this return path.
foo(33,17): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    foo(37,21): anon5_Else
foo(36,0): Error: A postcondition might not hold on this return path.
foo(34,18): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    foo(38,22): anon5_Else
foo(35,0): Error: A postcondition might not hold on this return path.
foo(33,17): Related location: This is the postcondition that might not hold.
Execution trace:
    (0,0): anon0
    foo(37,21): anon5_Else

Dafny program verifier finished with 0 verified, 0 errors
Wrote textual form of target program to warnings-as-errors.cs
[xUnit.net 00:00:09.64]     DafnyPipeline.Test.RelativePaths.Test [FAIL]
  Failed DafnyPipeline.Test.RelativePaths.Test [437 ms]
  Error Message:
   System.AggregateException : One or more errors occurred. (Could not load file or assembly '�, Version=32772.0.0.0, Culture=�, PublicKeyToken=null'. Index not found. (0x80131124))
---- System.BadImageFormatException : Could not load file or assembly '�, Version=32772.0.0.0, Culture=�, PublicKeyToken=null'. Index not found. (0x80131124)
-------- System.BadImageFormatException : Index not found. (0x80131124)
  Stack Trace:
     at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in /Users/mija/repos/dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 67
   at DafnyPipeline.Test.RelativePaths.Test() in /Users/mija/repos/dafny/dafny/Source/DafnyPipeline.Test/RelativePaths.cs:line 11
----- Inner Stack Trace -----
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromPath(IntPtr ptrNativeAssemblyLoadContext, String ilPath, String niPath, ObjectHandleOnStack retAssembly)
   at System.Runtime.Loader.AssemblyLoadContext.InternalLoadFromPath(String assemblyPath, String nativeImagePath)
   at System.Runtime.Loader.AssemblyLoadContext.LoadFromAssemblyPath(String assemblyPath)
   at System.Reflection.Assembly.LoadFile(String path)
   at Microsoft.Dafny.Compilers.CsharpCompiler.CompileTargetProgram(String dafnyProgramName, String targetProgramText, String callToMain, String targetFilename, ReadOnlyCollection`1 otherFileNames, Boolean runAfterCompile, TextWriter outputWriter, Object& compilationResult) in /Users/mija/repos/dafny/dafny/Source/Dafny/Compilers/Compiler-Csharp.cs:line 3203
   at Microsoft.Dafny.DafnyDriver.CompileDafnyProgram(Program dafnyProgram, String dafnyProgramName, ReadOnlyCollection`1 otherFileNames, Boolean invokeCompiler, TextWriter outputWriter) in /Users/mija/repos/dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 618
   at Microsoft.Dafny.DafnyDriver.Compile(String fileName, ReadOnlyCollection`1 otherFileNames, Program dafnyProgram, PipelineOutcome oc, IDictionary`2 moduleStats, Boolean verified) in /Users/mija/repos/dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 440
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in /Users/mija/repos/dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 260
----- Inner Stack Trace -----


Failed!  - Failed:     1, Passed:     8, Skipped:     0, Total:     9, Duration: 8 s - /Users/mija/repos/dafny/dafny/Source/DafnyPipeline.Test/bin/Debug/net6.0/DafnyPipeline.Test.dll (net6.0)
```

Since then it always has worked correctly.

I'll keep an eye on it and reopen if it happens again.

**Comment by hmijail** [comment]
(It still would be nice to have some indication of whether I, as a desktop user, should care for this particular test or not. Is the "pipeline" in the title referring to CI or something like that?)
