### ISSUE TITLE
Crash in PrettyArrowTypeName

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/dafny#2104]
Input:

```
const F := ((f: A -> bool) => f(f))
```

Output:

```
test.dfy(1,16): Error: Undeclared top-level type or type parameter: A (did you forget to qualify a name or declare a module import 'opened'?)
test.dfy(1,21): Error: Undeclared top-level type or type parameter: A (did you forget to qualify a name or declare a module import 'opened'?)
Unhandled exception. System.AggregateException: One or more errors occurred. (Sequence contains no elements)
 ---> System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Last[TSource](IEnumerable`1 source)
   at Microsoft.Dafny.ArrowType.PrettyArrowTypeName(String arrow, List`1 typeArgs, Type result, ModuleDefinition context, Boolean parseAble) in C:\dafny\Source\Dafny\AST\DafnyAst.cs:line 2604
   at Microsoft.Dafny.UserDefinedType.TypeName(ModuleDefinition context, Boolean parseAble) in C:\dafny\Source\Dafny\AST\DafnyAst.cs:line 3019
   at Microsoft.Dafny.Type.ToString() in C:\dafny\Source\Dafny\AST\DafnyAst.cs:line 703
   at System.Text.ValueStringBuilder.AppendFormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.FormatHelper(IFormatProvider provider, String format, ParamsArray args)
   at System.String.Format(String format, Object[] args)
   at Microsoft.Dafny.ErrorReporter.Error(MessageSource source, IToken tok, String msg, Object[] args) in C:\dafny\Source\Dafny\Reporting.cs:line 67
   at Microsoft.Dafny.Resolver.ResolveApplySuffix(ApplySuffix e, ResolveOpts opts, Boolean allowMethodCall) in C:\dafny\Source\Dafny\Resolver.cs:line 16736
   at Microsoft.Dafny.Resolver.ResolveExpression(Expression expr, ResolveOpts opts) in C:\dafny\Source\Dafny\Resolver.cs:line 14739
   at Microsoft.Dafny.Resolver.ResolveExpression(Expression expr, ResolveOpts opts) in C:\dafny\Source\Dafny\Resolver.cs:line 15304
   at Microsoft.Dafny.Resolver.ResolveExpression(Expression expr, ResolveOpts opts) in C:\dafny\Source\Dafny\Resolver.cs:line 14605
   at Microsoft.Dafny.Resolver.ResolveTopLevelDecls_Core(List`1 declarations, Graph`1 datatypeDependencies, Graph`1 codatatypeDependencies, Boolean isAnExport) in C:\dafny\Source\Dafny\Resolver.cs:line 2728
   at Microsoft.Dafny.Resolver.ResolveModuleDefinition(ModuleDefinition m, ModuleSignature sig, Boolean isAnExport) in C:\dafny\Source\Dafny\Resolver.cs:line 1032
   at Microsoft.Dafny.Resolver.ResolveProgram(Program prog) in C:\dafny\Source\Dafny\Resolver.cs:line 507
   at Microsoft.Dafny.Main.Resolve(Program program, ErrorReporter reporter) in C:\dafny\Source\Dafny\DafnyMain.cs:line 162
   at Microsoft.Dafny.Main.ParseCheck(IList`1 files, String programName, ErrorReporter reporter, Program& program) in C:\dafny\Source\Dafny\DafnyMain.cs:line 113
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in C:\dafny\Source\DafnyDriver\DafnyDriver.cs:line 249
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in C:\dafny\Source\DafnyDriver\DafnyDriver.cs:line 67
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass6_0.<Main>b__0() in C:\dafny\Source\DafnyDriver\DafnyDriver.cs:line 47
   at System.Threading.Thread.StartCallback()
```

**Comment by MikaelMayer** [comment]
I can no longer reproduce this issue. Might have been fixed.
