### ISSUE TITLE
Crash in TypeSubstitutionMap

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/dafny#2113]
Input:

```dafny
type T
datatype Box2<T, R> = Box(t: T)
type Box1<A> = Box2<A, T>

method Main(r: Box1<int>) {
  match r {
    case Box(EOF) => return;
    case Box(err) => return;
  }
}
```

Output:

```
Unhandled exception. System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'))
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Microsoft.Dafny.Resolver.TypeSubstitutionMap(List`1 formals, List`1 actuals) in C:\dafny\Source\Dafny\Resolver.cs:line 14342
   at Microsoft.Dafny.Resolver.CheckLinearExtendedPattern(Type type, ExtendedPattern pat, ResolveOpts opts) in C:\dafny\Source\Dafny\Resolver.cs:line 12740
   at Microsoft.Dafny.Resolver.CheckLinearNestedMatchCase(Type type, NestedMatchCase mc, ResolveOpts opts) in C:\dafny\Source\Dafny\Resolver.cs:line 12761
   at Microsoft.Dafny.Resolver.CompileNestedMatchStmt(NestedMatchStmt s, ResolveOpts opts) in C:\dafny\Source\Dafny\Resolver.cs:line 12587
   at Microsoft.Dafny.Resolver.ResolveNestedMatchStmt(NestedMatchStmt s, ResolveOpts opts) in C:\dafny\Source\Dafny\Resolver.cs:line 11735
   at Microsoft.Dafny.Resolver.ResolveStatement(Statement stmt, ICodeContext codeContext) in C:\dafny\Source\Dafny\Resolver.cs:line 11646
   at Microsoft.Dafny.Resolver.ResolveStatementWithLabels(Statement stmt, ICodeContext codeContext) in C:\dafny\Source\Dafny\Resolver.cs:line 13630
   at Microsoft.Dafny.Resolver.ResolveBlockStatement(BlockStmt blockStmt, ICodeContext codeContext) in C:\dafny\Source\Dafny\Resolver.cs:line 13600
   at Microsoft.Dafny.Resolver.ResolveMethod(Method m) in C:\dafny\Source\Dafny\Resolver.cs:line 10395
   at Microsoft.Dafny.Resolver.ResolveClassMemberBodies(TopLevelDeclWithMembers cl) in C:\dafny\Source\Dafny\Resolver.cs:line 9608
   at Microsoft.Dafny.Resolver.ResolveTopLevelDecls_Core(List`1 declarations, Graph`1 datatypeDependencies, Graph`1 codatatypeDependencies, Boolean isAnExport) in C:\dafny\Source\Dafny\Resolver.cs:line 2818
   at Microsoft.Dafny.Resolver.ResolveModuleDefinition(ModuleDefinition m, ModuleSignature sig, Boolean isAnExport) in C:\dafny\Source\Dafny\Resolver.cs:line 1032
   at Microsoft.Dafny.Resolver.ResolveProgram(Program prog) in C:\dafny\Source\Dafny\Resolver.cs:line 507
   at Microsoft.Dafny.Main.Resolve(Program program, ErrorReporter reporter) in C:\dafny\Source\Dafny\DafnyMain.cs:line 162
   at Microsoft.Dafny.Main.ParseCheck(IList`1 files, String programName, ErrorReporter reporter, Program& program) in C:\dafny\Source\Dafny\DafnyMain.cs:line 113
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in C:\dafny\Source\DafnyDriver\DafnyDriver.cs:line 249
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in C:\dafny\Source\DafnyDriver\DafnyDriver.cs:line 67
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass6_0.<Main>b__0() in C:\dafny\Source\DafnyDriver\DafnyDriver.cs:line 47
   at System.Threading.Thread.StartCallback()
```

**Comment by MikaelMayer** [comment]
I tested this and it no longer crashes Dafny. Must have been fixed previously.
