### ISSUE TITLE
Language server crashing when adding `{:opaque}` on datatype predicate.

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#2207]
Launch the following example in VSCode:

```dafny
  predicate method {:opaque} Valid() {
    true
  }
```
It is stuck verifying. Same if starting from the second version directly. Running this example on the command-line is fine though.
Logs show the following exception:

```
[23:18:48 ERR Microsoft.Dafny.LanguageServer.Handlers.DafnyTextDocumentHandler] error while handling document event
System.ArgumentException: An element with the same key but a different value already exists. Key: '(line: 2, char: 29)'
   at System.Collections.Immutable.ImmutableDictionary`2.HashBucket.Add(TKey key, TValue value, IEqualityComparer`1 keyOnlyComparer, IEqualityComparer`1 valueComparer, KeyCollisionBehavior behavior, OperationResult& result)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 items, MutationInput origin, KeyCollisionBehavior collisionBehavior)
   at System.Collections.Immutable.ImmutableDictionary`2.AddRange(IEnumerable`1 pairs, Boolean avoidToHashMap)
   at System.Collections.Immutable.ImmutableDictionary.ToImmutableDictionary[TSource,TKey,TValue](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 keyComparer, IEqualityComparer`1 valueComparer)
   at System.Collections.Immutable.ImmutableDictionary.ToImmutableDictionary[TSource,TKey,TValue](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Microsoft.Dafny.LanguageServer.Workspace.VerificationProgressReporter.ReportImplementationsBeforeVerification(Implementation[] implementations) in dafny\Source\DafnyLanguageServer\Workspace\VerificationProgressReporter.cs:line 173
   at Microsoft.Dafny.LanguageServer.Workspace.TextDocumentLoader.Verify(DafnyDocument document, CancellationToken cancellationToken) in dafny\Source\DafnyLanguageServer\Workspace\TextDocumentLoader.cs:line 190
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.<>c__DisplayClass18_0.<Verify>b__0(Task`1 task) in dafny\Source\DafnyLanguageServer\Workspace\DocumentDatabase.cs:line 124
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
```

I am using the latest master branch for Dafny and the latest master branch for VSCode.

The issue is, `{:opaque}` creates a lemma with the same position, so the conversion to immutable dictionary fails. We should merge the auto-generated lemma verification tree with the original method or function tree.

**Comment by keyboardDrummer** [comment]
Might be good to use and update `TextDocumentLoader.GetImplementationId`

**Comment by MikaelMayer** [comment]
> Might be good to use and update TextDocumentLoader.GetImplementationId

Indeed, it guarantees the unicity of implementation Ids. In my case, unicity was not the real problem, as the verification tree freely tolerates multiple implementations per top-level declaration.
It's just that two top-level declarations had the same position, and since I'm labelling top-level declarations for better hover diagnostics, I need to make a choice, and the choice is obvious: the labelling of the top-level declaration should be the one explicitly provided by the user, not the implicitly generated one.
There might be other cases where we generate more Dafny methods, but this PR takes care of regrouping them now.
