### ISSUE TITLE
Test `ReorderingVerificationGutterStatusTester.EnsuresPriorityWorksEvenIfRemovingMethods` is unstable

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/dafny#2214]
Same holds for `EnsuresPriorityWorksEvenIfRemovingMethodsWhileTypo` (note the WhileTypo)

From: https://github.com/dafny-lang/dafny/runs/6773362112?check_suite_focus=true
```
A total of 1 test files matched the specified pattern.
  Failed EnsuresPriorityWorksEvenIfRemovingMethods [50 s]
  Error Message:
   Test method Microsoft.Dafny.LanguageServer.IntegrationTest.Diagnostics.ReorderingVerificationGutterStatusTester.EnsuresPriorityWorksEvenIfRemovingMethods threw exception: 
System.OperationCanceledException: The operation was canceled.
  Stack Trace:
      at System.Threading.CancellationToken.ThrowOperationCanceledException()
   at System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(TaskNode asyncWaiter, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.IntegrationTest.Util.TestNotificationReceiver`1.AwaitNextNotificationAsync(CancellationToken cancellationToken) in /Users/runner/work/dafny/dafny/Source/DafnyLanguageServer.Test/Util/TestNotificationReceiver.cs:line 20
   at Microsoft.Dafny.LanguageServer.IntegrationTest.Diagnostics.LinearVerificationGutterStatusTester.GetAllLineVerificationStatuses(TextDocumentItem documentItem, TestNotificationReceiver`1 verificationStatusGutterReceiver) in /Users/runner/work/dafny/dafny/Source/DafnyLanguageServer.Test/GutterStatus/LinearVerificationGutterStatusTester.cs:line 116
   at Microsoft.Dafny.LanguageServer.IntegrationTest.Diagnostics.LinearVerificationGutterStatusTester.VerifyTrace(String codeAndTrace, String fileName, Boolean testTrace, TestNotificationReceiver`1 verificationStatusGutterReceiver) in /Users/runner/work/dafny/dafny/Source/DafnyLanguageServer.Test/GutterStatus/LinearVerificationGutterStatusTester.cs:line 236
   at Microsoft.Dafny.LanguageServer.IntegrationTest.Diagnostics.ReorderingVerificationGutterStatusTester.TestPriorities(String code, String expectedPriorities) in /Users/runner/work/dafny/dafny/Source/DafnyLanguageServer.Test/GutterStatus/ReorderingVerificationGutterStatusTester.cs:line 143
   at Microsoft.Dafny.LanguageServer.IntegrationTest.Diagnostics.ReorderingVerificationGutterStatusTester.EnsuresPriorityWorksEvenIfRemovingMethods() in /Users/runner/work/dafny/dafny/Source/DafnyLanguageServer.Test/GutterStatus/ReorderingVerificationGutterStatusTester.cs:line 102
```

**Comment by keyboardDrummer** [comment]
Seems like it just times out sometimes

**Comment by MikaelMayer** [comment]
Both are in the same test suite.

How come they can timeout?! I am using `-proverOpt:SOLVER=noop` so that there is no solver invocation involved.

**Comment by cpitclaudel** [comment]
Another maybe-related issue today? https://github.com/dafny-lang/dafny/runs/6785638824?check_suite_focus=true#step:8:225

```
Test run for /Users/runner/work/dafny/dafny/Source/DafnyLanguageServer.Test/bin/Debug/net6.0/DafnyLanguageServer.Test.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.2.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed HoveringExistsBoundVarReturnsBoundVarInferredType [550 ms]
  Error Message:
   Assert.AreEqual failed. Expected:<```dafny
j: int
```>. Actual:<[Error:](https://dafny-lang.github.io/dafny/DafnyRef/DafnyRef#sec-verification-debugging) assertion might not hold  
This is the only assertion in method f  
Resource usage: 7K RU  
```dafny
j: int
```>. 
  Stack Trace:
     at Microsoft.Dafny.LanguageServer.IntegrationTest.Lookup.HoverTest.HoveringExistsBoundVarReturnsBoundVarInferredType() in /Users/runner/work/dafny/dafny/Source/DafnyLanguageServer.Test/Lookup/HoverTest.cs:line 370
Results File: /Users/runner/work/dafny/dafny/Source/DafnyLanguageServer.Test/TestResults/_Mac-1654650293851_2022-06-08_01_47_54.trx
```

**Comment by MikaelMayer** [comment]
Is this a stable error?

**Comment by MikaelMayer** [comment]
> EnsuresPriorityWorksEvenIfRemovingMethodsWhileTypo

Since this file heavily relies on edits and changes, it's possible it's related to recent LSP problems that were fixed like this one https://github.com/dafny-lang/dafny/pull/2240 or that one in Boogie https://github.com/boogie-org/boogie/pull/588

I'll mark it as "fixed" with https://github.com/dafny-lang/dafny/pull/2215 which bumps the Boogie version, so that if it happens again, we will know it was not related to these bugs.

**Comment by MikaelMayer** [comment]
It actually took 30 minutes, but I was still able to reproduce the issue.
