### ISSUE TITLE
Crash in Resolver.ImposeSubtypingConstraint

### ISSUE THREAD

**Issue by ghost** [dafny-lang/dafny#2248]
I have a .dfy containing an "inductive predicate" and an "inductive lemma". I have translated them to "least predicate" and "least lemma", to use the last release of Dafny over VSCode
```dafny
least predicate is_derivable (s:string)
{
s == ""
||
(exists s0 :: is_derivable(s0) && s == "ab" + s0)
||
(exists s0 :: is_derivable(s0) && s == "ba" + s0)
||
(exists s1, s2 :: is_derivable(s1) && is_derivable(s2) && s == s1 + s2)
}

function numberOf(c:char,s:string):nat
{
if s == "" then 0 
else if s[0] == c then 1 + numberOf(c,s[1..])
else numberOf(c,s[1..])
}

least lemma correctness_Lemma(s:string)
requires is_derivable(s) 
ensures numberOf('a',s) == numberOf('b',s)
{
if s == "" { }
else if exists  s0 :: is_derivable(s0) && s == "ab" + s0 {
		var s0 :| is_derivable(s0) && s == "ab" + s0;
		correctness_Lemma(s0);
		}
else if exists s0:: is_derivable(s0) && s == "ba" + s0 {
	 var s0 :| is_derivable(s0) && s == "ba" + s0;
	 correctness_Lemma(s0);
	 }
else { 
      //assert exists s1, s2 :: is_derivable(s1) && is_derivable(s2) && s == s1 + s2;
      var s1, s2  :| is_derivable(s1) && is_derivable(s2) && s == s1 + s2;
	  correctness_Lemma(s1); //assert numberOf('a',s1) == numberOf('b',s1); //IH
	  correctness_Lemma(s2); //assert numberOf('a',s2) == numberOf('b',s2); //IH
      calc {
            numberOf('a',s);
			   {
			   //assert s == s1 + s2;
			   assume forall c :: numberOf(c,s1+s2) == numberOf(c,s1) + numberOf(c,s2);
			   }
			numberOf('a',s1) + numberOf('a',s2);
			numberOf('b',s1) + numberOf('b',s2);
			   {
			   assume forall c :: numberOf(c,s1+s2) == numberOf(c,s1) + numberOf(c,s2);
			   }
			numberOf('b',s); 
     }}
}
```

but they produce the following error:

```
[Error - 13:10:10] Request textDocument/hover failed.
  Message: Internal Error - System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at Microsoft.Dafny.Resolver.ImposeSubtypingConstraint(Type super, Type sub, ErrorMsg errorMsg)
   at Microsoft.Dafny.Resolver.AssignProxyAndHandleItsConstraints_aux(TypeProxy proxy, Type t, Boolean keepConstraints)
   at Microsoft.Dafny.Resolver.AssignProxyAndHandleItsConstraints_aux(TypeProxy proxy, Type t, Boolean keepConstraints)
   at Microsoft.Dafny.Resolver.AssignKnownEndsFullstrength_SuperDirection(TypeProxy proxy)
   at Microsoft.Dafny.Resolver.ProcessFullStrength_SuperDirection(Type t, ISet`1 processed, Boolean& anyNewConstraints)
   at Microsoft.Dafny.Resolver.PartiallySolveTypeConstraints(Boolean allowDecisions)
   at Microsoft.Dafny.Resolver.SolveAllTypeConstraints()
   at Microsoft.Dafny.Resolver.ResolveFunction(Function f)
   at Microsoft.Dafny.Resolver.ResolveClassMemberBodies(TopLevelDeclWithMembers cl)
   at Microsoft.Dafny.Resolver.ResolveTopLevelDecls_Core(List`1 declarations, Graph`1 datatypeDependencies, Graph`1 codatatypeDependencies, Boolean isAnExport)
   at Microsoft.Dafny.Resolver.ResolveModuleDefinition(ModuleDefinition m, ModuleSignature sig, Boolean isAnExport)
   at Microsoft.Dafny.Resolver.ResolveProgram(Program prog)
   at Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver.RunDafnyResolver(TextDocumentItem document, Program program)
   at Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver.ResolveSymbols(TextDocumentItem textDocument, Program program, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.TextDocumentLoader.LoadInternal(TextDocumentItem textDocument, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.TextDocumentLoader.<>c__DisplayClass13_0.<<LoadAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.ApplyChangesAsync(Task`1 oldDocumentTask, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentDatabase.GetDocumentAsync(TextDocumentIdentifier documentId)
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyHoverHandler.Handle(HoverParams request, CancellationToken cancellationToken)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext()
  Code: -32603
```

**Comment by MikaelMayer** [comment]
Can you please post a small example so that we can reproduce it?

**Comment by jiplucap** [comment]
`least predicate is_derivable (s:string)
{
s == ""
||
(exists s0 :: is_derivable(s0) && s == "ab" + s0)
||
(exists s0 :: is_derivable(s0) && s == "ba" + s0)
||
(exists s1, s2 :: is_derivable(s1) && is_derivable(s2) && s == s1 + s2)
}

function numberOf(c:char,s:string):nat
{
if s == "" then 0 
else if s[0] == c then 1 + numberOf(c,s[1..])
else numberOf(c,s[1..])
}

least lemma correctness_Lemma(s:string)
requires is_derivable(s) 
ensures numberOf('a',s) == numberOf('b',s)
{
if s == "" { }
else if exists  s0 :: is_derivable(s0) && s == "ab" + s0 {
		var s0 :| is_derivable(s0) && s == "ab" + s0;
		correctness_Lemma(s0);
		}
else if exists s0:: is_derivable(s0) && s == "ba" + s0 {
	 var s0 :| is_derivable(s0) && s == "ba" + s0;
	 correctness_Lemma(s0);
	 }
else { 
      //assert exists s1, s2 :: is_derivable(s1) && is_derivable(s2) && s == s1 + s2;
      var s1, s2  :| is_derivable(s1) && is_derivable(s2) && s == s1 + s2;
	  correctness_Lemma(s1); //assert numberOf('a',s1) == numberOf('b',s1); //IH
	  correctness_Lemma(s2); //assert numberOf('a',s2) == numberOf('b',s2); //IH
      calc {
            numberOf('a',s);
			   {
			   //assert s == s1 + s2;
			   assume forall c :: numberOf(c,s1+s2) == numberOf(c,s1) + numberOf(c,s2);
			   }
			numberOf('a',s1) + numberOf('a',s2);
			numberOf('b',s1) + numberOf('b',s2);
			   {
			   assume forall c :: numberOf(c,s1+s2) == numberOf(c,s1) + numberOf(c,s2);
			   }
			numberOf('b',s); 
     }}
}`

**Comment by cpitclaudel** [comment]
This is what I see:

```
Process terminated. Assertion failed.
   at Microsoft.Dafny.Resolver.ImposeSubtypingConstraint(Type super, Type sub, ErrorMsg errorMsg) in C:\dafny\master\Source\Dafny\Resolver.cs:line 4796
   at Microsoft.Dafny.Resolver.AssignProxyAndHandleItsConstraints_aux(TypeProxy proxy, Type t, Boolean keepConstraints) in C:\dafny\master\Source\Dafny\Resolver.cs:line 4764
   at Microsoft.Dafny.Resolver.AssignProxyAndHandleItsConstraints(TypeProxy proxy, Type t, Boolean keepConstraints) in C:\dafny\master\Source\Dafny\Resolver.cs:line 4667
   at Microsoft.Dafny.Resolver.AssignProxyAndHandleItsConstraints_aux(TypeProxy proxy, Type t, Boolean keepConstraints) in C:\dafny\master\Source\Dafny\Resolver.cs:line 4756
   at Microsoft.Dafny.Resolver.AssignProxyAndHandleItsConstraints(TypeProxy proxy, Type t, Boolean keepConstraints) in C:\dafny\master\Source\Dafny\Resolver.cs:line 4667
   at Microsoft.Dafny.Resolver.AssignKnownEndsFullstrength_SuperDirection(TypeProxy proxy) in C:\dafny\master\Source\Dafny\Resolver.cs:line 6404
   at Microsoft.Dafny.Resolver.ProcessFullStrength_SuperDirection(Type t, ISet`1 processed, Boolean& anyNewConstraints) in C:\dafny\master\Source\Dafny\Resolver.cs:line 6121
   at Microsoft.Dafny.Resolver.PartiallySolveTypeConstraints(Boolean allowDecisions) in C:\dafny\master\Source\Dafny\Resolver.cs:line 5691
   at Microsoft.Dafny.Resolver.SolveAllTypeConstraints() in C:\dafny\master\Source\Dafny\Resolver.cs:line 6479
   at Microsoft.Dafny.Resolver.ResolveFunction(Function f) in C:\dafny\master\Source\Dafny\Resolver.cs:line 10199
   at Microsoft.Dafny.Resolver.ResolveClassMemberBodies(TopLevelDeclWithMembers cl) in C:\dafny\master\Source\Dafny\Resolver.cs:line 9593
   at Microsoft.Dafny.Resolver.ResolveTopLevelDecls_Core(List`1 declarations, Graph`1 datatypeDependencies, Graph`1 codatatypeDependencies, Boolean isAnExport) in C:\dafny\master\Source\Dafny\Resolver.cs:line 2821
   at Microsoft.Dafny.Resolver.ResolveModuleDefinition(ModuleDefinition m, ModuleSignature sig, Boolean isAnExport) in C:\dafny\master\Source\Dafny\Resolver.cs:line 1035
   at Microsoft.Dafny.Resolver.ResolveProgram(Program prog) in C:\dafny\master\Source\Dafny\Resolver.cs:line 507
   at Microsoft.Dafny.Main.Resolve(Program program, ErrorReporter reporter) in C:\dafny\master\Source\Dafny\DafnyMain.cs:line 162
   at Microsoft.Dafny.Main.ParseCheck(IList`1 files, String programName, ErrorReporter reporter, Program& program) in C:\dafny\master\Source\Dafny\DafnyMain.cs:line 113
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in C:\dafny\master\Source\DafnyDriver\DafnyDriver.cs:line 249
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId)
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in C:\dafny\master\Source\DafnyDriver\DafnyDriver.cs:line 67
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass6_0.<Main>b__0() in C:\dafny\master\Source\DafnyDriver\DafnyDriver.cs:line 47
   at System.Threading.Thread.StartCallback()
```

**Comment by cpitclaudel** [comment]
A workaround is to add a type annotation on `s1` and `s2`  in `is_derivable`:

```
    (exists s1: string, s2: string :: is_derivable(s1) && is_derivable(s2) && s == s1 + s2)
```

The following complete example verifies:

```
least predicate is_derivable (s:string)
{
  || s == ""
  || (exists s0 :: is_derivable(s0) && s == "ab" + s0)
  || (exists s0 :: is_derivable(s0) && s == "ba" + s0)
  || (exists s1: string, s2: string :: is_derivable(s1) && is_derivable(s2) && s == s1 + s2)
}

function numberOf(c:char,s:string):nat
{
  if s == "" then 0
  else if s[0] == c then 1 + numberOf(c,s[1..])
  else numberOf(c,s[1..])
}

least lemma correctness_Lemma(s:string)
  requires is_derivable(s)
  ensures numberOf('a',s) == numberOf('b',s)
{
  if s == "" { }
  else if exists  s0 :: is_derivable(s0) && s == "ab" + s0 {
		var s0 :| is_derivable(s0) && s == "ab" + s0;
		correctness_Lemma(s0);
	}
  else if exists s0:: is_derivable(s0) && s == "ba" + s0 {
	  var s0 :| is_derivable(s0) && s == "ba" + s0;
	  correctness_Lemma(s0);
	}
  else {
    //assert exists s1, s2 :: is_derivable(s1) && is_derivable(s2) && s == s1 + s2;
    var s1, s2  :| is_derivable(s1) && is_derivable(s2) && s == s1 + s2;
	  correctness_Lemma(s1); //assert numberOf('a',s1) == numberOf('b',s1); //IH
	  correctness_Lemma(s2); //assert numberOf('a',s2) == numberOf('b',s2); //IH
    calc {
      numberOf('a',s);
			   {
			    //assert s == s1 + s2;
			    assume forall c :: numberOf(c,s1+s2) == numberOf(c,s1) + numberOf(c,s2);
			   }
			   numberOf('a',s1) + numberOf('a',s2);
			   numberOf('b',s1) + numberOf('b',s2);
			   {
			    assume forall c :: numberOf(c,s1+s2) == numberOf(c,s1) + numberOf(c,s2);
			   }
			   numberOf('b',s);
    }}
}
```

**Comment by keyboardDrummer** [comment]
Resolved by https://github.com/dafny-lang/dafny/pull/2954
