### ISSUE TITLE
ReorderingVerificationGutterStatusTester.TestPriorities test is unstable

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/dafny#2285]
```
A total of 1 test files matched the specified pattern.
  Failed EnsuresPriorityWorksEvenIfRemovingMethodsWhileTypo [544 ms]
  Error Message:
   Assert.AreEqual failed. Expected:< 1, 1, 1, 1, 1  1, 1, 1,10, 1  1, 1, 1, 9,10  1,10, 8, 9>. Actual:< 1, 1, 1, 1, 1  1, 1, 1,10, 1  1, 1, 1, 9,10  1,10, 1, 1>. 
  Stack Trace:
     at Microsoft.Dafny.LanguageServer.IntegrationTest.Diagnostics.ReorderingVerificationGutterStatusTester.TestPriorities(String code, String expectedPriorities) in /home/runner/work/dafny/dafny/Source/DafnyLanguageServer.Test/GutterStatus/ReorderingVerificationGutterStatusTester.cs:line 155
   at Microsoft.Dafny.LanguageServer.IntegrationTest.Diagnostics.ReorderingVerificationGutterStatusTester.<EnsuresPriorityWorksEvenIfRemovingMethodsWhileTypo>b__6_0() in /home/runner/work/dafny/dafny/Source/DafnyLanguageServer.Test/GutterStatus/ReorderingVerificationGutterStatusTester.cs:line 130
   at Microsoft.Dafny.LanguageServer.IntegrationTest.DafnyLanguageServerTestBase.WithNoopSolver(Func`1 action) in /home/runner/work/dafny/dafny/Source/DafnyLanguageServer.Test/DafnyLanguageServerTestBase.cs:line 166
   at Microsoft.Dafny.LanguageServer.IntegrationTest.Diagnostics.ReorderingVerificationGutterStatusTester.EnsuresPriorityWorksEvenIfRemovingMethodsWhileTypo() in /home/runner/work/dafny/dafny/Source/DafnyLanguageServer.Test/GutterStatus/ReorderingVerificationGutterStatusTester.cs:line 129
```

**Comment by MikaelMayer** [comment]
It's interesting that this test catches an instability, this seems like a smoke we ought to fix before it turns into fire.

I couldn't figure out why it happens, but here is my preliminary analysis.
The tests first loops here, by sending edit APIs and then waiting agressively on the result:

https://github.com/dafny-lang/dafny/blob/479bdda4f676bf12d743c15e03db1c43dc05d9f6/Source/DafnyLanguageServer.Test/GutterStatus/LinearVerificationGutterStatusTester.cs#L234-L237

Here we apply changes, and then we await every gutter status notification until the last one which does not indicate any more work (no more "obsolete" or "-ing" icons like Verifying)
In the unstable test, and at the moment the priorities are not the one expected (the very last edit), it inserted a typo just before, waited for the gutter status to indicate it, it removed a method, waited for the gutter status to return the updated (obsolete but migrated) diagnostics with the resolution error, and then the tests fixed the typo.
It expected that the priority of the last updated method (the fixed one) is set to 10 (which is the case), but that it would still remember the last two edited methods which should have priorities 9 and 8 respectively, and it looks like they are not remembered in this particular execution.

The code that pushes the gutter notifications is there:

https://github.com/dafny-lang/dafny/blob/479bdda4f676bf12d743c15e03db1c43dc05d9f6/Source/DafnyLanguageServer/Workspace/DocumentDatabase.cs#L206-L207

So gutter notifications are pushed before the enclosing async method `GetResolvedDocumentAsync` finishes.
This means that when the calling method tries to observe the migration:

https://github.com/dafny-lang/dafny/blob/479bdda4f676bf12d743c15e03db1c43dc05d9f6/Source/DafnyLanguageServer/Workspace/DocumentDatabase.cs#L159-L162

But my analysis stops here, as to me the field `LastTouchedMethodPositions` is always updated no matter what, provided that the last gutter statuses were sent. At least in the document that is being returned. Could it be possible that the next update request does not see these migrated lastTouchedMethodPositions, e.g. start with a version of the document before that, so that it migrates the wrong data?

**Comment by keyboardDrummer** [comment]
I don't understand how this could have happened either. Judging by the code and the actual result `1,10, 1, 1` in the end, it looks like the `document.LastTouchedMethodPositions` was empty before `ReportImplementationsBeforeVerification` was called for the last request, but I don't see how that's possible.
