### ISSUE TITLE
Unstable test VerificationStatusTest.ManualRunCancelCancelRunRun

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/dafny#2316]
https://github.com/dafny-lang/dafny/runs/7114049296?check_suite_focus=true

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed ManualRunCancelCancelRunRun [3 s]
  Error Message:
   Assert.IsFalse failed. 
  Stack Trace:
     at Microsoft.Dafny.LanguageServer.IntegrationTest.Synchronization.VerificationStatusTest.ManualRunCancelCancelRunRun() in D:\a\dafny\dafny\Source\DafnyLanguageServer.Test\Synchronization\VerificationStatusTest.cs:line 113
```

**Comment by MikaelMayer** [comment]
Another one that might be related?

ConcurrentInteractionTests.ChangeDocumentCancelsPreviousOpenAndChangeVerification 

https://github.com/dafny-lang/dafny/runs/7118811791?check_suite_focus=true

**Comment by MikaelMayer** [comment]
This test again failed my PR tests today:
https://github.com/dafny-lang/dafny/runs/7156066795?check_suite_focus=true

**Comment by MikaelMayer** [comment]
Hit that issue again today. Pfoo it has been a long time since it occurred ! 1 year and a half !

https://github.com/dafny-lang/dafny/actions/runs/12718612064/job/35457545105?pr=6033

```
fail: Microsoft.Dafny.Compilation[0]
      Caught error in statusUpdates observable.
      Microsoft.Boogie.ProverDiedException: Prover died with no further output, perhaps it ran out of memory or was killed.
         at Microsoft.Boogie.SMTLib.SMTLibProcess.PingPong()
         at Microsoft.Boogie.Checker.GoBackToIdle()
         at Microsoft.Boogie.VerificationTask.StartRun(CancellationToken cancellationToken)+MoveNext()
         at Microsoft.Boogie.VerificationTask.StartRun(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at System.Linq.AsyncEnumerable.ToObservableObservable`1.<>c__DisplayClass2_0.<<Subscribe>g__Core|0>d.MoveNext() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToObservable.cs:line 50
[xUnit.net 00:02:21.05]     Microsoft.Dafny.LanguageServer.IntegrationTest.Synchronization.VerificationStatusTest.ManualRunCancelCancelRunRun [FAIL]
[xUnit.net 00:02:21.05]       Assert.Equal() Failure
[xUnit.net 00:02:21.05]       Expected: Stale
[xUnit.net 00:02:21.05]       Actual:   Error
[xUnit.net 00:02:21.05]       Stack Trace:
[xUnit.net 00:02:21.05]         D:\a\dafny\dafny\dafny\Source\DafnyLanguageServer.Test\Synchronization\VerificationStatusTest.cs(450,0): at Microsoft.Dafny.LanguageServer.IntegrationTest.Synchronization.VerificationStatusTest.ManualRunCancelCancelRunRun()
[xUnit.net 00:02:21.05]         --- End of stack trace from previous location ---
[xUnit.net 00:02:21.05]       Output:
[xUnit.net 00:02:21.05]         Prover error: line 14 column 0: invalid command, '(' expected
```

**Comment by MikaelMayer** [comment]
Got it again while trying to release
https://github.com/dafny-lang/dafny/actions/runs/13125016516/job/36619473508?pr=6093
```
[xUnit.net 00:00:16.84]     Microsoft.Dafny.LanguageServer.IntegrationTest.Synchronization.VerificationStatusTest.ManualRunCancelCancelRunRun [FAIL]
[xUnit.net 00:00:16.84]       Assert.Equal() Failure
[xUnit.net 00:00:16.84]       Expected: Stale
[xUnit.net 00:00:16.[84](https://github.com/dafny-lang/dafny/actions/runs/13125016516/job/36619473508?pr=6093#step:11:85)]       Actual:   Error
[xUnit.net 00:00:16.84]       Stack Trace:
[xUnit.net 00:00:16.84]         D:\a\dafny\dafny\dafny\Source\DafnyLanguageServer.Test\Synchronization\VerificationStatusTest.cs(450,0): at Microsoft.Dafny.LanguageServer.IntegrationTest.Synchronization.VerificationStatusTest.ManualRunCancelCancelRunRun()
[xUnit.net 00:00:16.84]         --- End of stack trace from previous location ---
[xUnit.net 00:00:16.84]       Output:
[xUnit.net 00:00:16.84]         Prover error: ; $generated@@26 line: 101 position: 207

[xUnit.net 00:00:16.84]         Prover error: ; forall line: 105 position: 1

[xUnit.net 00:00:16.84]         Prover error: ; = line: 105 position: 40

[xUnit.net 00:00:16.84]         Prover error: ; = line: 105 position: 78

[xUnit.net 00:00:16.84]         Prover error: ; forall line: 107 position: 1

[xUnit.net 00:00:16.84]         Prover error: ; forall line: 109 position: 1

[xUnit.net 00:00:16.84]         Prover error: ; = line: 109 position: 39

[xUnit.net 00:00:16.84]         Prover error: ; forall line: 109 position: 163

[xUnit.net 00:00:16.84]         Prover error: ; forall line: 111 position: 1

[xUnit.net 00:00:16.84]         Prover error: ; forall line: 113 position: 1

[xUnit.net 00:00:16.84]         Prover error: line 101 column 0: invalid command, '(' expected

[xUnit.net 00:00:16.[85](https://github.com/dafny-lang/dafny/actions/runs/13125016516/job/36619473508?pr=6093#step:11:86)]         Prover error: line 101 column 208: invalid command, '(' expected
```
