### ISSUE TITLE
Translator generates ill-typed Boogie code, leading to assertion failure in `Microsoft.Boogie.IdentifierExpr.Typecheck`

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/dafny#2526]
I ran into this bug as part of my investigation into #2429 , which led to PRs #2519 (temporary workaround) and #2522 (more complete fix, but crashes due to this issue).

The following input:

```
function method F<T(0)>() : int
  requires var x: T :| true; [x] != []

method MObj() {
  print F<object?>();
}
```

… produces the following crash:

```
test.dfy(2,29): Error: internal error, shallow-type assignment was done incorrectly, x#1:ref != Box
Process terminated. Assertion failed.
   at Microsoft.Boogie.IdentifierExpr.Typecheck(TypecheckingContext tc) in C:\dafny\boogie\Source\Core\AbsyExpr.cs:line 1354
   at Microsoft.Boogie.NAryExpr.Typecheck(TypecheckingContext tc) in C:\dafny\boogie\Source\Core\AbsyExpr.cs:line 3300
   at Microsoft.Boogie.LetExpr.Typecheck(TypecheckingContext tc) in C:\dafny\boogie\Source\Core\AbsyQuant.cs:line 1290
   at Microsoft.Boogie.AssertCmd.Typecheck(TypecheckingContext tc) in C:\dafny\boogie\Source\Core\AbsyCmd.cs:line 3892
   at Microsoft.Boogie.Block.Typecheck(TypecheckingContext tc) in C:\dafny\boogie\Source\Core\AbsyCmd.cs:line 1371
   at Microsoft.Boogie.Implementation.Typecheck(TypecheckingContext tc) in C:\dafny\boogie\Source\Core\Absy.cs:line 4107
   at Microsoft.Boogie.Program.Typecheck(TypecheckingContext tc) in C:\dafny\boogie\Source\Core\Absy.cs:line 508
   at Microsoft.Boogie.Program.Typecheck(CoreOptions options, IErrorSink errorSink) in C:\dafny\boogie\Source\Core\Absy.cs:line 496
   at Microsoft.Boogie.Program.Typecheck(CoreOptions options) in C:\dafny\boogie\Source\Core\Absy.cs:line 490
   at Microsoft.Boogie.ExecutionEngine.ResolveAndTypecheck(Program program, String bplFileName, CivlTypeChecker& civlTypeChecker) in C:\dafny\boogie\Source\ExecutionEngine\ExecutionEngine.cs:line 396
   at Microsoft.Dafny.Main.BoogiePipelineWithRerun(TextWriter output, ExecutionEngine engine, Program program, String bplFileName, String programId) in C:\dafny\Source\Dafny\DafnyMain.cs:line 315
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dafny.Main.BoogiePipelineWithRerun(TextWriter output, ExecutionEngine engine, Program program, String bplFileName, String programId)
   at Microsoft.Dafny.Main.BoogieOnce(TextWriter output, ExecutionEngine engine, String baseFile, String moduleName, Program boogieProgram, String programId) in C:\dafny\Source\Dafny\DafnyMain.cs:line 279
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dafny.Main.BoogieOnce(TextWriter output, ExecutionEngine engine, String baseFile, String moduleName, Program boogieProgram, String programId)
   at Microsoft.Dafny.DafnyDriver.BoogieOnceWithTimer(TextWriter output, String baseName, String programId, String moduleName, Program program) in C:\dafny\Source\DafnyDriver\DafnyDriver.cs:line 419
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dafny.DafnyDriver.BoogieOnceWithTimer(TextWriter output, String baseName, String programId, String moduleName, Program program)
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass17_1.<Boogie>b__4() in C:\dafny\Source\DafnyDriver\DafnyDriver.cs:line 393
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntryUnsafe(Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

Here is my current understanding of the issue:

- When translating the call to function `F` in `MObj`, Dafny inline `F`'s `requires` clause into the body of `MObj`.  This uses `Substituter` class with a `typeMap` that maps `T` to `object?`.  From Dafny's perspective, the result is an assign-such-that expression that returns an `object?`

- Then (during translation), Dafny converts `var x: T :| true` into `var x: T :| $let#0_x(T)`, where `$let#0_x` is a skolemized version of the underlying existential.  This looks like this in Boogie:
      
       function $let#0_x(_module._default.M$T: Ty) : Box;

  This function always returns a box, meaning that it's output does not need to be boxed.  

- Also during translation, Dafny decides what to box and what not to box.  A reference like `x` needs to be boxed, so Dafny generates the following assertion in Boogie:

       assert {:subsumption 0} (var x#0 := $let#0_x(Tclass._System.object?()); 
         !Seq#Equal(Seq#Build(Seq#Empty(): Seq Box, $Box(x#0)), Seq#Empty(): Seq Box));

  Note that `x#0` is boxed.  This is because, even though it's not visible in the printed Boogie, the `var x#0` above actually has a type annotation: it's annotated as `: ref` (since in Dafny the RHS of the `var` returns a reference in the context of `MObj`).  

- When Boogie typechecks the term generated by Boogie, it updates the type of the LHS of the `var`: since the RHS is `$let#0_x`, which has type `Box`, the `LHS` is updated to have type `Box`.

- Finally, when Boogie typechecks `x#0` in the body of the var, it spots a type mismatch: the variable is used with type `ref`, but it is annotated to have type `Box` at it's binding (`var`) site.

There are two possible fixes:

0. Change the encoding of assign-such-that to make it polymorphic, so that the types line up in Boogie and Dafny
1. Be more careful in the translation from Dafny to Boogie, so as to avoid this type mismatch

I think option `0` is likely quite tricky to get right (it requires constraining the function in question to prevent it from hallucinating values in empty types)

Option 1 is probably easier.  We need to do essentially the same thing as this (which Dafny supports just fine):

```
function method MagicHat<T(0)>(): T

function method F<T(0)>() : int
  requires var x: T := MagicHat<T>(); [x] != []

method MObj() {
  print F<object?>();
}
```

The example above is a good workaround for this issue until we resolve the core problem, too.

**Comment by RustanLeino** [comment]
Thanks for such a detailed and helpful analysis! I agree that we should try for Option 0. I assume that means the Boogie let expression will be generated as

```
var x#0 := $Unbox($let#0_x(Tclass._System.object?())) : ref; 
```
