### ISSUE TITLE
AttributeError in generated Python code

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/dafny#2575]
Input:

```
module Base {
  trait T {}
}

module Derived refines Base {
  class C extends T {
    constructor() {}
  }
}

method Main() {
  var c := new Derived.C();
}
```

Output:

```console
$ Dafny /compileTarget:py /compile:4 Bug.dfy
Dafny program verifier finished with 1 verified, 0 errors
Wrote textual form of target program to Bug-py/Bug.py
Additional target code written to Bug-py/_dafny.py
Additional target code written to Bug-py/System_.py
Additional target code written to Bug-py/Base_Compile.py
Additional target code written to Bug-py/Derived_Compile.py
Additional target code written to Bug-py/module_.py
Running...

Traceback (most recent call last):
  File "Bug-py/Bug.py", line 6, in <module>
    import module_
  File "/dafny/SMT-LIB-transfromer/Src/Bench/Bug-py/module_.py", line 9, in <module>
    import Derived_Compile
  File "/dafny/SMT-LIB-transfromer/Src/Bench/Bug-py/Derived_Compile.py", line 13, in <module>
    class C(Derived_Compile.T):
AttributeError: partially initialized module 'Derived_Compile' has no attribute 'T' (most likely due to a circular import)
```

Generated code:

```
assert "Derived_Compile" == __name__
Derived_Compile = sys.modules[__name__]

class C(Derived_Compile.T):
    def  __init__(self):
        pass

    def __str__(self) -> str:
        return "Derived_Compile.C"
    def ctor__(self):
        pass

class T:
    pass
```

(Class `T` should come first)

**Comment by cpitclaudel** [comment]
Mostly untested patch: https://github.com/dafny-lang/dafny/commit/de3d4dd0b814829912a20272d8afea0176160065
