### ISSUE TITLE
textDocument/codeAction can cause an exception

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/dafny#2702]
In the following program, clicking on `false` creates an exception in the LSP server

```dafny

module Conc refines StillAsby {
  import A = B
}

abstract module StillAsby {
  import A : Absy
}

module B refines Absy {

}

abstract module Absy {
  method Foo() 
    ensures false {
    var x := 1;
  }
}
```

```
[Trace - 12:20:07 PM] Received response 'textDocument/codeAction - (150)' in 15ms. Request failed: Internal Error - System.Collections.Generic.KeyNotFoundException: The given key '15' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyCodeActionInput.Extract(Range range)
   at Microsoft.Dafny.LanguageServer.Language.VerificationDafnyCodeActionProvider.GetDafnyCodeActions(IDafnyCodeActionInput input, Diagnostic diagnostic, Range selection)
   at Microsoft.Dafny.LanguageServer.Plugins.DiagnosticDafnyCodeActionProvider.GetDafnyCodeActions(IDafnyCodeActionInput input, Range selection)
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyCodeActionHandler.<>c__DisplayClass5_0.<GetFixesWithIds>b__0(DafnyCodeActionProvider fixer)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyCodeActionHandler.Handle(CodeActionParams request, CancellationToken cancellationToken)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext() (-32603).
[Error - 12:20:07 PM] Request textDocument/codeAction failed.
  Message: Internal Error - System.Collections.Generic.KeyNotFoundException: The given key '15' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyCodeActionInput.Extract(Range range)
   at Microsoft.Dafny.LanguageServer.Language.VerificationDafnyCodeActionProvider.GetDafnyCodeActions(IDafnyCodeActionInput input, Diagnostic diagnostic, Range selection)
   at Microsoft.Dafny.LanguageServer.Plugins.DiagnosticDafnyCodeActionProvider.GetDafnyCodeActions(IDafnyCodeActionInput input, Range selection)
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyCodeActionHandler.<>c__DisplayClass5_0.<GetFixesWithIds>b__0(DafnyCodeActionProvider fixer)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToArray()
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyCodeActionHandler.Handle(CodeActionParams request, CancellationToken cancellationToken)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.<RouteRequest>g__InnerRoute|7_0(IServiceScopeFactory serviceScopeFactory, Request request, TDescriptor descriptor, Object params, CancellationToken token, ILogger logger)
   at OmniSharp.Extensions.JsonRpc.RequestRouterBase`1.RouteRequest(IRequestDescriptor`1 descriptors, Request request, CancellationToken token)
   at OmniSharp.Extensions.JsonRpc.DefaultRequestInvoker.<>c__DisplayClass10_0.<<RouteRequest>b__5>d.MoveNext()
  Code: -32603 
```

**Comment by MikaelMayer** [comment]
I cannot reproduce this as of today. Can you double check to see if this error is still there?

**Comment by keyboardDrummer** [comment]
Still reproduces on master for me.

**Comment by MikaelMayer** [comment]
Could you help me reproduce it?
Here is what I do, no errors.

![5871816c-47e6-440a-9ef8-77f84ae1409a](https://user-images.githubusercontent.com/3601079/190181075-e954adbf-61c5-4a35-bdcd-b9a50ecafe0a.gif)
