### ISSUE TITLE
Crash (`ArgumentOutOfRangeException`) in `Resolver.TypeSubstitutionMap`

### ISSUE THREAD

**Issue by cpitclaudel** [dafny-lang/dafny#2741]
Input:

```
datatype X1 = X1()
datatype Box<E> = Box(e: E)
type Alias = Box<X1>

method M(v: Alias)
{
  match v
    case Box(X1()) =>
    case Box(err) =>
}
```

Output:

```
boogie-crash.dfy(9,4): Warning: this branch is redundant
Unhandled exception. System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'))
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Microsoft.Dafny.Resolver.TypeSubstitutionMap(List`1 formals, List`1 actuals) in C:\dafny\Source\Dafny\Resolver.cs:line 14416
   at Microsoft.Dafny.Resolver.CheckLinearExtendedPattern(Type type, ExtendedPattern pat, ResolveOpts opts) in C:\dafny\Source\Dafny\Resolver.cs:line 12814
   at Microsoft.Dafny.Resolver.CheckLinearNestedMatchCase(Type type, NestedMatchCase mc, ResolveOpts opts) in C:\dafny\Source\Dafny\Resolver.cs:line 12835
   at Microsoft.Dafny.Resolver.CompileNestedMatchStmt(NestedMatchStmt s, ResolveOpts opts) in C:\dafny\Source\Dafny\Resolver.cs:line 12649
   at Microsoft.Dafny.Resolver.ResolveNestedMatchStmt(NestedMatchStmt s, ResolveOpts opts) in C:\dafny\Source\Dafny\Resolver.cs:line 11740
   at Microsoft.Dafny.Resolver.ResolveStatement(Statement stmt, ICodeContext codeContext) in C:\dafny\Source\Dafny\Resolver.cs:line 11651
   at Microsoft.Dafny.Resolver.ResolveStatementWithLabels(Statement stmt, ICodeContext codeContext) in C:\dafny\Source\Dafny\Resolver.cs:line 13704
   at Microsoft.Dafny.Resolver.ResolveBlockStatement(BlockStmt blockStmt, ICodeContext codeContext) in C:\dafny\Source\Dafny\Resolver.cs:line 13674
   at Microsoft.Dafny.Resolver.ResolveMethod(Method m) in C:\dafny\Source\Dafny\Resolver.cs:line 10400
   at Microsoft.Dafny.Resolver.ResolveClassMemberBodies(TopLevelDeclWithMembers cl) in C:\dafny\Source\Dafny\Resolver.cs:line 9613
   at Microsoft.Dafny.Resolver.ResolveTopLevelDecls_Core(List`1 declarations, Graph`1 datatypeDependencies, Graph`1 codatatypeDependencies, Boolean isAnExport) in C:\dafny\Source\Dafny\Resolver.cs:line 2816
   at Microsoft.Dafny.Resolver.ResolveModuleDefinition(ModuleDefinition m, ModuleSignature sig, Boolean isAnExport) in C:\dafny\Source\Dafny\Resolver.cs:line 1030
   at Microsoft.Dafny.Resolver.ResolveProgram(Program prog) in C:\dafny\Source\Dafny\Resolver.cs:line 502
   at Microsoft.Dafny.Main.Resolve(Program program, ErrorReporter reporter) in C:\dafny\Source\Dafny\DafnyMain.cs:line 163
   at Microsoft.Dafny.Main.ParseCheck(IList`1 files, String programName, ErrorReporter reporter, Program& program) in C:\dafny\Source\Dafny\DafnyMain.cs:line 114
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in C:\dafny\Source\DafnyDriver\DafnyDriver.cs:line 301
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in C:\dafny\Source\DafnyDriver\DafnyDriver.cs:line 116
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass9_0.<Main>b__0() in C:\dafny\Source\DafnyDriver\DafnyDriver.cs:line 92
   at System.Threading.Thread.StartCallback()
```

May be related to #2740?

**Comment by MikaelMayer** [comment]
Like #2743, was solved by #2954
