### ISSUE TITLE
Exception when resolving program that has a parameterised type in a redundant match case

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/dafny#2743]
```dafny
datatype List<T> =
| Cons(hd: T, tl: List<T>)
| Nil

type Prog = List<int>

function method interpProg(p: Prog) : int {
    match p {
        case x => 1
        case Nil => 2
        case Cons(instr, p) => 3
    }
}
```

Produces:

```
dafny test2.dfy 
test2.dfy(10,8): Warning: this branch is redundant 
test2.dfy(11,8): Warning: this branch is redundant 
Unhandled exception. System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'))
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Microsoft.Dafny.Resolver.TypeSubstitutionMap(List`1 formals, List`1 actuals) in /Users/runner/work/dafny/dafny/dafny/Source/Dafny/Resolver.cs:line 14479
   at Microsoft.Dafny.Resolver.CheckLinearExtendedPattern(Type type, ExtendedPattern pat, ResolutionContext resolutionContext) in /Users/runner/work/dafny/dafny/dafny/Source/Dafny/Resolver.cs:line 12883
   at Microsoft.Dafny.Resolver.CheckLinearNestedMatchCase(Type type, NestedMatchCase mc, ResolutionContext resolutionContext) in /Users/runner/work/dafny/dafny/dafny/Source/Dafny/Resolver.cs:line 12904
   at Microsoft.Dafny.Resolver.CompileNestedMatchExpr(NestedMatchExpr e, ResolutionContext resolutionContext) in /Users/runner/work/dafny/dafny/dafny/Source/Dafny/Resolver.cs:line 12664
   at Microsoft.Dafny.Resolver.ResolveNestedMatchExpr(NestedMatchExpr me, ResolutionContext resolutionContext) in /Users/runner/work/dafny/dafny/dafny/Source/Dafny/Resolver.cs:line 15885
   at Microsoft.Dafny.Resolver.ResolveExpression(Expression expr, ResolutionContext resolutionContext) in /Users/runner/work/dafny/dafny/dafny/Source/Dafny/Resolver.cs:line 15505
   at Microsoft.Dafny.Resolver.ResolveFunction(Function f) in /Users/runner/work/dafny/dafny/dafny/Source/Dafny/Resolver.cs:line 10245
   at Microsoft.Dafny.Resolver.ResolveClassMemberBodies(TopLevelDeclWithMembers cl) in /Users/runner/work/dafny/dafny/dafny/Source/Dafny/Resolver.cs:line 9642
   at Microsoft.Dafny.Resolver.ResolveTopLevelDecls_Core(List`1 declarations, Graph`1 datatypeDependencies, Graph`1 codatatypeDependencies, Boolean isAnExport) in /Users/runner/work/dafny/dafny/dafny/Source/Dafny/Resolver.cs:line 2817
   at Microsoft.Dafny.Resolver.ResolveModuleDefinition(ModuleDefinition m, ModuleSignature sig, Boolean isAnExport) in /Users/runner/work/dafny/dafny/dafny/Source/Dafny/Resolver.cs:line 1030
   at Microsoft.Dafny.Resolver.ResolveProgram(Program prog) in /Users/runner/work/dafny/dafny/dafny/Source/Dafny/Resolver.cs:line 502
   at Microsoft.Dafny.Main.Resolve(Program program, ErrorReporter reporter) in /Users/runner/work/dafny/dafny/dafny/Source/Dafny/DafnyMain.cs:line 163
   at Microsoft.Dafny.Main.ParseCheck(IList`1 files, String programName, ErrorReporter reporter, Program& program) in /Users/runner/work/dafny/dafny/dafny/Source/Dafny/DafnyMain.cs:line 114
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in /Users/runner/work/dafny/dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 305
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in /Users/runner/work/dafny/dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 116
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass9_0.<Main>b__0() in /Users/runner/work/dafny/dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 92
   at System.Threading.Thread.StartCallback()
```

**Comment by MikaelMayer** [comment]
This was fixed in #2954
