### ISSUE TITLE
Language Server not stable anymore

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#2890]
Yesterday I had been using the Dafny VSCode extension, and very often the following things happen
* Even just for parsing/resolving, it took way too long to recover a previous "verification" in the background.
* It randomly pops out persistent syntax errors on things that are clearly not in the text (e.g. unknown identifier but the said identifier is not a the position marked in the text) that go away if we restart VSCode.

The second item is critical, as it impairs productivity a lot . I suspect that a change was introduced in the LSP that lead to concurrent updates to the text buffer that don't work well.

## One repro

Write this in VSCode

```
function test(): int {
  1
}
```

Then press CTRL+A (to select all, and press ENTER. This effectively creates a blank file with two lines.
Then, press any key, such as `f`, while the caret is on the second line
The Dafny language server throws the following exception

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Microsoft.Dafny.LanguageServer.Workspace.TextBuffer.ToIndex(Position position) in dafny\Source\DafnyLanguageServer\Workspace\TextBuffer.cs:line 64
   at Microsoft.Dafny.LanguageServer.Workspace.TextBuffer.ApplyTextChange(TextDocumentContentChangeEvent change) in dafny\Source\DafnyLanguageServer\Workspace\TextBuffer.cs:line 73
   at Microsoft.Dafny.LanguageServer.Workspace.ChangeProcessors.TextChangeProcessor.ApplyTextChanges(TextBuffer buffer, Container`1 changes, CancellationToken cancellationToken) in dafny\Source\DafnyLanguageServer\Workspace\ChangeProcessors\TextChangeProcessor.cs:line 22
   at Microsoft.Dafny.LanguageServer.Workspace.ChangeProcessors.TextChangeProcessor.ApplyChange(DocumentTextBuffer originalTextDocument, DidChangeTextDocumentParams documentChange, CancellationToken cancellationToken) in dafny\Source\DafnyLanguageServer\Workspace\ChangeProcessors\TextChangeProcessor.cs:line 10
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentManager.UpdateDocument(DidChangeTextDocumentParams documentChange) in dafny\Source\DafnyLanguageServer\Workspace\DocumentManager.cs:line 94
   at Microsoft.Dafny.LanguageServer.Workspace.DocumentManagerDatabase.UpdateDocument(DidChangeTextDocumentParams documentChange) in dafny\Source\DafnyLanguageServer\Workspace\DocumentManagerDatabase.cs:line 48
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyTextDocumentHandler.Handle(DidChangeTextDocumentParams notification, CancellationToken cancellationToken) in dafny\Source\DafnyLanguageServer\Handlers\DafnyTextDocumentHandler.cs:line 85
```

**Comment by keyboardDrummer** [comment]
Possible change to blame: https://github.com/dafny-lang/dafny/pull/2799/files#diff-71506c12fe419a05f663f227a72feada1a5ca90efc83f45e8c6b95569cc5f4abR67
