### ISSUE TITLE
[Bug]: Verifier crash on declaration of subset type

### ISSUE THREAD

**Issue by rod-chapman** [dafny-lang/dafny#3019]
### Dafny version

3.9.1.41027

### Code to produce this issue

```dafny
module Crash
{
  type A = int
  type B = a : A | true
  type C  = a : B | true
}
```

### Command to run and results

```code
rodchap@f4d4889dcf6d src % dafny verify bug.dfy 
Unhandled exception. System.AggregateException: One or more errors occurred. (Unable to cast object of type 'Microsoft.Dafny.TypeSynonymDecl' to type 'Microsoft.Dafny.NewtypeDecl'.)
 ---> System.InvalidCastException: Unable to cast object of type 'Microsoft.Dafny.TypeSynonymDecl' to type 'Microsoft.Dafny.NewtypeDecl'.
   at Microsoft.Dafny.Translator.CheckResultToBeInType_Aux(IToken tok, Expression expr, Type toType, BoogieStmtListBuilder builder, ExpressionTranslator etran, String errorMsgPrefix)
   at Microsoft.Dafny.Translator.CheckResultToBeInType_Aux(IToken tok, Expression expr, Type toType, BoogieStmtListBuilder builder, ExpressionTranslator etran, String errorMsgPrefix)
   at Microsoft.Dafny.Translator.CheckResultToBeInType(IToken tok, Expression expr, Type toType, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran, String errorMsgPrefix)
   at Microsoft.Dafny.Translator.AddWellformednessCheck(RedirectingTypeDecl decl)
   at Microsoft.Dafny.Translator.AddTypeDecl(SubsetTypeDecl dd)
   at Microsoft.Dafny.Translator.AddTypeDecl(RevealableTypeDecl d)
   at Microsoft.Dafny.Translator.DoTranslation(Program p, ModuleDefinition forModule)
   at Microsoft.Dafny.Translator.Translate(Program p, ErrorReporter reporter, TranslatorFlags flags)+MoveNext()
   at Microsoft.Dafny.DafnyDriver.Translate(ExecutionEngineOptions options, Program dafnyProgram)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Dafny.DafnyDriver.ProcessFilesAsync(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args)
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass10_0.<Main>b__0()
   at System.Threading.Thread.StartCallback()
zsh: abort      dafny verify bug.dfy
```

### What happened?

Crash.

This is running on MacOS 12.6.1 on an M1 (ARM) MacBook Pro.

### What type of Operating System are you seeing the problem on?

Mac

**Comment by keyboardDrummer** [comment]
Resolved by: https://github.com/dafny-lang/dafny/pull/2954
