### ISSUE TITLE
[Bug]: Crash on subset type of pair

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#3091]
### Dafny version

3.9.1

### Code to produce this issue

```dafny
type SafePair = x: (int, int) | true
```

### Command to run and results

```code
Run through the VSCode IDE.

[{
	"resource": "Untitled-2",
	"owner": "dafny-vscode",
	"severity": 8,
	"message": "Dafny encountered an internal error. Please report it at <https://github.com/dafny-lang/dafny/issues>.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dafny.LanguageServer.Workspace.Notifications.TopLevelDeclMemberVerificationTree.<get_AssumptionsLines>g__CollectAssumeNotTrue|25_0(INode n) in dafny\\Source\\DafnyLanguageServer\\Workspace\\Notifications\\VerificationDiagnosticsParams.cs:line 484
   at Microsoft.Dafny.LanguageServer.Workspace.Notifications.TopLevelDeclMemberVerificationTree.get_AssumptionsLines() in dafny\\Source\\DafnyLanguageServer\\Workspace\\Notifications\\VerificationDiagnosticsParams.cs:line 494
   at Microsoft.Dafny.LanguageServer.Workspace.Notifications.TopLevelDeclMemberVerificationTree.get_StatusVerification() in dafny\\Source\\DafnyLanguageServer\\Workspace\\Notifications\\VerificationDiagnosticsParams.cs:line 464
   at Microsoft.Dafny.LanguageServer.Workspace.Notifications.VerificationTree.RenderInto(LineVerificationStatus[] perLineDiagnostics, Boolean contextHasErrors, Boolean contextIsPending, Range otherRange, Range contextRange) in dafny\\Source\\DafnyLanguageServer\\Workspace\\Notifications\\VerificationDiagnosticsParams.cs:line 321
   at Microsoft.Dafny.LanguageServer.Workspace.Notifications.TopLevelDeclMemberVerificationTree.RenderInto(LineVerificationStatus[] perLineDiagnostics, Boolean contextHasErrors, Boolean contextIsPending, Range otherRange, Range contextRange) in dafny\\Source\\DafnyLanguageServer\\Workspace\\Notifications\\VerificationDiagnosticsParams.cs:line 503
   at Microsoft.Dafny.LanguageServer.Workspace.Notifications.VerificationStatusGutter.RenderPerLineDiagnostics(DocumentUri uri, VerificationTree[] verificationTrees, Int32 numberOfLines, Boolean verificationStarted, Container`1 parseAndResolutionErrors) in dafny\\Source\\DafnyLanguageServer\\Workspace\\Notifications\\VerificationDiagnosticsParams.cs:line 61
   at Microsoft.Dafny.LanguageServer.Workspace.Notifications.VerificationStatusGutter.ComputeFrom(DocumentUri uri, Int32 version, VerificationTree[] verificationTrees, Container`1 resolutionErrors, Int32 linesCount, Boolean verificationStarted) in dafny\\Source\\DafnyLanguageServer\\Workspace\\Notifications\\VerificationDiagnosticsParams.cs:line 37
   at Microsoft.Dafny.LanguageServer.Workspace.NotificationPublisher.PublishGutterIcons(IdeState state, Boolean verificationStarted) in dafny\\Source\\DafnyLanguageServer\\Workspace\\NotificationPublisher.cs:line 100
   at Microsoft.Dafny.LanguageServer.Workspace.VerificationProgressReporter.ReportRealtimeDiagnostics(Boolean verificationStarted, DocumentAfterResolution document) in dafny\\Source\\DafnyLanguageServer\\Workspace\\VerificationProgressReporter.cs:line 220
   at Microsoft.Dafny.LanguageServer.Workspace.Compilation.PrepareVerificationTasksAsync(DocumentAfterResolution loaded, CancellationToken cancellationToken) in dafny\\Source\\DafnyLanguageServer\\Workspace\\Compilation.cs:line 166
   at Microsoft.Dafny.LanguageServer.Workspace.Compilation.TranslateAsync() in dafny\\Source\\DafnyLanguageServer\\Workspace\\Compilation.cs:line 112",
	
	"startLineNumber": 1,
	"startColumn": 1,
	"endLineNumber": 1,
	"endColumn": 2
}]
```

### What happened?

It should not crash

### What type of Operating System are you seeing the problem on?

Windows

**Comment by MikaelMayer** [comment]
this is not on master, it was on a branch.
