### ISSUE TITLE
An item with the same key has already been added (VSCode extension crash)

### ISSUE THREAD

**Issue by Timmmm** [dafny-lang/dafny#3219]
### Dafny version

3.10.0

### Code to produce this issue

```dafny
function decode_varint(input: seq<bv8>) : bv64
    requires |input| > 0
{
    var byte := input[0];
    var val := (byte & 0x7F) as bv64;
    var more := byte & 0x80 == 0 && |input| > 1;

    if more then val | (decode_varint(input[1..]) << 7) else val
}

function encode_varint(input: bv64) : seq<bv8>
{
    var byte := (input & 0x7F) as bv8;
    var shifted := input >> 7;
    if shifted == 0 then [byte | 0x80] else [byte] + encode_varint(shifted)
}

function encode_length(input: bv64) : nat
{
    if input < (1 << 7) then 1 else 1 + encode_length(input >> 7)
}

lemma EncodeLengthIsCorrect(input: bv64)
    ensures |encode_varint(input)| == encode_length(input)
{}

lemma EncodeLengthForValueRange(input: bv64, length: nat)
    requires 1 <= length <= 10
    requires (1 << ((length - 1) * 7)) <= input
    requires length < 10 ==> input < (1 << (length * 7))
    ensures encode_length(input) == length
{
    if length > 1 {
        EncodeLengthForValueRange(input >> 7, length - 1);
    }
}

lemma EncodeLengthMonotonic(input: bv64)
    ensures input < 0xFFFFFFFFFFFFFFFF ==> encode_length(input + 1) >= encode_length(input)
{}
```
```


### Command to run and resulting output

```code
Open in VSCode
```

### What happened?

The extension crashes the output is as follows:

```
Unhandled exception. System.ArgumentException: An item with the same key has already been added. Key: assert lt_bv64(input#0, 18446744073709551615bv64) ==> _module.__default.encode__length($LS($LS($LZ)), add_bv64(input#0, 1bv64)) >= _module.__default.encode__length($LS($LS($LZ)), input#0);

   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at VC.VCResult.ComputePerAssertOutcomes(Dictionary`2& perAssertOutcome, Dictionary`2& perAssertCounterExamples)
   at Microsoft.Dafny.LanguageServer.Workspace.VerificationProgressReporter.ReportAssertionBatchResult(AssertionBatchResult batchResult)
   at System.Reactive.AnonymousSafeObserver`1.OnNext(T value) in /_/Rx.NET/Source/src/System.Reactive/AnonymousSafeObserver.cs:line 43
   at System.Reactive.Linq.ObservableImpl.Where`1.Predicate._.OnNext(TSource value) in /_/Rx.NET/Source/src/System.Reactive/Linq/Observable/Where.cs:line 54
   at System.Reactive.ObserveOnObserverNew`1.DrainStep(ConcurrentQueue`1 q) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 559
   at System.Reactive.ObserveOnObserverNew`1.DrainShortRunning(IScheduler recursiveScheduler) in /_/Rx.NET/Source/src/System.Reactive/Internal/ScheduledObserver.cs:line 513
   at System.Reactive.Concurrency.EventLoopScheduler.Run() in /_/Rx.NET/Source/src/System.Reactive/Concurrency/EventLoopScheduler.cs:line 356
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Thread.StartCallback()
[Info  - 20:21:01] Connection to server got closed. Server will restart.
[Error - 20:21:01] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\Tim\.vscode\extensions\dafny-lang.ide-vscode-2.9.0\dist\extension.js:1:274562)
	at Object.dispose (c:\Users\Tim\.vscode\extensions\dafny-lang.ide-vscode-2.9.0\dist\extension.js:1:354645)
	at u.handleConnectionClosed (c:\Users\Tim\.vscode\extensions\dafny-lang.ide-vscode-2.9.0\dist\extension.js:1:354858)
	at u.handleConnectionClosed (c:\Users\Tim\.vscode\extensions\dafny-lang.ide-vscode-2.9.0\dist\extension.js:1:415204)
	at t (c:\Users\Tim\.vscode\extensions\dafny-lang.ide-vscode-2.9.0\dist\extension.js:1:352947)
	at a.invoke (c:\Users\Tim\.vscode\extensions\dafny-lang.ide-vscode-2.9.0\dist\extension.js:1:276175)
	at n.fire (c:\Users\Tim\.vscode\extensions\dafny-lang.ide-vscode-2.9.0\dist\extension.js:1:276936)
	at Z (c:\Users\Tim\.vscode\extensions\dafny-lang.ide-vscode-2.9.0\dist\extension.js:1:263820)
	at a.invoke (c:\Users\Tim\.vscode\extensions\dafny-lang.ide-vscode-2.9.0\dist\extension.js:1:276175)
	at n.fire (c:\Users\Tim\.vscode\extensions\dafny-lang.ide-vscode-2.9.0\dist\extension.js:1:276936)
	at g.fireClose (c:\Users\Tim\.vscode\extensions\dafny-lang.ide-vscode-2.9.0\dist\extension.js:1:288389)
	at Socket.<anonymous> (c:\Users\Tim\.vscode\extensions\dafny-lang.ide-vscode-2.9.0\dist\extension.js:1:289174)
	at Socket.emit (node:events:526:28)
	at Pipe.<anonymous> (node:net:687:12)
[Error - 20:21:01] Request textDocument/codeAction failed.
Error: Connection got disposed.
	at Object.dispose (c:\Users\Tim\.vscode\extensions\dafny-lang.ide-vscode-2.9.0\dist\extension.js:1:274562)
	at Object.dispose (c:\Users\Tim\.vscode\extensions\dafny-lang.ide-vscode-2.9.0\dist\extension.js:1:354645)
	at u.handleConnectionClosed (c:\Users\Tim\.vscode\extensions\dafny-lang.ide-vscode-2.9.0\dist\extension.js:1:354858)
	at u.handleConnectionClosed (c:\Users\Tim\.vscode\extensions\dafny-lang.ide-vscode-2.9.0\dist\extension.js:1:415204)
	at t (c:\Users\Tim\.vscode\extensions\dafny-lang.ide-vscode-2.9.0\dist\extension.js:1:352947)
	at a.invoke (c:\Users\Tim\.vscode\extensions\dafny-lang.ide-vscode-2.9.0\dist\extension.js:1:276175)
	at n.fire (c:\Users\Tim\.vscode\extensions\dafny-lang.ide-vscode-2.9.0\dist\extension.js:1:276936)
	at Z (c:\Users\Tim\.vscode\extensions\dafny-lang.ide-vscode-2.9.0\dist\extension.js:1:263820)
	at a.invoke (c:\Users\Tim\.vscode\extensions\dafny-lang.ide-vscode-2.9.0\dist\extension.js:1:276175)
	at n.fire (c:\Users\Tim\.vscode\extensions\dafny-lang.ide-vscode-2.9.0\dist\extension.js:1:276936)
	at g.fireClose (c:\Users\Tim\.vscode\extensions\dafny-lang.ide-vscode-2.9.0\dist\extension.js:1:288389)
	at Socket.<anonymous> (c:\Users\Tim\.vscode\extensions\dafny-lang.ide-vscode-2.9.0\dist\extension.js:1:289174)
	at Socket.emit (node:events:526:28)
	at Pipe.<anonymous> (node:net:687:12)
...
```

### What type of operating system are you experiencing the problem on?

Windows

**Comment by MikaelMayer** [comment]
This bug was fixed in Dafny 3.10. I just tested Dafny 3.10. and I confirm that the bug isn't there anymore, I can't reproduce it. Could you please double check your version of Dafny?
To use Dafny 3.10. in VSCode, you had to compile it yourself because as of today, it's not the latest nightly.

**Comment by Timmmm** [comment]
Ah my bad, apparently I didn't read the hint text in the bug report (does anyone?), so I just looked up the latest version on Github for when I installed the VSCode extension. Seems I actually have 3.9.1.something. Sorry about that!

**Comment by MikaelMayer** [comment]
Glad this issue will soon be a thing of the past !
