### ISSUE TITLE
crash during type checking

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#3262]
### Dafny version

3.10.0+dev

### Code to produce this issue

```dafny
module M {
    export reveals FooUtil
    class Blah {
        var x: nat;
        constructor C() {
            x := 0;
        }
        method update()
            modifies this
        {
            x := 1;
        }

    }
    class FooUtil {
        const foo: Blah;
        constructor C() {
            foo := new Blah.C();
            new;
            foo.update();
        }
    }
}

module P {
  import opened M

  method m() {
    var k := FooUtil.foo.x;
    FooUtil.foo.x := 5;
  }
}
```

### Command to run and resulting output

```code
dafny resolve test.dfy

Error message emitted but then a crash:

/Users/davidcok/projects/dafny/dafny/docs/HowToFAQ/tmp-error.dfy(29,21): Error: member 'foo' has not been imported in this scope and cannot be accessed here
/Users/davidcok/projects/dafny/dafny/docs/HowToFAQ/tmp-error.dfy(29,21): Error: accessing member 'foo' requires an instance expression
Process terminated. Assertion failed.
   at Microsoft.Dafny.Type.NormalizeExpand(Boolean keepConstraints) in /Users/davidcok/projects/dafny/dafny/Source/DafnyCore/AST/Types.cs:line 174
   at Microsoft.Dafny.Resolver.PartiallyResolveTypeForMemberSelection(IToken tok, Type t, String memberName, Int32 strength) in /Users/davidcok/projects/dafny/dafny/Source/DafnyCore/Resolver/NameResolutionAndTypeInference.cs:line 5115
   at Microsoft.Dafny.Resolver.ResolveMember(IToken tok, Type receiverType, String memberName, NonProxyType& tentativeReceiverType) in /Users/davidcok/projects/dafny/dafny/Source/DafnyCore/Resolver/NameResolutionAndTypeInference.cs:line 5046
   at Microsoft.Dafny.Resolver.ResolveDotSuffix(ExprDotName expr, Boolean isLastNameSegment, List`1 args, ResolutionContext resolutionContext, Boolean allowMethodCall) in /Users/davidcok/projects/dafny/dafny/Source/DafnyCore/Resolver/NameResolutionAndTypeInference.cs:line 6255
   at Microsoft.Dafny.Resolver.ResolveExpression(Expression expr, ResolutionContext resolutionContext) in /Users/davidcok/projects/dafny/dafny/Source/DafnyCore/Resolver/NameResolutionAndTypeInference.cs:line 333
   at Microsoft.Dafny.Resolver.ResolveUpdateStmt(UpdateStmt update, ResolutionContext resolutionContext, Int32 errorCountBeforeCheckingLhs) in /Users/davidcok/projects/dafny/dafny/Source/DafnyCore/Resolver/NameResolutionAndTypeInference.cs:line 3861
   at Microsoft.Dafny.Resolver.ResolveConcreteUpdateStmt(ConcreteUpdateStatement s, ResolutionContext resolutionContext) in /Users/davidcok/projects/dafny/dafny/Source/DafnyCore/Resolver/NameResolutionAndTypeInference.cs:line 3825
   at Microsoft.Dafny.Resolver.ResolveStatement(Statement stmt, ResolutionContext resolutionContext) in /Users/davidcok/projects/dafny/dafny/Source/DafnyCore/Resolver/NameResolutionAndTypeInference.cs:line 4145
   at Microsoft.Dafny.Resolver.ResolveStatementWithLabels(Statement stmt, ResolutionContext resolutionContext) in /Users/davidcok/projects/dafny/dafny/Source/DafnyCore/Resolver/NameResolutionAndTypeInference.cs:line 3651
   at Microsoft.Dafny.Resolver.ResolveBlockStatement(BlockStmt blockStmt, ResolutionContext resolutionContext) in /Users/davidcok/projects/dafny/dafny/Source/DafnyCore/Resolver/NameResolutionAndTypeInference.cs:line 3621
   at Microsoft.Dafny.Resolver.ResolveMethod(Method m) in /Users/davidcok/projects/dafny/dafny/Source/DafnyCore/Resolver/NameResolutionAndTypeInference.cs:line 3445
   at Microsoft.Dafny.Resolver.ResolveClassMemberBodies(TopLevelDeclWithMembers cl) in /Users/davidcok/projects/dafny/dafny/Source/DafnyCore/Resolver/NameResolutionAndTypeInference.cs:line 3125
   at Microsoft.Dafny.Resolver.ResolveTopLevelDecls_Core(List`1 declarations, Graph`1 datatypeDependencies, Graph`1 codatatypeDependencies, Boolean isAnExport) in /Users/davidcok/projects/dafny/dafny/Source/DafnyCore/Resolver/Resolver.cs:line 2842
   at Microsoft.Dafny.Resolver.ResolveModuleDefinition(ModuleDefinition m, ModuleSignature sig, Boolean isAnExport) in /Users/davidcok/projects/dafny/dafny/Source/DafnyCore/Resolver/Resolver.cs:line 1044
   at Microsoft.Dafny.Resolver.ResolveProgram(Program prog) in /Users/davidcok/projects/dafny/dafny/Source/DafnyCore/Resolver/Resolver.cs:line 510
   at Microsoft.Dafny.Main.Resolve(Program program, ErrorReporter reporter) in /Users/davidcok/projects/dafny/dafny/Source/DafnyCore/DafnyMain.cs:line 215
   at Microsoft.Dafny.Main.ParseCheck(IList`1 files, String programName, ErrorReporter reporter, Program& program) in /Users/davidcok/projects/dafny/dafny/Source/DafnyCore/DafnyMain.cs:line 166
   at Microsoft.Dafny.DafnyDriver.ProcessFilesAsync(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in /Users/davidcok/projects/dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 345
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dafny.DafnyDriver.ProcessFilesAsync(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId)
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in /Users/davidcok/projects/dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 123
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass10_0.<Main>b__0() in /Users/davidcok/projects/dafny/dafny/Source/DafnyDriver/DafnyDriver.cs:line 100
   at System.Threading.Thread.StartCallback()
/Users/davidcok/mybin/dafny: line 3: 41522 Abort trap: 6           /usr/local/bin/dotnet /Users/davidcok/projects/dafny/dafny/Binaries/Dafny.dll "$@"
```

### What happened?

Expect it not to crash

### What type of operating system are you experiencing the problem on?

Mac

**Comment by keyboardDrummer** [comment]
No longer occurs with todays nightly
