### ISSUE TITLE
Dafny crash on f.requires

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#3300]
```dafny
predicate IsCanOdd(f: int --> int) {
  forall x: int :: x % 2 == 0 ==> f.requires(x)
}
```

This crashes during translation with

```
Dafny encountered an internal error. Please report it at <https://github.com/dafny-lang/dafny/issues>.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dafny.Expression.set_Type(Type value) in dafny\Source\DafnyCore\AST\Expressions\Expressions.cs:line 54
   at Microsoft.Dafny.Substituter.Substitute(Expression expr) in dafny\Source\DafnyCore\Substituter.cs:line 57
   at Microsoft.Dafny.Substituter.Substitute(Expression expr) in dafny\Source\DafnyCore\Substituter.cs:line 156
   at Microsoft.Dafny.Translator.Substitute(Expression expr, Expression receiverReplacement, Dictionary`2 substMap, Dictionary`2 typeMap, Label oldLabel) in dafny\Source\DafnyCore\Verifier\Translator.cs:line 10621
   at Microsoft.Dafny.Translator.InRWClause_Aux(IToken tok, Expr o, Expr boxO, Expr f, List`1 rw, Boolean usedInUnchanged, ExpressionTranslator etran, Expression receiverReplacement, Dictionary`2 substMap) in dafny\Source\DafnyCore\Verifier\Translator.cs:line 4079
   at Microsoft.Dafny.Translator.InRWClause(IToken tok, Expr o, Expr f, List`1 rw, Boolean useInUnchanged, ExpressionTranslator etran, Expression receiverReplacement, Dictionary`2 substMap) in dafny\Source\DafnyCore\Verifier\Translator.cs:line 4051
   at Microsoft.Dafny.Translator.InRWClause(IToken tok, Expr o, Expr f, List`1 rw, ExpressionTranslator etran, Expression receiverReplacement, Dictionary`2 substMap) in dafny\Source\DafnyCore\Verifier\Translator.cs:line 4036
   at Microsoft.Dafny.Translator.CheckFrameSubset(IToken tok, List`1 calleeFrame, Expression receiverReplacement, Dictionary`2 substMap, ExpressionTranslator etran, Action`4 MakeAssert, ProofObligationDescription desc, QKeyValue kv) in dafny\Source\DafnyCore\Verifier\Translator.cs:line 3846
   at Microsoft.Dafny.Translator.CheckWellformedWithResult(Expression expr, WFOptions options, Expr result, Type resultType, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran) in dafny\Source\DafnyCore\Verifier\Translator.ExpressionWellformed.cs:line 672
   at Microsoft.Dafny.Translator.CheckWellformed(Expression expr, WFOptions options, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran) in dafny\Source\DafnyCore\Verifier\Translator.ExpressionWellformed.cs:line 238
   at Microsoft.Dafny.Translator.CheckWellformedWithResult(Expression expr, WFOptions options, Expr result, Type resultType, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran) in dafny\Source\DafnyCore\Verifier\Translator.ExpressionWellformed.cs:line 823
   at Microsoft.Dafny.Translator.<>c__DisplayClass434_7.<CheckWellformedWithResult>b__9(BoogieStmtListBuilder b) in dafny\Source\DafnyCore\Verifier\Translator.ExpressionWellformed.cs:line 1040
   at Microsoft.Dafny.Translator.BplIfIf(IToken tk, Boolean yes, Expr guard, BoogieStmtListBuilder builder, Action`1 k) in dafny\Source\DafnyCore\Verifier\Translator.BoogieFactory.cs:line 787
   at Microsoft.Dafny.Translator.<>c__DisplayClass434_6.<CheckWellformedWithResult>b__7(BoogieStmtListBuilder newBuilder) in dafny\Source\DafnyCore\Verifier\Translator.ExpressionWellformed.cs:line 1030
   at Microsoft.Dafny.Translator.BplIfIf(IToken tk, Boolean yes, Expr guard, BoogieStmtListBuilder builder, Action`1 k) in dafny\Source\DafnyCore\Verifier\Translator.BoogieFactory.cs:line 784
   at Microsoft.Dafny.Translator.<>c__DisplayClass434_5.<CheckWellformedWithResult>b__6(BoogieStmtListBuilder nextBuilder) in dafny\Source\DafnyCore\Verifier\Translator.ExpressionWellformed.cs:line 991
   at Microsoft.Dafny.Translator.BplIfIf(IToken tk, Boolean yes, Expr guard, BoogieStmtListBuilder builder, Action`1 k) in dafny\Source\DafnyCore\Verifier\Translator.BoogieFactory.cs:line 787
   at Microsoft.Dafny.Translator.CheckWellformedWithResult(Expression expr, WFOptions options, Expr result, Type resultType, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran) in dafny\Source\DafnyCore\Verifier\Translator.ExpressionWellformed.cs:line 979
   at Microsoft.Dafny.Translator.AddWellformednessCheck(Function f) in dafny\Source\DafnyCore\Verifier\Translator.cs:line 4358
   at Microsoft.Dafny.Translator.AddFunction_Top(Function f, Boolean includeAllMethods) in dafny\Source\DafnyCore\Verifier\Translator.ClassMembers.cs:line 140
   at Microsoft.Dafny.Translator.AddClassMembers(TopLevelDeclWithMembers c, Boolean includeAllMethods, Boolean includeInformationAboutType) in dafny\Source\DafnyCore\Verifier\Translator.ClassMembers.cs:line 69
   at Microsoft.Dafny.Translator.AddTypeDecl(RevealableTypeDecl d) in dafny\Source\DafnyCore\Verifier\Translator.cs:line 1212
   at Microsoft.Dafny.Translator.DoTranslation(Program p, ModuleDefinition forModule) in dafny\Source\DafnyCore\Verifier\Translator.cs:line 796
   at Microsoft.Dafny.Translator.Translate(Program p, ErrorReporter reporter, TranslatorFlags flags)+MoveNext() in dafny\Source\DafnyCore\Verifier\Translator.cs:line 868
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier.<>c__DisplayClass8_0.<GetVerificationTasksAsync>b__1() in dafny\Source\DafnyLanguageServer\Language\DafnyProgramVerifier.cs:line 51
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier.GetVerificationTasksAsync(DocumentAfterResolution document, CancellationToken cancellationToken) in dafny\Source\DafnyLanguageServer\Language\DafnyProgramVerifier.cs:line 51
   at Microsoft.Dafny.LanguageServer.Workspace.Compilation.PrepareVerificationTasksAsync(DocumentAfterResolution loaded, CancellationToken cancellationToken) in dafny\Source\DafnyLanguageServer\Workspace\Compilation.cs:line 131
   at Microsoft.Dafny.LanguageServer.Workspace.Compilation.TranslateAsync() in dafny\Source\DafnyLanguageServer\Workspace\Compilation.cs:line 108
```

**Comment by MikaelMayer** [comment]
This was actually a bug introduced in https://github.com/dafny-lang/dafny/pull/3282 which was subsequently fixed, so nothing to worry about. CI tests did catch this as well.
