### ISSUE TITLE
Crash using `dafny test`

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#3377]
### Dafny version

3.10.0+dev

### Code to produce this issue

```dafny
method {:extern} {:test} m(i: int, ghost j: int) 
  requires j == 1
```

### Command to run and resulting output

```code
dafny test text.dfy
```

### What happened?

Expected not to crash, buty got:

Dafny program verifier finished with 0 verified, 0 errors
Unhandled exception. System.AggregateException: One or more errors occurred. (Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'))
 ---> System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at Microsoft.Dafny.Compilers.SinglePassCompiler.TrCallStmt(CallStmt s, String receiverReplacement, ConcreteSyntaxTree wr) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 4279
   at Microsoft.Dafny.Compilers.SinglePassCompiler.TrStmt(Statement stmt, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 3072
   at Microsoft.Dafny.Compilers.SinglePassCompiler.TrStmtList(List`1 stmts, ConcreteSyntaxTree writer) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 4417
   at Microsoft.Dafny.Compilers.SinglePassCompiler.TrStmt(Statement stmt, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 3076
   at Microsoft.Dafny.Compilers.CsharpCompiler.EmitHaltRecoveryStmt(Statement body, String haltMessageVarName, Statement recoveryBody, ConcreteSyntaxTree wr) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/Compilers/Compiler-Csharp.cs:line 3440
   at Microsoft.Dafny.Compilers.SinglePassCompiler.TrStmt(Statement stmt, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 3387
   at Microsoft.Dafny.Compilers.SinglePassCompiler.TrStmtList(List`1 stmts, ConcreteSyntaxTree writer) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 4417
   at Microsoft.Dafny.Compilers.SinglePassCompiler.CompileMethod(Program program, Method m, IClassWriter cw, Boolean lookasideBody) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 2477
   at Microsoft.Dafny.Compilers.SinglePassCompiler.CompileClassMembers(Program program, TopLevelDeclWithMembers c, IClassWriter classWriter) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 2037
   at Microsoft.Dafny.Compilers.SinglePassCompiler.Compile(Program program, ConcreteSyntaxTree wrx) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/Compilers/SinglePassCompiler.cs:line 1423
   at Microsoft.Dafny.DafnyDriver.CompileDafnyProgram(Program dafnyProgram, String dafnyProgramName, ReadOnlyCollection`1 otherFileNames, Boolean invokeCompiler, TextWriter outputWriter) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyDriver/DafnyDriver.cs:line 687
   at Microsoft.Dafny.DafnyDriver.Compile(String fileName, ReadOnlyCollection`1 otherFileNames, Program dafnyProgram, PipelineOutcome oc, IDictionary`2 moduleStats, Boolean verified) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyDriver/DafnyDriver.cs:line 552
   at Microsoft.Dafny.DafnyDriver.ProcessFilesAsync(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyDriver/DafnyDriver.cs:line 364
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyDriver/DafnyDriver.cs:line 123
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass10_0.<Main>b__0() in /Users/davidcok/projects/dafny2/dafny/Source/DafnyDriver/DafnyDriver.cs:line 100
   at System.Threading.Thread.StartCallback()
/Users/davidcok/mybin/dafny: line 3: 62274 Abort trap: 6           /usr/local/bin/dotnet /Users/davidcok/projects/dafny2/dafny/Binaries/Dafny.dll "$@"

### What type of operating system are you experiencing the problem on?

Mac

**Comment by davidcok** [comment]
Will be fixed in PR #3898
