### ISSUE TITLE
EnsuresManyDocumentsCanBeVerifiedAtOnce is unstable

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/dafny#3403]
Example run: https://github.com/dafny-lang/dafny/actions/runs/4005795058/jobs/6877554794

```
Test run for /Users/runner/work/dafny/dafny/Source/DafnyLanguageServer.Test/bin/Debug/net6.0/DafnyLanguageServer.Test.dll (.NETCoreApp,Version=v6.0)
Microsoft (R) Test Execution Command Line Tool Version 17.4.0 (x64)
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed EnsuresManyDocumentsCanBeVerifiedAtOnce [2 s]
  Error Message:
   Assert.AreEqual failed. Expected:<
 .  |  |  |  I  |  | :predicate F(i: int) {
 .  |  |  |  I  |  | :  false // Should not be highlighted in gutter.
 .  |  |  |  I  |  | :}
    |  |  |  I  |  | :
 .  S [S][ ][I][S][ ]:method H()
 .  S [=][=][-][~][O]:  ensures F(1)
 .  S [=][=][-][~][=]:{//Next: { assert false;
 .  S [S][ ][I][S][ ]:}
>. Actual:<
 .  |  |  I  |  | :predicate F(i: int) {
 .  |  |  I  |  | :  false // Should not be highlighted in gutter.
 .  |  |  I  |  | :}
    |  |  I  |  | :
 .  S [ ][I][S][ ]:method H()
 .  S [ ][-][~][O]:  ensures F(1)
 .  S [ ][-][~][=]:{//Next: { assert false;
 .  S [ ][I][S][ ]:}
>. AssertEqualWithDiff() Failure
Diff (changing expected into actual):
 
- .  |  |  |  I  |  | :predicate F(i: int) {
- .  |  |  |  I  |  | :  false // Should not be highlighted in gutter.
- .  |  |  |  I  |  | :}
-    |  |  |  I  |  | :
- .  S [S][ ][I][S][ ]:method H()
- .  S [=][=][-][~][O]:  ensures F(1)
- .  S [=][=][-][~][=]:{//Next: { assert false;
- .  S [S][ ][I][S][ ]:}
+ .  |  |  I  |  | :predicate F(i: int) {
+ .  |  |  I  |  | :  false // Should not be highlighted in gutter.
+ .  |  |  I  |  | :}
+    |  |  I  |  | :
+ .  S [ ][I][S][ ]:method H()
+ .  S [ ][-][~][O]:  ensures F(1)
+ .  S [ ][-][~][=]:{//Next: { assert false;
+ .  S [ ][I][S][ ]:}
 

  Stack Trace:
     at Microsoft.Dafny.LanguageServer.IntegrationTest.Util.AssertWithDiff.Equal(String expected, String actual) in /Users/runner/work/dafny/dafny/Source/DafnyLanguageServer.Test/Util/AssertWithDiff.cs:line 28
   at Microsoft.Dafny.LanguageServer.IntegrationTest.Diagnostics.LinearVerificationGutterStatusTester.VerifyTrace(String codeAndTrace, String fileName, Boolean testTrace, TestNotificationReceiver`1 verificationStatusGutterReceiver) in /Users/runner/work/dafny/dafny/Source/DafnyLanguageServer.Test/GutterStatus/LinearVerificationGutterStatusTester.cs:line 253
   at Microsoft.Dafny.LanguageServer.IntegrationTest.Diagnostics.ConcurrentLinearVerificationGutterStatusTester.EnsuresManyDocumentsCanBeVerifiedAtOnce() in /Users/runner/work/dafny/dafny/Source/DafnyLanguageServer.Test/GutterStatus/ConcurrentLinearVerificationGutterStatusTester.cs:line 64

  Standard Output Messages:
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       MarkVerificationFinished called
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       MarkVerificationFinished called
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration string of type Microsoft.Dafny.TypeSynonymDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration nat of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown syntax node of type Microsoft.Dafny.FunctionCallExpr in (null)@(0,0)
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown syntax node of type Microsoft.Dafny.FunctionCallExpr in (null)@(0,0)
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration _#PartialFunc1 of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration _#TotalFunc1 of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown syntax node of type Microsoft.Dafny.FunctionCallExpr in (null)@(0,0)
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown syntax node of type Microsoft.Dafny.FunctionCallExpr in (null)@(0,0)
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration _#PartialFunc0 of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration _#TotalFunc0 of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration string of type Microsoft.Dafny.TypeSynonymDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration nat of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown syntax node of type Microsoft.Dafny.FunctionCallExpr in (null)@(0,0)
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown syntax node of type Microsoft.Dafny.FunctionCallExpr in (null)@(0,0)
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration _#PartialFunc1 of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration _#TotalFunc1 of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown syntax node of type Microsoft.Dafny.FunctionCallExpr in (null)@(0,0)
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown syntax node of type Microsoft.Dafny.FunctionCallExpr in (null)@(0,0)
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration _#PartialFunc0 of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration _#TotalFunc0 of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       documentUpdates.HasObservers: True, threadId: 892
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 892
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile1.dfy version 1.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Passed documentAfterParsing to documentUpdates.OnNext, resolving ResolvedDocument task for version 1.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       documentUpdates.HasObservers: True, threadId: 888
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 888
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile0.dfy version 1.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Passed documentAfterParsing to documentUpdates.OnNext, resolving ResolvedDocument task for version 1.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       MarkVerificationFinished called
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration string of type Microsoft.Dafny.TypeSynonymDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration nat of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown syntax node of type Microsoft.Dafny.FunctionCallExpr in (null)@(0,0)
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown syntax node of type Microsoft.Dafny.FunctionCallExpr in (null)@(0,0)
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration _#PartialFunc1 of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration _#TotalFunc1 of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown syntax node of type Microsoft.Dafny.FunctionCallExpr in (null)@(0,0)
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown syntax node of type Microsoft.Dafny.FunctionCallExpr in (null)@(0,0)
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration _#PartialFunc0 of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration _#TotalFunc0 of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       documentUpdates.HasObservers: True, threadId: 903
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 903
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile2.dfy version 1.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Passed documentAfterParsing to documentUpdates.OnNext, resolving ResolvedDocument task for version 1.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 13
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile1.dfy version 1.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 549
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile0.dfy version 1.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       MarkVerificationStarted called
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 903
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile2.dfy version 1.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       MarkVerificationStarted called
 info: Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier[0]
 info: Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier[0]
       Verifying H (correctness) ...
 dbug: Microsoft.Dafny.LanguageServer.Workspace.DocumentManager[0]
       Setting result for workCompletedForCurrentVersion
 info: Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier[0]
 info: Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier[0]
       Verifying H (correctness) ...
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Received status Running { } for Impl$$_module.__default.H
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 831
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile0.dfy version 1.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       MarkVerificationStarted called
 dbug: Microsoft.Dafny.LanguageServer.Workspace.DocumentManager[0]
       Setting result for workCompletedForCurrentVersion
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Received status Running { } for Impl$$_module.__default.H
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 901
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile2.dfy version 1.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.DocumentManager[0]
       Setting result for workCompletedForCurrentVersion
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Received status Queued { } for Impl$$_module.__default.H
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 966
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile1.dfy version 1.
 info: Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier[0]
 info: Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier[0]
       Verifying H (correctness) ...
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Received status Running { } for Impl$$_module.__default.H
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 966
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile1.dfy version 1.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Received status Completed { Result = Microsoft.Boogie.VerificationResult } for Impl$$_module.__default.H
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 831
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile0.dfy version 1.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Calling FinishedNotifications because there are no remaining verification jobs for version 1.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       MarkVerificationFinished called
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Received status Completed { Result = Microsoft.Boogie.VerificationResult } for Impl$$_module.__default.H
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 901
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile2.dfy version 1.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Calling FinishedNotifications because there are no remaining verification jobs for version 1.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       MarkVerificationFinished called
 dbug: Microsoft.Dafny.LanguageServer.Handlers.DafnyTextDocumentHandler[0]
       received change notification file:///testfile0.dfy
 dbug: Microsoft.Dafny.LanguageServer.Workspace.DocumentManager[0]
       Clearing result for workCompletedForCurrentVersion
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       MarkVerificationFinished called
 dbug: Microsoft.Dafny.LanguageServer.Workspace.DocumentManager[0]
       Finished processing document update for version 2
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Received status Completed { Result = Microsoft.Boogie.VerificationResult } for Impl$$_module.__default.H
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 966
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile1.dfy version 1.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Calling FinishedNotifications because there are no remaining verification jobs for version 1.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       MarkVerificationFinished called
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration string of type Microsoft.Dafny.TypeSynonymDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration nat of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown syntax node of type Microsoft.Dafny.FunctionCallExpr in (null)@(0,0)
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown syntax node of type Microsoft.Dafny.FunctionCallExpr in (null)@(0,0)
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration _#PartialFunc1 of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration _#TotalFunc1 of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown syntax node of type Microsoft.Dafny.FunctionCallExpr in (null)@(0,0)
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown syntax node of type Microsoft.Dafny.FunctionCallExpr in (null)@(0,0)
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration _#PartialFunc0 of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration _#TotalFunc0 of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       documentUpdates.HasObservers: True, threadId: 905
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 905
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile0.dfy version 2.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Passed documentAfterParsing to documentUpdates.OnNext, resolving ResolvedDocument task for version 2.
 dbug: Microsoft.Dafny.LanguageServer.Handlers.DafnyTextDocumentHandler[0]
       received change notification file:///testfile2.dfy
 dbug: Microsoft.Dafny.LanguageServer.Workspace.DocumentManager[0]
       Clearing result for workCompletedForCurrentVersion
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       MarkVerificationFinished called
 dbug: Microsoft.Dafny.LanguageServer.Workspace.DocumentManager[0]
       Finished processing document update for version 2
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration string of type Microsoft.Dafny.TypeSynonymDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration nat of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown syntax node of type Microsoft.Dafny.FunctionCallExpr in (null)@(0,0)
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown syntax node of type Microsoft.Dafny.FunctionCallExpr in (null)@(0,0)
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration _#PartialFunc1 of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration _#TotalFunc1 of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown syntax node of type Microsoft.Dafny.FunctionCallExpr in (null)@(0,0)
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown syntax node of type Microsoft.Dafny.FunctionCallExpr in (null)@(0,0)
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration _#PartialFunc0 of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration _#TotalFunc0 of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Handlers.DafnyTextDocumentHandler[0]
       received change notification file:///testfile1.dfy
 dbug: Microsoft.Dafny.LanguageServer.Workspace.DocumentManager[0]
       Clearing result for workCompletedForCurrentVersion
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       MarkVerificationFinished called
 dbug: Microsoft.Dafny.LanguageServer.Workspace.DocumentManager[0]
       Finished processing document update for version 2
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration string of type Microsoft.Dafny.TypeSynonymDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration nat of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown syntax node of type Microsoft.Dafny.FunctionCallExpr in (null)@(0,0)
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown syntax node of type Microsoft.Dafny.FunctionCallExpr in (null)@(0,0)
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration _#PartialFunc1 of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration _#TotalFunc1 of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown syntax node of type Microsoft.Dafny.FunctionCallExpr in (null)@(0,0)
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown syntax node of type Microsoft.Dafny.FunctionCallExpr in (null)@(0,0)
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration _#PartialFunc0 of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Language.Symbols.DafnyLangSymbolResolver[0]
       encountered unknown top level declaration _#TotalFunc0 of type Microsoft.Dafny.SubsetTypeDecl
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       documentUpdates.HasObservers: True, threadId: 888
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 888
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile2.dfy version 2.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Passed documentAfterParsing to documentUpdates.OnNext, resolving ResolvedDocument task for version 2.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       documentUpdates.HasObservers: True, threadId: 905
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 905
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile1.dfy version 2.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Passed documentAfterParsing to documentUpdates.OnNext, resolving ResolvedDocument task for version 2.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 900
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile0.dfy version 2.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       MarkVerificationStarted called
 info: Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier[0]
 info: Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier[0]
       Verifying H (correctness) ...
 dbug: Microsoft.Dafny.LanguageServer.Workspace.DocumentManager[0]
       Setting result for workCompletedForCurrentVersion
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Received status Running { } for Impl$$_module.__default.H
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 936
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile0.dfy version 2.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Received status Completed { Result = Microsoft.Boogie.VerificationResult } for Impl$$_module.__default.H
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 936
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile0.dfy version 2.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Calling FinishedNotifications because there are no remaining verification jobs for version 2.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       MarkVerificationFinished called
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 575
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile2.dfy version 2.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       MarkVerificationStarted called
 info: Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier[0]
 info: Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier[0]
       Verifying H (correctness) ...
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 549
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile1.dfy version 2.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       MarkVerificationStarted called
 dbug: Microsoft.Dafny.LanguageServer.Workspace.DocumentManager[0]
       Setting result for workCompletedForCurrentVersion
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Received status Running { } for Impl$$_module.__default.H
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 940
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile2.dfy version 2.
 info: Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier[0]
 info: Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier[0]
       Verifying H (correctness) ...
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Received status Running { } for Impl$$_module.__default.H
 dbug: Microsoft.Dafny.LanguageServer.Workspace.DocumentManager[0]
       Setting result for workCompletedForCurrentVersion
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 970
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile1.dfy version 2.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Received status Completed { Result = Microsoft.Boogie.VerificationResult } for Impl$$_module.__default.H
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 940
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile2.dfy version 2.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Calling FinishedNotifications because there are no remaining verification jobs for version 2.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       MarkVerificationFinished called
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Received status Completed { Result = Microsoft.Boogie.VerificationResult } for Impl$$_module.__default.H
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       IdeStateObserver.OnNext entered, threadId: 970
 dbug: Microsoft.Dafny.LanguageServer.Workspace.IdeStateObserver[0]
       Publishing notification for file:///testfile1.dfy version 2.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       Calling FinishedNotifications because there are no remaining verification jobs for version 2.
 dbug: Microsoft.Dafny.LanguageServer.Workspace.Compilation[0]
       MarkVerificationFinished called
```

**Comment by MikaelMayer** [comment]
I think it's more than an unstability, it's actually a bug that is likely related to this other issue.

https://github.com/dafny-lang/ide-vscode/issues/339#issue-1515953685

and it's highly disturbing. Happens every day. Errors are not reported. It's likely a regression as this did not happen a few months ago I believe.
