### ISSUE TITLE
Test DafnyTests/TestAttribute.dfy does not succeed in CI

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#3595]
### Dafny version

3.12 but with Dafny 4 defaults

### What happened?

The test DafnyTests/TestAttribute.dfy only succeeds with --unicode-char:false and only locally.
I suspect the failure to pass CI is due to the attempt to use the :test infrastructure. 
But it is not clear why this should fail.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by robin-aws** [comment]
Based on https://github.com/dafny-lang/dafny/actions/runs/4238783393/jobs/7366417426 it looks like `dotnet test` is not producing lines that match the OutputCheck patterns in stdout, only on stderr: https://github.com/dafny-lang/dafny/actions/runs/4238669328/jobs/7366359394. When I run this test locally on a Mac (using the xUnit runner in Rider) I see other lines on stdout that match:

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
  Failed _module.__default.FailingTest_CheckForFailureForXunit [2 ms]
  Error Message:
   Dafny test failed: VoidOutcome.VoidFailure(Whoopsie)
Expected: False
Actual:   True
  Stack Trace:
     at _module.__default.FailingTest_CheckForFailureForXunit() in /Users/salkeldr/Documents/GitHub/dafny/Source/IntegrationTests/bin/Debug/net6.0/TestFiles/LitTests/LitTest/DafnyTests/TestAttribute.cs:line 5469
  Failed _module.__default.FailingTestUsingMock [< 1 ms]
  Error Message:
   Dafny.HaltException : TestAttribute.dfy(138,2): expectation violation
  Stack Trace:
     at _module.__default.FailingTestUsingMock() in /Users/salkeldr/Documents/GitHub/dafny/Source/IntegrationTests/bin/Debug/net6.0/TestFiles/LitTests/LitTest/DafnyTests/TestAttribute.cs:line 5596
  Failed _module.__default.FailingTestUsingExpectWithMessage [< 1 ms]
  Error Message:
   Dafny.HaltException : TestAttribute.dfy(56,2): Down with DoubleThink!
  Stack Trace:
     at _module.__default.FailingTestUsingExpectWithMessage() in /Users/salkeldr/Documents/GitHub/dafny/Source/IntegrationTests/bin/Debug/net6.0/TestFiles/LitTests/LitTest/DafnyTests/TestAttribute.cs:line 5492
  Failed _module.__default.FailingTestUsingExpect [< 1 ms]
  Error Message:
   Dafny.HaltException : TestAttribute.dfy(52,2): expectation violation
  Stack Trace:
     at _module.__default.FailingTestUsingExpect() in /Users/salkeldr/Documents/GitHub/dafny/Source/IntegrationTests/bin/Debug/net6.0/TestFiles/LitTests/LitTest/DafnyTests/TestAttribute.cs:line 5485
  Failed _module.__default.FailingTestUsingNoLHSAssignOrHalt [< 1 ms]
  Error Message:
   Dafny.HaltException : TestAttribute.dfy(77,2): VoidOutcome.VoidFailure(requirement failed)
  Stack Trace:
     at _module.__default.FailingTestUsingNoLHSAssignOrHalt() in /Users/salkeldr/Documents/GitHub/dafny/Source/IntegrationTests/bin/Debug/net6.0/TestFiles/LitTests/LitTest/DafnyTests/TestAttribute.cs:line 5547
  Failed _module.__default.FailingTestUsingAssignOrHalt [< 1 ms]
  Error Message:
   Dafny.HaltException : TestAttribute.dfy(69,8): NatOutcome.NatFailure(Divide by zero)
  Stack Trace:
     at _module.__default.FailingTestUsingAssignOrHalt() in /Users/salkeldr/Documents/GitHub/dafny/Source/IntegrationTests/bin/Debug/net6.0/TestFiles/LitTests/LitTest/DafnyTests/TestAttribute.cs:line 5524

Failed!  - Failed:     6, Passed:    18, Skipped:     0, Total:    24, Duration: 35 ms - /Users/salkeldr/Documents/GitHub/dafny/Source/IntegrationTests/bin/Debug/net6.0/TestFiles/LitTests/LitTest/DafnyTests/bin/Debug/net6.0/DafnyTests.dll (net6.0)
```

I suspect ``--unicode-char:false` is a red herring as it passes for me without it (on a mac, it could be an unrelated issue with other platforms).

I'm tryin redirecting the stderr of `dotnet test` to `%t` in the test, as that was the original intention and the fact that the test passed when redirecting stdout is a bit of a fluke.
