### ISSUE TITLE
Unhelpful failure when a `{:test}` method returns a value

### ISSUE THREAD

**Issue by atomb** [dafny-lang/dafny#3839]
### Dafny version

2afa1f2970f8de9b0c6663e0738a60201fa28b9e

### Code to produce this issue

```dafny
method {:test} M(x: int) returns (r: int)
{
    expect x != x;
    return x;
}
```

### Command to run and resulting output

```code
$ ~/Repositories/dafny/Scripts/dafny test test.dfy
Unhandled exception. System.AggregateException: One or more errors occurred. (Unable to cast object of type 'Microsoft.Dafny.IntType' to type 'Microsoft.Dafny.UserDefinedType'.)
 ---> System.InvalidCastException: Unable to cast object of type 'Microsoft.Dafny.IntType' to type 'Microsoft.Dafny.UserDefinedType'.
   at Microsoft.Dafny.RunAllTestsMainMethod.PostResolve(Program program) in /Users/aarotomb/Repositories/dafny/Source/DafnyCore/Resolver/RunAllTestsMainMethod.cs:line 168
   at Microsoft.Dafny.Resolver.ResolveProgram(Program prog) in /Users/aarotomb/Repositories/dafny/Source/DafnyCore/Resolver/Resolver.cs:line 750
   at Microsoft.Dafny.Main.Resolve(Program program, ErrorReporter reporter) in /Users/aarotomb/Repositories/dafny/Source/DafnyCore/DafnyMain.cs:line 235
   at Microsoft.Dafny.Main.ParseCheck(IList`1 files, String programName, ErrorReporter reporter, Program& program) in /Users/aarotomb/Repositories/dafny/Source/DafnyCore/DafnyMain.cs:line 185
   at Microsoft.Dafny.DafnyDriver.ProcessFilesAsync(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in /Users/aarotomb/Repositories/dafny/Source/DafnyDriver/DafnyDriver.cs:line 397
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in /Users/aarotomb/Repositories/dafny/Source/DafnyDriver/DafnyDriver.cs:line 123
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass10_0.<Main>b__0() in /Users/aarotomb/Repositories/dafny/Source/DafnyDriver/DafnyDriver.cs:line 101
   at System.Threading.Thread.StartCallback()
/Users/aarotomb/Repositories/dafny/Scripts/dafny: line 35: 94219 Abort trap: 6           "$DOTNET" "$DAFNY" "$@"

$ ~/Repositories/dafny/Scripts/dafny /runAllTests:1 test.dfy
Unhandled exception. System.AggregateException: One or more errors occurred. (Unable to cast object of type 'Microsoft.Dafny.IntType' to type 'Microsoft.Dafny.UserDefinedType'.)
 ---> System.InvalidCastException: Unable to cast object of type 'Microsoft.Dafny.IntType' to type 'Microsoft.Dafny.UserDefinedType'.
   at Microsoft.Dafny.RunAllTestsMainMethod.PostResolve(Program program) in /Users/aarotomb/Repositories/dafny/Source/DafnyCore/Resolver/RunAllTestsMainMethod.cs:line 168
   at Microsoft.Dafny.Resolver.ResolveProgram(Program prog) in /Users/aarotomb/Repositories/dafny/Source/DafnyCore/Resolver/Resolver.cs:line 750
   at Microsoft.Dafny.Main.Resolve(Program program, ErrorReporter reporter) in /Users/aarotomb/Repositories/dafny/Source/DafnyCore/DafnyMain.cs:line 235
   at Microsoft.Dafny.Main.ParseCheck(IList`1 files, String programName, ErrorReporter reporter, Program& program) in /Users/aarotomb/Repositories/dafny/Source/DafnyCore/DafnyMain.cs:line 185
   at Microsoft.Dafny.DafnyDriver.ProcessFilesAsync(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in /Users/aarotomb/Repositories/dafny/Source/DafnyDriver/DafnyDriver.cs:line 397
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in /Users/aarotomb/Repositories/dafny/Source/DafnyDriver/DafnyDriver.cs:line 123
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass10_0.<Main>b__0() in /Users/aarotomb/Repositories/dafny/Source/DafnyDriver/DafnyDriver.cs:line 101
   at System.Threading.Thread.StartCallback()
/Users/aarotomb/Repositories/dafny/Scripts/dafny: line 35: 94239 Abort trap: 6           "$DOTNET" "$DAFNY" "$@"
```

### What happened?

Instead of a stack trace, it should either succeed in running the test or fail with a helpful error message saying that a `{:test}` method cannot return a value. We'll need to decide which we want to support.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by davidcok** [comment]
The problem is actually that M returns a value that does not have a failure-compatible type. But even that should be OK if there is an expect statement, as here.

There is an additional problem that M has input arguments, which also causes a later crash.
