### ISSUE TITLE
Java map<_, char> not keeping value type as char when accessign

### ISSUE THREAD

**Issue by Dilan-s** [dafny-lang/dafny#3887]
### Dafny version

4.0.0

### Code to produce this issue

```dafny
method Main() returns () {
  var v_map: map<bool, char> := map[true := 'c'];
  if true in v_map {
    var v_char: char := v_map[true];
    assert true;
  }
}
```

### Command to run and resulting output

```code
$ dafny /compile:4 /compileTarget:java test.dfy
Exception in thread "main" java.lang.ClassCastException: class java.lang.Character cannot be cast to class dafny.CodePoint (java.lang.Character is in module java.base of loader 'bootstrap'; dafny.CodePoint is in unnamed module of loader 'app')
        at _System.__default.Main(__default.java:16)
        at _System.__default.__Main(__default.java:20)
        at test.lambda$main$0(test.java:9)
        at dafny.Helpers.withHaltHandling(Helpers.java:327)
        at test.main(test.java:9)
```

### What happened?

Dafny verifies the program, but in Java throws an error (detailed above) which happens when accessing the value of a map (this occurs regardless of the type of the key) where the value is of type char. In all other languages (js, py, go, cs) this issue does not occur. This appears that the code generation for Java is casting the type of the value incorrectly.

### What type of operating system are you experiencing the problem on?

Linux

**Comment by Dilan-s** [comment]
Further investigation also shows an issue in the keys when the type is char:

### Code to produce this issue

```dafny
method Main() {
  var v_map: map<char, bool> := map['H' := false];
  var v_char: char := 'H';
  assert v_char in v_map;
  print v_char in v_map, "\n";
}
```


### Command to run and resulting output

```code
$ dafny /compile:4 /compileTarget:java test.dfy
false

$ dafny /compile:4 /compileTarget:js test.dfy
true

$ dafny /compile:4 /compileTarget:py test.dfy
true

$ dafny /compile:4 /compileTarget:go test.dfy
true
```


### What happened?

Dafny verifies the program, but in Java produces a different result to other target languages

### What type of operating system are you experiencing the problem on?

Linux

**Comment by Dilan-s** [comment]
Further further investigation shows this related issues with array<array<char>>:
```
method Main() returns ()
{
 var v_array_1: array<char> := new char[1] ['a'];
 var v_array_5: array<array<char>> := new array<char>[1] [v_array_1];
}
```
Compiling to java gives the error
```
Exception in thread "main" java.lang.ClassCastException: class [[C cannot be cast to class [[I ([[C and [[I are in module java.base of loader 'bootstrap')
```
