### ISSUE TITLE
match of match without outer default causes compilation crash

### ISSUE THREAD

**Issue by Dilan-s** [dafny-lang/dafny#3966]
### Dafny version

4.1.0

### Code to produce this issue

```dafny
method Main() returns ()
{
  var v_int: int := match (match 1 {
    case _ => true
  }) {
    case true => 14
  };
}
```

### Command to run and resulting output

```code
$ Dafny /compile:0 t.dfy
Process terminated. Assertion failed.
   at Microsoft.Dafny.Translator.CheckWellformedWithResult(Expression expr, WFOptions wfOptions, Expr result, Type resultType, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran) in /home/dilan/dafny-verifier/src/main/dafny_compiler/dafny/Source/DafnyCore/Verifier/Translator.ExpressionWellformed.cs:line 1189
...
   at System.Threading.Thread.StartCallback()
Aborted (core dumped)
```

### What happened?

Compiling the code segment causes dafny to crash and not produce any output file. This seems to be an issue before translating into a specific language. Adding in a default case into the outer match removes this error.

<details>
  <summary>Full error message</summary>
Process terminated. Assertion failed.
   at Microsoft.Dafny.Translator.CheckWellformedWithResult(Expression expr, WFOptions wfOptions, Expr result, Type resultType, List\`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran) in /dafny/Source/DafnyCore/Verifier/Translator.ExpressionWellformed.cs:line 1189
   at Microsoft.Dafny.Translator.CheckWellformedWithResult(Expression expr, WFOptions wfOptions, Expr result, Type resultType, List\`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran) in /dafny/Source/DafnyCore/Verifier/Translator.ExpressionWellformed.cs:line 1177
   at Microsoft.Dafny.Translator.CheckWellformedWithResult(Expression expr, WFOptions wfOptions, Expr result, Type resultType, List\`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran) in /dafny/Source/DafnyCore/Verifier/Translator.ExpressionWellformed.cs:line 1172
   at Microsoft.Dafny.Translator.CheckWellformed(Expression expr, WFOptions options, List\`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran) in /dafny/Source/DafnyCore/Verifier/Translator.ExpressionWellformed.cs:line 238
   at Microsoft.Dafny.Translator.CheckWellformedWithResult(Expression expr, WFOptions wfOptions, Expr result, Type resultType, List\`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran) in /dafny/Source/DafnyCore/Verifier/Translator.ExpressionWellformed.cs:line 867
   at Microsoft.Dafny.Translator.CheckWellformed(Expression expr, WFOptions options, List\`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran) in /dafny/Source/DafnyCore/Verifier/Translator.ExpressionWellformed.cs:line 238
   at Microsoft.Dafny.Translator.TrStmt_CheckWellformed(Expression expr, BoogieStmtListBuilder builder, List\`1 locals, ExpressionTranslator etran, Boolean subsumption, Boolean lValueContext) in /dafny/Source/DafnyCore/Verifier/Translator.cs:line 5337
   at Microsoft.Dafny.Translator.TrPredicateStmt(PredicateStmt stmt, BoogieStmtListBuilder builder, List\`1 locals, ExpressionTranslator etran) in /dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 534
   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List\`1 locals, ExpressionTranslator etran) in /dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 24
   at Microsoft.Dafny.Translator.CheckWellformedStmtExpr(StmtExpr stmtExpr, WFOptions options, Expr result, Type resultType, List\`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran) in /dafny/Source/DafnyCore/Verifier/Translator.ExpressionWellformed.cs:line 1265
   at Microsoft.Dafny.Translator.CheckWellformedWithResult(Expression expr, WFOptions wfOptions, Expr result, Type resultType, List\`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran) in /dafny/Source/DafnyCore/Verifier/Translator.ExpressionWellformed.cs:line 1125
   at Microsoft.Dafny.Translator.CheckWellformedWithResult(Expression expr, WFOptions wfOptions, Expr result, Type resultType, List\`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran) in /dafny/Source/DafnyCore/Verifier/Translator.ExpressionWellformed.cs:line 1177
   at Microsoft.Dafny.Translator.CheckWellformed(Expression expr, WFOptions options, List\`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran) in /dafny/Source/DafnyCore/Verifier/Translator.ExpressionWellformed.cs:line 238
   at Microsoft.Dafny.Translator.TrStmt_CheckWellformed(Expression expr, BoogieStmtListBuilder builder, List\`1 locals, ExpressionTranslator etran, Boolean subsumption, Boolean lValueContext) in /dafny/Source/DafnyCore/Verifier/Translator.cs:line 5337
   at Microsoft.Dafny.Translator.TrAssignmentRhs(IToken tok, IdentifierExpr bGivenLhs, IVariable lhsVar, Type lhsType, AssignmentRhs rhs, Type rhsTypeConstraint, BoogieStmtListBuilder builder, List\`1 locals, ExpressionTranslator etran) in /dafny/Source/DafnyCore/Verifier/Translator.cs:line 8857
   at Microsoft.Dafny.Translator.ProcessRhss(List\`1 lhsBuilder, List\`1 bLhss, List\`1 lhss, List\`1 rhss, BoogieStmtListBuilder builder, List\`1 locals, ExpressionTranslator etran) in /dafny/Source/DafnyCore/Verifier/Translator.cs:line 8464
   at Microsoft.Dafny.Translator.TrAssignment(Statement stmt, Expression lhs, AssignmentRhs rhs, BoogieStmtListBuilder builder, List\`1 locals, ExpressionTranslator etran) in /dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 1131
   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List\`1 locals, ExpressionTranslator etran) in /dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 258
   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List\`1 locals, ExpressionTranslator etran) in /dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 218
   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List\`1 locals, ExpressionTranslator etran) in /dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 486
   at Microsoft.Dafny.Translator.TrStmtList(List\`1 stmts, BoogieStmtListBuilder builder, List\`1 locals, ExpressionTranslator etran) in /dafny/Source/DafnyCore/Verifier/Translator.cs:line 7471
   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List\`1 locals, ExpressionTranslator etran) in /dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 307
   at Microsoft.Dafny.Translator.AddMethodImpl(Method m, Procedure proc, Boolean wellformednessProc) in /dafny/Source/DafnyCore/Verifier/Translator.ClassMembers.cs:line 651
   at Microsoft.Dafny.Translator.AddMethod_Top(Method m, Boolean isByMethod, Boolean includeAllMethods) in /dafny/Source/DafnyCore/Verifier/Translator.ClassMembers.cs:line 198
   at Microsoft.Dafny.Translator.AddClassMembers(TopLevelDeclWithMembers c, Boolean includeAllMethods, Boolean includeInformationAboutType) in /dafny/Source/DafnyCore/Verifier/Translator.ClassMembers.cs:line 71
   at Microsoft.Dafny.Translator.AddTypeDecl(RevealableTypeDecl d) in /dafny/Source/DafnyCore/Verifier/Translator.cs:line 1236
   at Microsoft.Dafny.Translator.DoTranslation(Program p, ModuleDefinition forModule) in /dafny/Source/DafnyCore/Verifier/Translator.cs:line 806
   at Microsoft.Dafny.Translator.Translate(Program p, ErrorReporter reporter, TranslatorFlags flags)+MoveNext() in /dafny/Source/DafnyCore/Verifier/Translator.cs:line 877
   at Microsoft.Dafny.DafnyDriver.Translate(ExecutionEngineOptions options, Program dafnyProgram)+MoveNext() in /dafny/Source/DafnyDriver/DafnyDriver.cs:line 576
   at System.Collections.Generic.List\`1..ctor(IEnumerable\`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable\`1 source)
   at Microsoft.Dafny.DafnyDriver.ProcessFilesAsync(IList\`1 dafnyFiles, ReadOnlyCollection\`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in /dafny/Source/DafnyDriver/DafnyDriver.cs:line 404
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dafny.DafnyDriver.ProcessFilesAsync(IList\`1 dafnyFiles, ReadOnlyCollection\`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId)
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in /dafny/Source/DafnyDriver/DafnyDriver.cs:line 123
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass10_0.<Main>b__0() in /dafny/Source/DafnyDriver/DafnyDriver.cs:line 101
   at System.Threading.Thread.StartCallback()
Aborted (core dumped)

</details>

### What type of operating system are you experiencing the problem on?

Linux

**Comment by MikaelMayer** [comment]
After doing a git bisect, this was fixed by #4030 thank you very much @keyboardDrummer  !
