### ISSUE TITLE
Dafny compilation crash: match expression inside forall statement

### ISSUE THREAD

**Issue by alex-usher** [dafny-lang/dafny#3969]
### Dafny version

4.1.0

### Code to produce this issue

```dafny
datatype D = A | B

method Main() {
    var a := new bool[3];
    forall i | 0 <= i < a.Length {
        a[i] := match A {
            case A => true
            case B => false
        };
    }
}
```

### Command to run and resulting output

```code
$ dafny main.dfy
Process terminated. Assertion failed.
   at Microsoft.Dafny.Translator.ExpressionTranslator.TrExpr(Expression expr) in dafny/Source/DafnyCore/Verifier/Translator.ExpressionTranslator.cs:line 1448
...
 at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in dafny/Source/DafnyDriver/DafnyDriver.cs:line 124
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass10_0.<Main>b__0() in dafny/Source/DafnyDriver/DafnyDriver.cs:line 102
   at System.Threading.Thread.StartCallback()
```

### What happened?

Compiling the code segment causes dafny to crash and not produce any output file. This seems to be an issue before translating into a specific language, and only happens with `forall` (converting to a for-loop verifies & compiles successfully).

See below for the full output error message.

<details>
  <summary>Full error message</summary>
<pre><code>Process terminated. Assertion failed.
   at Microsoft.Dafny.Translator.ExpressionTranslator.TrExpr(Expression expr) in dafny/Source/DafnyCore/Verifier/Translator.ExpressionTranslator.cs:line 1448
   at Microsoft.Dafny.Translator.ExpressionTranslator.TrExpr(Expression expr) in dafny/Source/DafnyCore/Verifier/Translator.ExpressionTranslator.cs:line 1438
   at Microsoft.Dafny.Translator.TrForall_NewValueAssumption(IToken tok, List`1 boundVars, List`1 bounds, Expression range, Expression lhs, Expression rhs, Attributes attributes, ExpressionTranslator etran, ExpressionTranslator prevEtran) in dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 1348
   at Microsoft.Dafny.Translator.TrForallAssign(ForallStmt s, AssignStmt s0, BoogieStmtListBuilder definedness, BoogieStmtListBuilder updater, List`1 locals, ExpressionTranslator etran) in dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 1314
   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 386
   at Microsoft.Dafny.Translator.TrStmtList(List`1 stmts, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in dafny/Source/DafnyCore/Verifier/Translator.cs:line 7485
   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in dafny/Source/DafnyCore/Verifier/Translator.TrStatement.cs:line 307
   at Microsoft.Dafny.Translator.AddMethodImpl(Method m, Procedure proc, Boolean wellformednessProc) in dafny/Source/DafnyCore/Verifier/Translator.ClassMembers.cs:line 653
   at Microsoft.Dafny.Translator.AddMethod_Top(Method m, Boolean isByMethod, Boolean includeAllMethods) in dafny/Source/DafnyCore/Verifier/Translator.ClassMembers.cs:line 200
   at Microsoft.Dafny.Translator.AddClassMembers(TopLevelDeclWithMembers c, Boolean includeAllMethods, Boolean includeInformationAboutType) in dafny/Source/DafnyCore/Verifier/Translator.ClassMembers.cs:line 72
   at Microsoft.Dafny.Translator.AddTypeDecl(RevealableTypeDecl d) in dafny/Source/DafnyCore/Verifier/Translator.cs:line 1236
   at Microsoft.Dafny.Translator.DoTranslation(Program p, ModuleDefinition forModule) in dafny/Source/DafnyCore/Verifier/Translator.cs:line 806
   at Microsoft.Dafny.Translator.Translate(Program p, ErrorReporter reporter, TranslatorFlags flags)+MoveNext() in dafny/Source/DafnyCore/Verifier/Translator.cs:line 877
   at Microsoft.Dafny.DafnyDriver.Translate(ExecutionEngineOptions options, Program dafnyProgram)+MoveNext() in dafny/Source/DafnyDriver/DafnyDriver.cs:line 583
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Dafny.DafnyDriver.ProcessFilesAsync(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in dafny/Source/DafnyDriver/DafnyDriver.cs:line 410
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Dafny.DafnyDriver.ProcessFilesAsync(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId)
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in dafny/Source/DafnyDriver/DafnyDriver.cs:line 124
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass10_0.<Main>b__0() in dafny/Source/DafnyDriver/DafnyDriver.cs:line 102
   at System.Threading.Thread.StartCallback()
</code></pre>

</details>

### What type of operating system are you experiencing the problem on?

Linux, Mac

**Comment by alex-usher** [comment]
fixed as of 4.3.0.0
