### ISSUE TITLE
C# Backend: Runtime Exceptions for Modulus of Large Multiset

### ISSUE THREAD

**Issue by alex-usher** [dafny-lang/dafny#3988]
### Dafny version

4.1.0

### Code to produce this issue

```dafny
method Main() {
    var x: multiset<int> := multiset{};
    (1) x := x[1 := 4294967296]; 
    (2) x := x[1 := 2147483648]; 
    (3) x := x[1 := 18446744073709551616];
    print |x|;
}

(different errors for selecting (1), (2), and (3) but all related)
```

### Command to run and resulting output

```code
(1) 
$ dafny main.dfy && dotnet main.dll
Unhandled exception. System.OverflowException: Value was either too large or too small for an Int32.
   at System.Numerics.BigInteger.op_Explicit(BigInteger value)
   at Dafny.MultiSet`1.get_Count()
   at _module.__default._Main(ISequence`1 __noArgsParameter)
   at __CallToMain.<>c__DisplayClass0_0.<Main>b__0()
   at Dafny.Helpers.WithHaltHandling(Action action)
   at __CallToMain.Main(String[] args)

(2)
$ dafny main.dfy && dotnet main.dll
Unhandled exception. System.OverflowException: Arithmetic operation resulted in an overflow.
   at System.Numerics.BigInteger.op_Explicit(BigInteger value)
   at Dafny.MultiSet`1.get_Count()
   at _module.__default._Main(ISequence`1 __noArgsParameter)
   at __CallToMain.<>c__DisplayClass0_0.<Main>b__0()
   at Dafny.Helpers.WithHaltHandling(Action action)
   at __CallToMain.Main(String[] args)

(3)
$ dafny main.dfy /compileTarget:py && python main-py/main.py
Traceback (most recent call last):
  File "main-py/main.py", line 12, in <module>
    module_.default__.Main(dafnyArgs)
  File "main-py/module_.py", line 24, in Main
    _dafny.print(_dafny.string_of(len(d_0_x_)))
                                  ^^^^^^^^^^^
OverflowError: cannot fit 'int' into an index-sized integer
```

### What happened?

Creating a multiset of size >= 2^32 (1) or 2^31 (2) for C#, or 2^64 (3) for Python, verifies successfully but results in the above runtime exceptions when trying to take its modulus. The other backends seem to handle this case using the BigInteger implementation - I'm wondering if the same needs to be done for the C# and Python backends? Although I appreciate this program is quite unrealistic so it may just be a limitation!

### What type of operating system are you experiencing the problem on?

Linux, Mac

**Comment by alex-usher** [comment]
confirmed fixed as of 4.3.0
