### ISSUE TITLE
Runtime implementation of multisets has a cardinality limit

### ISSUE THREAD

**Issue by fabiomadge** [dafny-lang/dafny#4012]
### Dafny version

4.1.0

### Code to produce this issue

```dafny
method Main() {
    var x: multiset<int> := multiset{};
    x := x[1 := 18446744073709551616];
    print |x|;
}
```

### What happened?

Crash

### What type of operating system are you experiencing the problem on?

Mac

**Comment by stefan-aws** [comment]
Can confirm the following error on my Mac with 4.1.0:

```
Error: Execution resulted in exception: Exception has been thrown by the target of an invocation.
System.OverflowException: Value was either too large or too small for an Int32.
   at System.Numerics.BigInteger.op_Explicit(BigInteger value)
   at Dafny.MultiSet`1.get_Count()
   at _module.__default._Main(ISequence`1 __noArgsParameter)
   at __CallToMain.<>c__DisplayClass0_0.<Main>b__0()
   at Dafny.Helpers.WithHaltHandling(Action action)
   at __CallToMain.Main(String[] args)
```

**Comment by fabiomadge** [comment]
What about the fix?
