### ISSUE TITLE
Empty standard input makes Dafny crash

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#4045]
### Dafny version

4.1.0 (specifically Nuget release, NOT GitHub release)

### Command to run and resulting output

```code
% dafny -stdin
<ctrl-D>
% dafny -stdin                      
<stdin>(1,0): Warning: File contains no code

Dafny program verifier finished with 0 verified, 0 errors
Unhandled exception. System.AggregateException: One or more errors occurred. (Value cannot be null. (Parameter 'path1'))
 ---> System.ArgumentNullException: Value cannot be null. (Parameter 'path1')
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.Dafny.DafnyDriver.GenerateTargetPaths(DafnyOptions options, String dafnyProgramName) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyDriver/DafnyDriver.cs:line 754
   at Microsoft.Dafny.DafnyDriver.CompileDafnyProgram(Program dafnyProgram, String dafnyProgramName, ReadOnlyCollection`1 otherFileNames, Boolean invokeCompiler, TextWriter outputWriter) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyDriver/DafnyDriver.cs:line 883
   at Microsoft.Dafny.DafnyDriver.Compile(String fileName, ReadOnlyCollection`1 otherFileNames, Program dafnyProgram, PipelineOutcome oc, IDictionary`2 moduleStats, Boolean verified) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyDriver/DafnyDriver.cs:line 717
   at Microsoft.Dafny.DafnyDriver.ProcessFilesAsync(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, DafnyOptions options, Boolean lookForSnapshots, String programId) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyDriver/DafnyDriver.cs:line 415
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyDriver/DafnyDriver.cs:line 119
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass10_0.<Main>b__0() in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyDriver/DafnyDriver.cs:line 102
   at System.Threading.Thread.StartCallback()
/Users/salkeldr/Documents/GitHub/dafny/Scripts/dafny: line 35: 11519 Abort trap: 6           "$DOTNET" "$DAFNY" "$@"
```

### What happened?

Introduced by https://github.com/dafny-lang/dafny/pull/3858, then re-introduced by https://github.com/dafny-lang/dafny/pull/3986

### What type of operating system are you experiencing the problem on?

Mac

**Comment by fabiomadge** [comment]
It only affects the unlisted version (`4.1.0.50509`), not `4.1.0` proper.
