### ISSUE TITLE
OverflowException in C# for large multiset value cardinality

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#4125]
### Dafny version

4.1.0

### Code to produce this issue

```dafny
method Main() {
    var x: multiset<int> := multiset{};
    x := x[1 := 18446744073709551616];
    print |x|, "\n";
}
```

### Command to run and resulting output

```code
% dafny run -t:cs src/Scratch.dfy

Dafny program verifier finished with 1 verified, 0 errors
Unhandled exception. System.OverflowException: Value was either too large or too small for an Int32.
   at System.Numerics.BigInteger.op_Explicit(BigInteger value)
   at Dafny.MultiSet`1.get_Count()
   at _module.__default._Main(ISequence`1 __noArgsParameter)
   at __CallToMain.<>c__DisplayClass0_0.<Main>b__0()
   at Dafny.Helpers.WithHaltHandling(Action action)
   at __CallToMain.Main(String[] args)
```

### What happened?

C# backend doesn't handle multiset value cardinality outside of the Int32 range.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by alex-usher** [comment]
(for visibility) this originates from: #3988
