### ISSUE TITLE
Crash, likely related to refinement

### ISSUE THREAD

**Issue by davidcok** [dafny-lang/dafny#4129]
### Dafny version

4.1.0+dev

### Code to produce this issue

```dafny
// RUN: %exits-with 0 %baredafny resolve --function-syntax:4 --use-basename-for-filename --unicode-char:false  "%s" > "%t"
 
module M {
  method m()
}
module P refines M {
  method m ... {
    while true { ...; }
  }
}
```

### Command to run and resulting output

```code
dafny resolve --function-syntax:4 --use-basename-for-filename --unicode-char:false


/Users/davidcok/projects/dafny2/dafny/Test/crash.dfy(8,20): Warning: the ... refinement feature in statements is deprecated
/Users/davidcok/projects/dafny2/dafny/Test/crash.dfy(8,17): Error: skeleton statements are allowed only in refining methods
Unhandled exception. System.AggregateException: One or more errors occurred. (One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.)))
 ---> System.AggregateException: One or more errors occurred. (One or more errors occurred. (Object reference not set to an instance of an object.))
 ---> System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dafny.SkeletonStatement.get_SubStatements()+MoveNext() in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/AST/Statements/SkeletonStatement.cs:line 61
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Dafny.ProgramTraverser.Traverse(Statement stmt, String field, Object parent) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/Generic/Util.cs:line 924
   at Microsoft.Dafny.ProgramTraverser.<>c__DisplayClass17_0.<Traverse>b__2(Statement subStmt) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/Generic/Util.cs:line 926
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Dafny.ProgramTraverser.Traverse(Statement stmt, String field, Object parent) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/Generic/Util.cs:line 924
   at Microsoft.Dafny.ProgramTraverser.<>c__DisplayClass17_0.<Traverse>b__2(Statement subStmt) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/Generic/Util.cs:line 926
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Dafny.ProgramTraverser.Traverse(Statement stmt, String field, Object parent) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/Generic/Util.cs:line 924
   at Microsoft.Dafny.ProgramTraverser.<>c__DisplayClass17_0.<Traverse>b__2(Statement subStmt) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/Generic/Util.cs:line 926
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Dafny.ProgramTraverser.Traverse(Statement stmt, String field, Object parent) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/Generic/Util.cs:line 924
   at Microsoft.Dafny.ProgramTraverser.Traverse(MemberDecl memberDeclaration, String field, Object parent) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/Generic/Util.cs:line 906
   at Microsoft.Dafny.ProgramTraverser.<>c__DisplayClass15_0.<Traverse>b__0(MemberDecl memberDecl) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/Generic/Util.cs:line 784
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Dafny.ProgramTraverser.Traverse(TopLevelDecl topd) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/Generic/Util.cs:line 784
   at Microsoft.Dafny.ProgramTraverser.Traverse(IEnumerable`1 topLevelDecls) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/Generic/Util.cs:line 725
   at Microsoft.Dafny.Resolver.ResolveTopLevelDecls_Core(List`1 declarations, Graph`1 datatypeDependencies, Graph`1 codatatypeDependencies, String moduleName, Boolean isAnExport) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/Resolver/Resolver.cs:line 2829
   at Microsoft.Dafny.Resolver.ResolveModuleDefinition(ModuleDefinition m, ModuleSignature sig, Boolean isAnExport) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/Resolver/Resolver.cs:line 834
   at Microsoft.Dafny.Resolver.ResolveProgram(Program prog) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/Resolver/Resolver.cs:line 534
   at Microsoft.Dafny.DafnyMain.<>c__DisplayClass5_0.<Resolve>b__0() in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/DafnyMain.cs:line 90
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.Dafny.DafnyMain.Resolve(Program program) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/DafnyMain.cs:line 90
   at Microsoft.Dafny.DafnyMain.ParseCheck(TextReader stdIn, IReadOnlyList`1 files, String programName, DafnyOptions options, Program& program) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyCore/DafnyMain.cs:line 54
   at Microsoft.Dafny.DafnyDriver.ProcessFilesAsync(IReadOnlyList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, DafnyOptions options, Boolean lookForSnapshots, String programId) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyDriver/DafnyDriver.cs:line 425
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Dafny.DafnyDriver.ThreadMain(TextWriter outputWriter, TextWriter errorWriter, TextReader inputReader, String[] args) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyDriver/DafnyDriver.cs:line 135
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass11_0.<MainWithWriters>b__0() in /Users/davidcok/projects/dafny2/dafny/Source/DafnyDriver/DafnyDriver.cs:line 112
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Dafny.DafnyDriver.MainWithWriters(TextWriter outputWriter, TextWriter errorWriter, TextReader inputReader, String[] args) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyDriver/DafnyDriver.cs:line 112
   at Microsoft.Dafny.DafnyDriver.Main(String[] args) in /Users/davidcok/projects/dafny2/dafny/Source/DafnyDriver/DafnyDriver.cs:line 99
   at Dafny.Dafny.Main(String[] args) in /Users/davidcok/projects/dafny2/dafny/Source/Dafny/Dafny.cs:line 7
/Users/davidcok/mybin/dafny: line 3: 68308 Abort trap: 6           /usr/local/bin/dotnet /Users/davidcok/projects/dafny2/dafny/Binaries/Dafny.dll "$@"
```

### What happened?

No crash

### What type of operating system are you experiencing the problem on?

Mac

**Comment by keyboardDrummer** [comment]
In Dafny 4.6 this no longer crashes on the CLI:
```
/Users/rwillems/Documents/Sync/Temp/HasProjectFile2/newTypeSystem.dfy(8,20): Warning: the ... refinement feature in statements is deprecated
  |
8 |     while true { ...; }
  |                     ^

/Users/rwillems/Documents/Sync/Temp/HasProjectFile2/newTypeSystem.dfy(8,17): Error: skeleton statements are allowed only in refining methods
  |
8 |     while true { ...; }
  |                  ^^^
```

but it does cause an exception in the IDE

**Comment by keyboardDrummer** [comment]
Triggers error in hover and documentSymbol:

```
[Trace - 3:06:03 PM] Received response 'textDocument/completion - (108)' in 23ms. Request failed: Internal Error - System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dafny.NodeExtensions.FindNodeChain(INode node, DafnyPosition position, LList`1 parent, Func`2 predicate)
   at Microsoft.Dafny.NodeExtensions.FindNodeChain(INode node, DafnyPosition position, LList`1 parent, Func`2 predicate)
   at Microsoft.Dafny.NodeExtensions.FindNodeChain(INode node, DafnyPosition position, LList`1 parent, Func`2 predicate)
   at Microsoft.Dafny.NodeExtensions.FindNodeChain(INode node, Uri uri, DafnyPosition position, LList`1 parent, Func`2 predicate)
   at Microsoft.Dafny.NodeExtensions.FindNodeChain(INode node, Uri uri, DafnyPosition position, LList`1 parent, Func`2 predicate)
   at Microsoft.Dafny.NodeExtensions.FindNodeChain(INode node, Uri uri, DafnyPosition position, LList`1 parent, Func`2 predicate)
   at Microsoft.Dafny.NodeExtensions.FindNodeChain(INode node, Uri uri, DafnyPosition position, LList`1 parent, Func`2 predicate)
   at Microsoft.Dafny.NodeExtensions.FindNode[T](INode root, Uri uri, DafnyPosition position)
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyCompletionHandler.CompletionProcessor.IsDotExpression()
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyCompletionHandler.CompletionProcessor.Process()
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyCompletionHandler.Handle(CompletionParams request, CancellationToken cancellationToken)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
```

**Comment by keyboardDrummer** [comment]
Fixed by https://github.com/dafny-lang/dafny/pull/5446
