### ISSUE TITLE
Parser exception "Value cannot be null" when stdin includes relative file

### ISSUE THREAD

**Issue by alex-chew** [dafny-lang/dafny#4135]
### Dafny version

b592aa7 and later

### Code to produce this issue

```dafny
// No code required
```

### Command to run and resulting output

```code
# Error occurs whether or not Lib.dfy exists

$ echo 'include "Lib.dfy"' | dafny -stdin
<stdin>(1,0): Error: [internal error] Parser exception: Value cannot be null. (Parameter 'path1')
    at System.IO.Path.Combine(String path1, String path2)
    at Microsoft.Dafny.Parser.Dafny()
    at Microsoft.Dafny.Parser.Parse()
    at Microsoft.Dafny.ProgramParser.ParseFile(DafnyOptions options, String s, Uri uri)
    at Microsoft.Dafny.ProgramParser.ParseFile(DafnyOptions options, TextReader reader, Uri uri) (ID: p_internal_exception)

This error indicates an internal crashing bug in Dafny. Please report it with as much of
the source code that causes the problem as possible.
<stdin>(1,0): Error: [internal error] Parser exception: Object reference not set to an instance of an object.
2 parse errors detected in
```

### What happened?

When passing Dafny source code to `dafny` via standard input, if the code contains an include to a relative file, then the above parser exception is thrown.

If the same code is instead passed to `dafny` in a file (and not standard input), then a warning is printed instead:

```
Lib.dfy(1,0): Warning: File contains no code (ID: p_file_has_no_code)

The indicated file has no code. This can be because the file is empty, because some parse error
left the top-level module with no well-formed declarations, or because a unclosed comment
has commented-out the whole file.
```

In the version 4.1.0 release, the include works as intended when passed over stdin - if the included file doesn't exist then an appropriate "Unable to open included file" error is printed, and if it does exist then Dafny includes it as normal.

### What type of operating system are you experiencing the problem on?

Linux, Mac

**Comment by alex-chew** [comment]
This is potentially related to https://github.com/dafny-lang/dafny/issues/4045.
