### ISSUE TITLE
Using --print and --rprint together crashes on programs with iterators

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#4159]
### Dafny version

4.1.0

### Code to produce this issue

```dafny
iterator C() yields (x: int) {}
```

### Command to run and resulting output

```code
% dafny verify src/Scratch.dfy --rprint:- --print:-
// Scratch.dfy

/*
module _System {
  /* CALL GRAPH for module _System:
   */
  type string(==,0) = seq<char>

  type {:axiom} nat(==,0) = x: int
    | 0 <= x

  trait {:compile false} object { }
  /*-- non-null type
  type {:axiom} object(==) = c: object? | c != null /*special witness*/
  */

  class {:compile false} array<arg> {
    var Length: int  // immutable
  }
  /*-- non-null type
  type {:axiom} array(==)<arg> = c: array?<arg> | c != null /*special witness*/
  */

  type {:compile false} /*_#Func1*/ -T0 ~> +R {
    ghost function requires(x0: T0): bool
      reads reads(x0)

    ghost function reads(x0: T0): set<object?>
      reads reads(x0)
  }

  type {:compile false} /*_#PartialFunc1*/ -T0 --> +R = f: T0 ~> R
    | forall x0: T0 :: f.reads(x0) == {}
    /*special witness*/

  type {:compile false} /*_#TotalFunc1*/ -T0 -> +R = f: T0 --> R
    | forall x0: T0 :: f.requires(x0)
    /*special witness*/

  type {:compile false} /*_#Func0*/ () ~> +R {
    ghost function requires(): bool
      reads reads()

    ghost function reads(): set<object?>
      reads reads()
  }

  type {:compile false} /*_#PartialFunc0*/ () --> +R = f: () ~> R
    | f.reads() == {}
    /*special witness*/

  type {:compile false} /*_#TotalFunc0*/ () -> +R = f: () --> R
    | f.requires()
    /*special witness*/
}
// bitvector types in use:
*/

/* CALL GRAPH for module _module:
 */
iterator C() yields (x: int)
{
}
Process terminated. Assertion failed.
   at Microsoft.Dafny.Printer.PrintTopLevelDecls(Program program, IEnumerable`1 decls, Int32 indent, List`1 prefixIds, String fileBeingPrinted) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyCore/AST/Grammar/Printer.cs:line 344
   at Microsoft.Dafny.Printer.PrintProgram(Program prog, Boolean afterResolver) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyCore/AST/Grammar/Printer.cs:line 214
   at Microsoft.Dafny.Printer.<>c__DisplayClass23_0.<PrintProgramLargeStack>b__0() in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyCore/AST/Grammar/Printer.cs:line 188
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(Task task)
   at Microsoft.Boogie.CustomStackSizePoolTaskScheduler.WorkLoop()
   at System.Threading.Thread.StartCallback()
/Users/salkeldr/Documents/GitHub/dafny/Scripts/dafny: line 35: 83412 Abort trap: 6           "$DOTNET" "$DAFNY" "$@"
```

### What happened?

~Appears that one printing pass modifies the AST in a way that breaks the second.~

The pretty printing logic accepts a `afterResolver` flag, but various parts of the logic check `options.DafnyPrintResolvedFile != null` instead, which is true if the resolved program WILL be printed instead. This could lead to lots of potential crashes trying to read resolved data that isn't there yet.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by atomb** [comment]
This seems to have been fixed already, immediately after it was discovered! Commit b87a851d9da3d5e9f7cab4b3b813a284b59cde70, which I expect was the one to uncover the issue, is susceptible to it. The following commit, 0d9bf00cffc6fa2bdb2f3468fdf7f68adc541d53, fixes it (though maybe by accident?).
