### ISSUE TITLE
Python runtime error possibly due to refinement and all-caps module names

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#4162]
### Dafny version

4.1.0

### Code to produce this issue

```dafny
// Queue.dfyi

abstract module Queue {
    type Item
    type Queue = seq<Item>

    method Init() returns (q: Queue)
        ensures |q| == 0

    method Push(item: Item, q: Queue) returns (q': Queue)
        ensures |q'| == |q| + 1

    method Pop(q: Queue) returns (item: Item, q': Queue)
        requires |q| > 0
        ensures item in q
        ensures |q'| == |q| - 1
}

abstract module MainSpec {
    import Q : Queue
}

// LIFO.dfy

include "Queue.dfyi"

module LIFO refines Queue {
    type Item = int

    method Init() returns (q: Queue) {
        q := [];
    }

    method Push(item: Item, q: Queue) returns (q': Queue) {
        return [item] + q;
    }

    method Pop(q: Queue) returns (item: Item, q': Queue)
        ensures item == q[0]
    {
        item := q[0];
        q' := q[1..];
    }
}

module MainImpl refines MainSpec {
    import Q = LIFO

    method Main()
    {
        var q := Q.Init();
        q := Q.Push(0, q);
        q := Q.Push(1, q);
        q := Q.Push(2, q);

        var n: int;
        n, q := Q.Pop(q);
        print n, "\n";
        n, q := Q.Pop(q);
        print n, "\n";
        n, q := Q.Pop(q);
        print n, "\n";
    }
}
```

### Command to run and resulting output

```code
% dafny run -t:py Test/exports/LIFO.dfy

Dafny program verifier finished with 5 verified, 0 errors
Traceback (most recent call last):
  File "/Users/salkeldr/Documents/GitHub/dafny/Test/exports/LIFO-py/LIFO.py", line 10, in <module>
    assert "LIFO" == __name__
           ^^^^^^^^^^^^^^^^^^
AssertionError
```

### What happened?

Not yet sure what's going on, possibly some name mangling in Python due to the all-caps module name. Changing it to `Lifo` in code (without changing the file name) leads to a different error: 

```
% dafny run -t:py Test/exports/LIFO.dfy

Dafny program verifier finished with 5 verified, 0 errors
Traceback (most recent call last):
  File "/Users/salkeldr/Documents/GitHub/dafny/Test/exports/LIFO-py/LIFO.py", line 6, in <module>
    import module_
  File "/Users/salkeldr/Documents/GitHub/dafny/Test/exports/LIFO-py/module_.py", line 9, in <module>
    import Lifo
ModuleNotFoundError: No module named 'Lifo'
```

### What type of operating system are you experiencing the problem on?

Mac

**Comment by fabiomadge** [comment]
The problem is that the filename (`LIFO.dfy`) is the same as one of the module names, so the entry point is overridden. Adding `/out:LIFOO` fixes the issue.
