### ISSUE TITLE
Refining a class that extends a trait throws an error

### ISSUE THREAD

**Issue by akravc** [dafny-lang/dafny#4248]
### Dafny version

4.1.0

### Code to produce this issue

```dafny
module Base {
  trait {:termination false} Expr {}
  class Num extends Expr {}
  class Plus extends Expr {}
}

module BaseX refines Base {
  class Num ... {}
}
```

### Command to run and resulting output

```code
The minimal example results in the following error in VSCode:

"Dafny encountered an internal error. Please report it at <https://github.com/dafny-lang/dafny/issues>.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Boogie.FunctionCall.get_ArgumentCount()
   at Microsoft.Boogie.NAryExpr.Typecheck(TypecheckingContext tc)
   at Microsoft.Boogie.Axiom.Typecheck(TypecheckingContext tc)
   at Microsoft.Boogie.Program.Typecheck(TypecheckingContext tc)
   at Microsoft.Boogie.ExecutionEngine.GetImplementationTasks(Program program)
   at Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier.<>c__DisplayClass5_0.<GetVerificationTasksAsync>b__0(Tuple`2 t)
   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.ToList()
   at Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier.GetVerificationTasksAsync(DocumentAfterResolution document, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.Compilation.PrepareVerificationTasksAsync(DocumentAfterResolution loaded, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.Compilation.TranslateAsync()"
```

### What happened?

The error shows up when the refined class extends a trait in the base module. If it doesn't extend a trait, the error does not show up. 

### What type of operating system are you experiencing the problem on?

Mac

**Comment by fabiomadge** [comment]
Thanks for the report! I believe that is regression has already been fix in master. You try the lastest [nightly build](https://github.com/dafny-lang/dafny/releases/tag/nightly) to ensure this fixes the issue in your code case as well?
