### ISSUE TITLE
Dafny crash when there is "e in S" set membership syntax and an export set

### ISSUE THREAD

**Issue by sjjs7** [dafny-lang/dafny#4334]
### Dafny version

4.1.0

### Code to produce this issue

```dafny
module Crash {
  export Body
    reveals *

  datatype Sort =
    | Int
    | Re
 
  datatype Func =
    | ReUnion
    | ReLoop {

      predicate wellFormedFunction(args: seq<Sort>) {
        match this {
          case ReUnion => (forall arg | arg in args :: arg.Re?)
          case _ => false
        }
      }

    }
}
```

### Command to run and resulting output

```code
input to CL (verifies fine in VSCode):
dafny /compile:1 crash.dfy

output: 
Process terminated. Assertion failed.
   at Microsoft.Dafny.Type.NormalizeExpand(Boolean keepConstraints) in /Users/jjsch/dafny/Source/DafnyCore/AST/Types/Types.cs:line 176
   at Microsoft.Dafny.Type.get_AsSubsetType() in /Users/jjsch/dafny/Source/DafnyCore/AST/Types/Types.cs:line 604
   at Microsoft.Dafny.SubsetConstraintGhostChecker.Traverse(Expression expr, String field, Object parent) in /Users/jjsch/dafny/Source/DafnyCore/Resolver/SubsetConstraintGhostChecker.cs:line 87
   at Microsoft.Dafny.ProgramTraverser.<>c__DisplayClass18_0.<Traverse>b__0(Expression subExpr) in /Users/jjsch/dafny/Source/DafnyCore/Generic/Util.cs:line 939
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Dafny.ProgramTraverser.Traverse(Expression expr, String field, Object parent) in /Users/jjsch/dafny/Source/DafnyCore/Generic/Util.cs:line 939
   at Microsoft.Dafny.SubsetConstraintGhostChecker.Traverse(Expression expr, String field, Object parent) in /Users/jjsch/dafny/Source/DafnyCore/Resolver/SubsetConstraintGhostChecker.cs:line 80
   at Microsoft.Dafny.ProgramTraverser.<>c__DisplayClass18_0.<Traverse>b__0(Expression subExpr) in /Users/jjsch/dafny/Source/DafnyCore/Generic/Util.cs:line 939
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Dafny.ProgramTraverser.Traverse(Expression expr, String field, Object parent) in /Users/jjsch/dafny/Source/DafnyCore/Generic/Util.cs:line 939
   at Microsoft.Dafny.SubsetConstraintGhostChecker.Traverse(Expression expr, String field, Object parent) in /Users/jjsch/dafny/Source/DafnyCore/Resolver/SubsetConstraintGhostChecker.cs:line 80
   at Microsoft.Dafny.ProgramTraverser.Traverse(MemberDecl memberDeclaration, String field, Object parent) in /Users/jjsch/dafny/Source/DafnyCore/Generic/Util.cs:line 874
   at Microsoft.Dafny.ProgramTraverser.<>c__DisplayClass15_0.<Traverse>b__0(MemberDecl memberDecl) in /Users/jjsch/dafny/Source/DafnyCore/Generic/Util.cs:line 783
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Dafny.ProgramTraverser.Traverse(TopLevelDecl topd) in /Users/jjsch/dafny/Source/DafnyCore/Generic/Util.cs:line 783
   at Microsoft.Dafny.ProgramTraverser.Traverse(IEnumerable`1 topLevelDecls) in /Users/jjsch/dafny/Source/DafnyCore/Generic/Util.cs:line 724
   at Microsoft.Dafny.ProgramTraverser.Traverse(ModuleDefinition moduleDefinition) in /Users/jjsch/dafny/Source/DafnyCore/Generic/Util.cs:line 715
   at Microsoft.Dafny.ProgramTraverser.Traverse(ModuleDecl moduleDecl) in /Users/jjsch/dafny/Source/DafnyCore/Generic/Util.cs:line 738
   at Microsoft.Dafny.ProgramTraverser.Traverse(TopLevelDecl topd) in /Users/jjsch/dafny/Source/DafnyCore/Generic/Util.cs:line 833
   at Microsoft.Dafny.ProgramTraverser.Traverse(IEnumerable`1 topLevelDecls) in /Users/jjsch/dafny/Source/DafnyCore/Generic/Util.cs:line 724
   at Microsoft.Dafny.Resolver.ResolveTopLevelDecls_Core(List`1 declarations, Graph`1 datatypeDependencies, Graph`1 codatatypeDependencies, String moduleName, Boolean isAnExport) in /Users/jjsch/dafny/Source/DafnyCore/Resolver/Resolver.cs:line 2827
   at Microsoft.Dafny.Resolver.ResolveModuleDefinition(ModuleDefinition m, ModuleSignature sig, Boolean isAnExport) in /Users/jjsch/dafny/Source/DafnyCore/Resolver/Resolver.cs:line 834
   at Microsoft.Dafny.Resolver.ResolveProgram(Program prog) in /Users/jjsch/dafny/Source/DafnyCore/Resolver/Resolver.cs:line 534
   at Microsoft.Dafny.DafnyMain.<>c__DisplayClass5_0.<Resolve>b__0() in /Users/jjsch/dafny/Source/DafnyCore/DafnyMain.cs:line 90
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(Task task)
   at Microsoft.Boogie.CustomStackSizePoolTaskScheduler.WorkLoop()
   at System.Threading.Thread.StartCallback()
/Users/jjsch/dafny/Scripts/dafny: line 35: 37386 Abort trap: 6           "$DOTNET" "$DAFNY" "$@"
```

### What happened?

If we use instead the alternate syntax: `(forall i | 0 <= i < |args| :: args[i].Re?)` in place of `(forall arg | arg in args :: arg.Re?)` the code verifies. If we remove the export statement the code verifies using either syntax.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by alex-chew** [comment]
Hi @sjjs7, thanks for the report. Unfortunately I'm not able to reproduce the crash you describe, using either the 4.1.0 release or the 4.2.0 release of Dafny on an Intel Mac. Can you please provide more details about your environment, in particular whether you're perhaps running a non-release version of Dafny, and which hardware / OS version you're running?

**Comment by sjjs7** [comment]
Running `dafny --version` I get back `4.1.0`, I am not sure how to check if this is a non-release version.
My OS is Mac Ventura Version 13.4.

**Comment by alex-chew** [comment]
> Running `dafny --version` I get back `4.1.0`, I am not sure how to check if this is a non-release version. My OS is Mac Ventura Version 13.4.

Thanks @sjjs7. Unfortunately I don't believe Dafny has a way of reporting whether it's a release version or not, but can you try using a fresh download of either Dafny 4.1.0 or Dafny 4.2.0, and see if you still experience the crash?

Also, can you clarify whether you're running on an Intel Mac or an M1 Mac?

**Comment by sjjs7** [comment]
I did a fresh download of Dafny (this time 4.2.0) and I still experience the same crash. 

I am running on an M1 Mac.

Also here is the full crash output, in case this is any help:

`Process terminated. Assertion failed.
   at Microsoft.Dafny.Type.NormalizeExpand(Boolean keepConstraints) in /Users/jjsch/new-dafny/dafny/Source/DafnyCore/AST/Types/Types.cs:line 177
   at Microsoft.Dafny.Type.get_AsSubsetType() in /Users/jjsch/new-dafny/dafny/Source/DafnyCore/AST/Types/Types.cs:line 611
   at Microsoft.Dafny.SubsetConstraintGhostChecker.Traverse(Expression expr, String field, Object parent) in /Users/jjsch/new-dafny/dafny/Source/DafnyCore/Resolver/SubsetConstraintGhostChecker.cs:line 87
   at Microsoft.Dafny.ProgramTraverser.<>c__DisplayClass18_0.<Traverse>b__0(Expression subExpr) in /Users/jjsch/new-dafny/dafny/Source/DafnyCore/Generic/Util.cs:line 968
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Dafny.ProgramTraverser.Traverse(Expression expr, String field, Object parent) in /Users/jjsch/new-dafny/dafny/Source/DafnyCore/Generic/Util.cs:line 968
   at Microsoft.Dafny.SubsetConstraintGhostChecker.Traverse(Expression expr, String field, Object parent) in /Users/jjsch/new-dafny/dafny/Source/DafnyCore/Resolver/SubsetConstraintGhostChecker.cs:line 80
   at Microsoft.Dafny.ProgramTraverser.<>c__DisplayClass18_0.<Traverse>b__0(Expression subExpr) in /Users/jjsch/new-dafny/dafny/Source/DafnyCore/Generic/Util.cs:line 968
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Dafny.ProgramTraverser.Traverse(Expression expr, String field, Object parent) in /Users/jjsch/new-dafny/dafny/Source/DafnyCore/Generic/Util.cs:line 968
   at Microsoft.Dafny.SubsetConstraintGhostChecker.Traverse(Expression expr, String field, Object parent) in /Users/jjsch/new-dafny/dafny/Source/DafnyCore/Resolver/SubsetConstraintGhostChecker.cs:line 80
   at Microsoft.Dafny.ProgramTraverser.Traverse(MemberDecl memberDeclaration, String field, Object parent) in /Users/jjsch/new-dafny/dafny/Source/DafnyCore/Generic/Util.cs:line 903
   at Microsoft.Dafny.ProgramTraverser.<>c__DisplayClass15_0.<Traverse>b__0(MemberDecl memberDecl) in /Users/jjsch/new-dafny/dafny/Source/DafnyCore/Generic/Util.cs:line 812
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source, Func`2 predicate)
   at Microsoft.Dafny.ProgramTraverser.Traverse(TopLevelDecl topd) in /Users/jjsch/new-dafny/dafny/Source/DafnyCore/Generic/Util.cs:line 812
   at Microsoft.Dafny.ProgramTraverser.Traverse(IEnumerable`1 topLevelDecls) in /Users/jjsch/new-dafny/dafny/Source/DafnyCore/Generic/Util.cs:line 753
   at Microsoft.Dafny.ProgramTraverser.Traverse(ModuleDefinition moduleDefinition) in /Users/jjsch/new-dafny/dafny/Source/DafnyCore/Generic/Util.cs:line 744
   at Microsoft.Dafny.ProgramTraverser.Traverse(ModuleDecl moduleDecl) in /Users/jjsch/new-dafny/dafny/Source/DafnyCore/Generic/Util.cs:line 767
   at Microsoft.Dafny.ProgramTraverser.Traverse(TopLevelDecl topd) in /Users/jjsch/new-dafny/dafny/Source/DafnyCore/Generic/Util.cs:line 862
   at Microsoft.Dafny.ProgramTraverser.Traverse(IEnumerable`1 topLevelDecls) in /Users/jjsch/new-dafny/dafny/Source/DafnyCore/Generic/Util.cs:line 753
   at Microsoft.Dafny.ModuleResolver.ResolveTopLevelDecls_Core(List`1 declarations, Graph`1 datatypeDependencies, Graph`1 codatatypeDependencies, String moduleName, Boolean isAnExport) in /Users/jjsch/new-dafny/dafny/Source/DafnyCore/Resolver/ModuleResolver.cs:line 1591
   at Microsoft.Dafny.ModuleDefinition.Resolve(ModuleSignature sig, ModuleResolver resolver, Boolean isAnExport) in /Users/jjsch/new-dafny/dafny/Source/DafnyCore/AST/Modules/ModuleDefinition.cs:line 428
   at Microsoft.Dafny.LiteralModuleDecl.Resolve(ModuleResolver resolver, CompilationData compilation) in /Users/jjsch/new-dafny/dafny/Source/DafnyCore/AST/Modules/LiteralModuleDecl.cs:line 122
   at Microsoft.Dafny.ModuleResolver.ResolveModuleDeclaration(CompilationData compilation, ModuleDecl decl) in /Users/jjsch/new-dafny/dafny/Source/DafnyCore/Resolver/ModuleResolver.cs:line 184
   at Microsoft.Dafny.ProgramResolver.ResolveModuleDeclaration(CompilationData compilation, ModuleDecl decl) in /Users/jjsch/new-dafny/dafny/Source/DafnyCore/Resolver/ProgramResolver.cs:line 161
   at Microsoft.Dafny.ProgramResolver.Resolve(CancellationToken cancellationToken) in /Users/jjsch/new-dafny/dafny/Source/DafnyCore/Resolver/ProgramResolver.cs:line 66
   at Microsoft.Dafny.DafnyMain.<>c__DisplayClass5_0.<Resolve>b__0() in /Users/jjsch/new-dafny/dafny/Source/DafnyCore/DafnyMain.cs:line 89
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(Task task)
   at Microsoft.Boogie.CustomStackSizePoolTaskScheduler.WorkLoop()
   at System.Threading.Thread.StartCallback()
Scripts/dafny: line 35: 57895 Abort trap: 6           "$DOTNET" "$DAFNY" "$@"`

**Comment by keyboardDrummer** [comment]
I can reproduce this with Dafny 4.6.0 using `dafny build <program>`

**Comment by olivier-aws** [comment]
Cannot reproduce with Dafny 4.9.1 using `dafny build <program>`

**Comment by olivier-aws** [comment]
Closing the issue as it cannot be reproduced with latest Dafny release (4.9.1).
