### ISSUE TITLE
Internal error maybe to do with sequences

### ISSUE THREAD

**Issue by CarlKCarlK** [dafny-lang/dafny#4446]
### Dafny version

4.2.0

### Code to produce this issue

```dafny
// A range is a INCLUSIVE (closed) interval [a, b] of integers.
predicate IsRange(pair: (int, int))
{
  pair.0 <= pair.1
}

method subseq(s: seq<(int, int)>, i: int, j: int) returns (r: seq<(int, int)>)
  requires 0 <= i <= j <= |s|
  ensures |r| == j - i
  ensures forall k | 0 <= k < |r| :: r[k] == s[i + k]
{
  r := [s[k] | k in [i..j-1]];
}

method Main()
{
  var s: seq<(int, int)> := [(1, 2), (3, 4), (5, 6), (7, 8), (9, 10)];
  assume forall pair | pair in s :: IsRange(pair);
  assert forall pair | pair in s :: IsRange(pair);
  var s1 := s[1..3];
}
```

### Command to run and resulting output

```code
In VS code, I get this error:

Dafny encountered an internal error. Please report it at <https://github.com/dafny-lang/dafny/issues>.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dafny.LanguageServer.Workspace.NotificationPublisher.PublishGutterIcons(IdeState state, Boolean verificationStarted)
   at Microsoft.Dafny.LanguageServer.Workspace.CompilationManager.ResolveAsync()
```

### What happened?

From the terminal, I get more useful error message: 

   |
13 |   r := [s[k] | k in [i..j-1]];
   |                       ^

o:\Projects\Science\dafny\demo1\property_example.dfy(13,22): Error: rbracket expected

### What type of operating system are you experiencing the problem on?

Windows

**Comment by keyboardDrummer** [comment]
I get the same error on the CLI and in the IDE:
<img width="930" alt="image" src="https://github.com/dafny-lang/dafny/assets/3121201/86a25323-135b-4306-bcd9-962c07dfb459">

**Comment by keyboardDrummer** [comment]
For resolving the hard to reproduce NPE in the gutter icon code:
```
System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dafny.LanguageServer.Workspace.NotificationPublisher.PublishGutterIcons(IdeState state, Boolean verificationStarted)
   at Microsoft.Dafny.LanguageServer.Workspace.CompilationManager.ResolveAsync()
```

I suggest we switch to client side computed gutter icons.
