### ISSUE TITLE
Cannot execute a plugin for the language server

### ISSUE THREAD

**Issue by xbreu** [dafny-lang/dafny#4759]
### What change in documentation do you suggest?

I want to make a plugin for Dafny and, because of that, I started by following the reference page for plugins (which can be checked [here](https://github.com/dafny-lang/dafny/blob/master/docs/DafnyRef/Plugins.md)), but could not make it work. I also tried working with an example plugin ([PluginsTest.cs](https://github.com/dafny-lang/dafny/blob/master/Source/DafnyLanguageServer.Test/_plugins/PluginsTest.cs)).
The problem is that, whenever I add the .dll file to VS Code, the extension stops working, and the logs don't show anything wrong to my knowledge:
```
$ code --verbose | grep -i 'dafny'
[4866:1108/120523.264898:INFO:CONSOLE(645)] "%cTRACE color: #888 pickRunningLocation for dafny-lang.ide-vscode, extension kinds: [workspace], isInstalledLocally: true, isInstalledRemotely: false, preference: None => LocalProcess", source: vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js (645)
        at D (/home/xbreu/.vscode/extensions/dafny-lang.ide-vscode-3.2.1/dist/extension.js:1:429900)
        at b (/home/xbreu/.vscode/extensions/dafny-lang.ide-vscode-3.2.1/dist/extension.js:1:428885)
        at d (/home/xbreu/.vscode/extensions/dafny-lang.ide-vscode-3.2.1/dist/extension.js:1:473826)
        at t.map (/home/xbreu/.vscode/extensions/dafny-lang.ide-vscode-3.2.1/dist/extension.js:1:473912)
        at Object.asDiagnostics (/home/xbreu/.vscode/extensions/dafny-lang.ide-vscode-3.2.1/dist/extension.js:1:441449)
        at u.workDiagnosticQueue (/home/xbreu/.vscode/extensions/dafny-lang.ide-vscode-3.2.1/dist/extension.js:1:320827)
        at Immediate.<anonymous> (/home/xbreu/.vscode/extensions/dafny-lang.ide-vscode-3.2.1/dist/extension.js:1:320493)
[4866:1108/120530.966302:INFO:CONSOLE(2015)] "[dafny-lang.ide-vscode]Illegal argument: line must be non-negative", source: vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js (2015)
        at D (/home/xbreu/.vscode/extensions/dafny-lang.ide-vscode-3.2.1/dist/extension.js:1:429900)
        at b (/home/xbreu/.vscode/extensions/dafny-lang.ide-vscode-3.2.1/dist/extension.js:1:428885)
        at d (/home/xbreu/.vscode/extensions/dafny-lang.ide-vscode-3.2.1/dist/extension.js:1:473826)
        at t.map (/home/xbreu/.vscode/extensions/dafny-lang.ide-vscode-3.2.1/dist/extension.js:1:473912)
        at Object.asDiagnostics (/home/xbreu/.vscode/extensions/dafny-lang.ide-vscode-3.2.1/dist/extension.js:1:441449)
        at u.workDiagnosticQueue (/home/xbreu/.vscode/extensions/dafny-lang.ide-vscode-3.2.1/dist/extension.js:1:320827)
        at Immediate.<anonymous> (/home/xbreu/.vscode/extensions/dafny-lang.ide-vscode-3.2.1/dist/extension.js:1:320493)
[4866:1108/120546.460716:INFO:CONSOLE(645)] "%cTRACE color: #888 CommandService#executeCommand dafny.openStatusBarMenu", source: vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js (645)
[4866:1108/120549.335438:INFO:CONSOLE(645)] "%cTRACE color: #888 CommandService#executeCommand dafny.openStatusBarMenu", source: vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js (645)
```
I am not sure which is the cause for this. And I could not run the language server alone as well to see if I get more debug information. I'm not sure if I should detail the situation here or open a new issue, so I'll put it here for now.
Following what I understood from the language server [README](https://github.com/dafny-lang/dafny/blob/master/Source/DafnyLanguageServer/README.md), I compiled z3 and created a folder `dafny/Binaries/z3/bin` with the binary. But when I get errors when running the .dll:
```
$ dotnet DafnyLanguageServer.dll
A fatal error was encountered. The library 'libhostpolicy.so' required to execute the application was not found in '/home/xbreu/Documents/dafny/Binaries/'.
Failed to run as a self-contained app.
  - The application was run as a self-contained app because '/home/xbreu/Documents/dafny/Binaries/DafnyLanguageServer.runtimeconfig.json' was not found.
  - If this should be a framework-dependent app, add the '/home/xbreu/Documents/dafny/Binaries/DafnyLanguageServer.runtimeconfig.json' file and specify the appropriate framework.
```
I'm not well-versed with C#, but all that I read online suggested changes in the .csproj files.
I can provide more info that may be relevant, all the command were executed in a Linux machine (with EndeavourOS).

**Comment by MikaelMayer** [comment]
Instead of putting your plugin in the list of plugins, could you please try to add the following argument to the Dafny language server?

    --plugin:<Path to your plugin.dll>

The dafny language server used to have a separate way to inject plugins, but now that it's started with Dafny the above might work. If that is the case, then we can just drop the dropdown list of plugins.

**Comment by xbreu** [comment]
Yes, that worked, thank you very much. In the case of VSCode I added an item to the "Language Server Launch Args" and it worked. Seems like the problem is the "Dafny Plugins" option like you mentioned.
