### ISSUE TITLE
Datatype update expressions not resolved correctly by refreshed type system

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#4847]
```dafny
datatype D = D(n: nat)

method Foo(d: D)
{
  while (true) 
    invariant d.(n := d.n + 1).n >= 0
  {

  }
}
```

```bash
% dafny verify src/Scratch.dfy --type-system-refresh
Process terminated. Assertion failed.
   at Microsoft.Dafny.BoogieGenerator.CheckWellformedWithResult(Expression expr, WFOptions wfOptions, Expr result, Type resultType, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran, String resultDescription) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyCore/Verifier/BoogieGenerator.ExpressionWellformed.cs:line 1226
   at Microsoft.Dafny.BoogieGenerator.CheckWellformedWithResult(Expression expr, WFOptions wfOptions, Expr result, Type resultType, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran, String resultDescription) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyCore/Verifier/BoogieGenerator.ExpressionWellformed.cs:line 1209
   at Microsoft.Dafny.BoogieGenerator.CheckWellformed(Expression expr, WFOptions options, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyCore/Verifier/BoogieGenerator.ExpressionWellformed.cs:line 253
   at Microsoft.Dafny.BoogieGenerator.CheckWellformedWithResult(Expression expr, WFOptions wfOptions, Expr result, Type resultType, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran, String resultDescription) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyCore/Verifier/BoogieGenerator.ExpressionWellformed.cs:line 903
   at Microsoft.Dafny.BoogieGenerator.CheckWellformed(Expression expr, WFOptions options, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyCore/Verifier/BoogieGenerator.ExpressionWellformed.cs:line 253
   at Microsoft.Dafny.BoogieGenerator.TrStmt_CheckWellformed(Expression expr, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran, Boolean subsumption, Boolean lValueContext) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyCore/Verifier/BoogieGenerator.TrStatement.cs:line 2818
   at Microsoft.Dafny.BoogieGenerator.TrLoop(LoopStmt s, Expression Guard, BodyTranslator bodyTr, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran, Expr freeInvariant, Boolean includeTerminationCheck) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyCore/Verifier/BoogieGenerator.TrStatement.cs:line 1441
   at Microsoft.Dafny.BoogieGenerator.TrWhileStmt(WhileStmt stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyCore/Verifier/BoogieGenerator.TrStatement.cs:line 998
   at Microsoft.Dafny.BoogieGenerator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyCore/Verifier/BoogieGenerator.TrStatement.cs:line 318
   at Microsoft.Dafny.BoogieGenerator.TrStmtList(List`1 stmts, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyCore/Verifier/BoogieGenerator.TrStatement.cs:line 2786
   at Microsoft.Dafny.BoogieGenerator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyCore/Verifier/BoogieGenerator.TrStatement.cs:line 305
   at Microsoft.Dafny.BoogieGenerator.AddMethodImpl(Method m, Procedure proc, Boolean wellformednessProc) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyCore/Verifier/BoogieGenerator.Methods.cs:line 667
   at Microsoft.Dafny.BoogieGenerator.AddMethod_Top(Method m, Boolean isByMethod, Boolean includeAllMethods) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyCore/Verifier/BoogieGenerator.Methods.cs:line 209
   at Microsoft.Dafny.BoogieGenerator.AddClassMembers(TopLevelDeclWithMembers c, Boolean includeAllMethods, Boolean includeInformationAboutType) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyCore/Verifier/BoogieGenerator.Methods.cs:line 79
   at Microsoft.Dafny.BoogieGenerator.AddRevealableTypeDecl(RevealableTypeDecl d) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyCore/Verifier/BoogieGenerator.Types.cs:line 879
   at Microsoft.Dafny.BoogieGenerator.DoTranslation(Program p, ModuleDefinition forModule) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyCore/Verifier/BoogieGenerator.cs:line 829
   at Microsoft.Dafny.BoogieGenerator.Translate(Program p, ErrorReporter reporter, TranslatorFlags flags)+MoveNext() in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyCore/Verifier/BoogieGenerator.cs:line 901
   at Microsoft.Dafny.CompilerDriver.Translate(ExecutionEngineOptions options, Program dafnyProgram)+MoveNext() in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyDriver/CompilerDriver.cs:line 224
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Dafny.CompilerDriver.<>c__DisplayClass4_0.<ProcessFilesAsync>b__0() in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyDriver/CompilerDriver.cs:line 153
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(Task task)
   at Microsoft.Boogie.CustomStackSizePoolTaskScheduler.WorkLoop()
   at System.Threading.Thread.StartCallback()
```

The exception is caused by expressions like `d.(n := d.n + 1)` having a null `ResolvedExpression`.

Found while trying to make JSON verify with `--type-system-refresh` on, as it uses datatype update expressions frequently in `invariant` and `decreases` clauses.

**Comment by olivier-aws** [comment]
Closing the issue as it cannot be reproduced with latest Dafny release (4.9.1).
