### ISSUE TITLE
type-system-refresh type synonym issue

### ISSUE THREAD

**Issue by selig** [dafny-lang/dafny#4984]
### Dafny version

4.3.0+e0127dd67001edf6523b20d6940c2e3699c2e6fa

### Code to produce this issue

```dafny
type T<A,B> = A

datatype Foo<A> = Foo(value: T<string, A>)
{
    function toString() : string
    {
      value
    }
}
```

### Command to run and resulting output

```code
dafny verify  --type-system-refresh tmp.dfy 

tmp.dfy(6,13): Error: Function body type mismatch (expected string, got T<string, A>)
  |
6 |     function toString() : string 
  |              ^^^^^^^^
```

### What happened?

I expected the type synonym to be expanded but it failed. The code verifies without the `type-system-refresh` option.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by selig** [comment]
I'm hoping this is related, if not I can cut a separate ticket. Expanding the example to

```
type T<A,B> = A

datatype Foo<A> =
    | Bar
    | Foo (value: T<string, A>)
{
    function toString() : string
    {
      match this {
        case Bar => "bar"
        case Foo(value: T<string, A>) => value
      }
    }
}
```

leads to

```
Unhandled exception: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dafny.SubtypeConstraint.ConstrainTypeArguments(List`1 parameters, List`1 superArguments, List`1 subArguments, IToken tok, PreTypeConstraint baseError, PreTypeConstraints constraints) in /Users/<redacted>/git/dafny/Source/DafnyCore/Resolver/PreType/PreTypeSubtypeConstraint.cs:line 118
   at Microsoft.Dafny.SubtypeConstraint.Apply(PreTypeConstraints constraints) in /Users/<redacted>/git/dafny/Source/DafnyCore/Resolver/PreType/PreTypeSubtypeConstraint.cs:line 65
   at Microsoft.Dafny.PreTypeConstraints.ApplySubtypeConstraints() in /Users/<redacted>/git/dafny/Source/DafnyCore/Resolver/PreType/PreTypeConstraints.cs:line 234
   at Microsoft.Dafny.PreTypeConstraints.PartiallySolveTypeConstraints(String printableContext, Boolean makeDecisions) in /Users/<redacted>/git/dafny/Source/DafnyCore/Resolver/PreType/PreTypeConstraints.cs:line 119
   at Microsoft.Dafny.PreTypeConstraints.SolveAllTypeConstraints(String printableContext) in /Users/<redacted>/git/dafny/Source/DafnyCore/Resolver/PreType/PreTypeConstraints.cs:line 142
   at Microsoft.Dafny.PreTypeResolver.ResolveFunction(Function f) in /Users/<redacted>/git/dafny/Source/DafnyCore/Resolver/PreType/PreTypeResolve.cs:line 1176
   at Microsoft.Dafny.PreTypeResolver.ResolveMember(MemberDecl member) in /Users/<redacted>/git/dafny/Source/DafnyCore/Resolver/PreType/PreTypeResolve.cs:line 978
   at Microsoft.Dafny.PreTypeResolver.ResolveDeclarationBody(Declaration d) in /Users/<redacted>/git/dafny/Source/DafnyCore/Resolver/PreType/PreTypeResolve.cs:line 793
   at Microsoft.Dafny.PreTypeResolver.ResolveDeclarations(List`1 declarations, ModuleResolver resolver, Boolean firstPhaseOnly) in /Users/<redacted>/git/dafny/Source/DafnyCore/Resolver/PreType/PreTypeResolve.cs:line 583
   at Microsoft.Dafny.ModuleResolver.ResolveTopLevelDecls_Core(List`1 declarations, Graph`1 datatypeDependencies, Graph`1 codatatypeDependencies, String moduleDescription, Boolean isAnExport) in /Users/<redacted>/git/dafny/Source/DafnyCore/Resolver/ModuleResolver.cs:line 1081
   at Microsoft.Dafny.ModuleDefinition.Resolve(ModuleSignature sig, ModuleResolver resolver, String exportSetName) in /Users/<redacted>/git/dafny/Source/DafnyCore/AST/Modules/ModuleDefinition.cs:line 508
   at Microsoft.Dafny.LiteralModuleDecl.Resolve(ModuleResolver resolver, CompilationData compilation) in /Users/<redacted>/git/dafny/Source/DafnyCore/AST/Modules/LiteralModuleDecl.cs:line 123
   at Microsoft.Dafny.ModuleResolver.ResolveModuleDeclaration(CompilationData compilation, ModuleDecl decl) in /Users/<redacted>/git/dafny/Source/DafnyCore/Resolver/ModuleResolver.cs:line 184
   at Microsoft.Dafny.ProgramResolver.ResolveModuleDeclaration(CompilationData compilation, ModuleDecl decl) in /Users/<redacted>/git/dafny/Source/DafnyCore/Resolver/ProgramResolver.cs:line 174
   at Microsoft.Dafny.ProgramResolver.Resolve(CancellationToken cancellationToken) in /Users/<redacted>/git/dafny/Source/DafnyCore/Resolver/ProgramResolver.cs:line 69
   at Microsoft.Dafny.DafnyMain.<>c__DisplayClass8_0.<Resolve>b__0() in /Users/<redacted>/git/dafny/Source/DafnyCore/DafnyMain.cs:line 86
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Microsoft.Dafny.DafnyMain.Resolve(Program program) in /Users/<redacted>/git/dafny/Source/DafnyCore/DafnyMain.cs:line 86
   at Microsoft.Dafny.DafnyMain.ParseCheck(TextReader stdIn, IReadOnlyList`1 files, String programName, DafnyOptions options, Program& program) in /Users/<redacted>/git/dafny/Source/DafnyCore/DafnyMain.cs:line 51
   at Microsoft.Dafny.CompilerDriver.ProcessFilesAsync(IReadOnlyList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, DafnyOptions options, ProofDependencyManager depManager, Boolean lookForSnapshots, String programId) in /Users/<redacted>/git/dafny/Source/DafnyDriver/CompilerDriver.cs:line 144
   at Microsoft.Dafny.CompilerDriver.RunCompiler(DafnyOptions options) in /Users/<redacted>/git/dafny/Source/DafnyDriver/CompilerDriver.cs:line 68
   at Microsoft.Dafny.DafnyCli.<>c__DisplayClass9_0.<<SetHandlerUsingDafnyOptionsContinuation>g__Handle|0>d.MoveNext() in /Users/<redacted>/git/dafny/Source/DafnyDriver/Commands/DafnyCli.cs:line 204
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Dafny.DafnyCli.<>c__DisplayClass20_0.<<AddDeveloperHelp>b__0>d.MoveNext() in /Users/<redacted>/git/dafny/Source/DafnyDriver/Commands/DafnyCli.cs:line 364
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

**Comment by alex-chew** [comment]
Thanks for the report, I was also able to reproduce the behavior on the 4.4.0 release (both the error with `--type-system-refresh`, and the success without).

I'm going to assign this to @RustanLeino for now.
