### ISSUE TITLE
{:only} causes crash

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#5064]
### Dafny version

4.4.0

### Code to produce this issue

```dafny
In `Source/DafnyStandardLibraries/src/Std/Unicode/Utf8EncodingScheme.dfy`, mark lemma `LemmaDeserializeSerialize` with `{:only}`.
```

### Command to run and resulting output

```code
In the Dafny root directory, do:

% time make -C Source/DafnyStandardLibraries all
dotnet run --project ../Dafny --no-build -- build -t:lib src/Std/dfyconfig.toml --output:build/DafnyStandardLibraries.doo
src/Std/Unicode/Utf8EncodingScheme.dfy(56,8): Error: Members with {:only} temporarily disable the verification of other members in the entire file
   |
56 |   lemma {:only}
   |         ^^^^^^^

Process terminated. Assertion failed.
   at Microsoft.Dafny.BinaryExpr.get_ResolvedOp() in $DAFNY/Source/DafnyCore/AST/Expressions/Operators/BinaryExpr.cs:line 122
   at Microsoft.Dafny.BoogieGenerator.CheckWellformedAndAssume(Expression expr, WFOptions wfOptions, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran, String comment) in $DAFNY/Source/DafnyCore/Verifier/BoogieGenerator.ExpressionWellformed.cs:line 141
   at Microsoft.Dafny.BoogieGenerator.AddMethodImpl(Method m, Procedure proc, Boolean wellformednessProc) in $DAFNY/Source/DafnyCore/Verifier/BoogieGenerator.Methods.cs:line 766
   at Microsoft.Dafny.BoogieGenerator.AddMethod_Top(Method m, Boolean isByMethod, Boolean includeAllMethods) in $DAFNY/Source/DafnyCore/Verifier/BoogieGenerator.Methods.cs:line 184
   at Microsoft.Dafny.BoogieGenerator.AddClassMembers(TopLevelDeclWithMembers c, Boolean includeAllMethods, Boolean includeInformationAboutType) in $DAFNY/Source/DafnyCore/Verifier/BoogieGenerator.Methods.cs:line 79
   at Microsoft.Dafny.BoogieGenerator.AddRevealableTypeDecl(RevealableTypeDecl d) in $DAFNY/Source/DafnyCore/Verifier/BoogieGenerator.Types.cs:line 879
   at Microsoft.Dafny.BoogieGenerator.DoTranslation(Program p, ModuleDefinition forModule) in $DAFNY/Source/DafnyCore/Verifier/BoogieGenerator.cs:line 821
   at Microsoft.Dafny.BoogieGenerator.Translate(Program p, ErrorReporter reporter, TranslatorFlags flags)+MoveNext() in $DAFNY/Source/DafnyCore/Verifier/BoogieGenerator.cs:line 893
   at Microsoft.Dafny.SynchronousCliCompilation.Translate(ExecutionEngineOptions options, Program dafnyProgram)+MoveNext() in $DAFNY/Source/DafnyDriver/SynchronousCliCompilation.cs:line 363
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Dafny.SynchronousCliCompilation.<>c__DisplayClass5_0.<ProcessFilesAsync>b__0() in $DAFNY/Source/DafnyDriver/SynchronousCliCompilation.cs:line 282
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   at System.Threading.Tasks.Task.ExecuteEntry()
   at System.Threading.Tasks.TaskScheduler.TryExecuteTask(Task task)
   at Microsoft.Boogie.CustomStackSizePoolTaskScheduler.WorkLoop()
   at System.Threading.Thread.StartCallback()
make: *** [build-binary] Error 134
make -C Source/DafnyStandardLibraries all  12.63s user 0.63s system 115% cpu 11.506 total
```

### What happened?

First, there's an error regarding the use of `{:only}`. (I'm guessing that's because of some setting in the `dfyconfig.toml` file.) Then, there's a crash (see above).

### What type of operating system are you experiencing the problem on?

Mac

**Comment by MikaelMayer** [comment]
I  can't reproduce the crash with this command-line

verify dfyconfig.toml

Did you have any other modifications on your branch?

**Comment by RustanLeino** [comment]
I can't repro with the current version, either. I did a bisect and found that https://github.com/dafny-lang/dafny/pull/4971 apparently fixed the problem.
