### ISSUE TITLE
Code completion request causes exception

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/dafny#5130]
```dafny 
[Trace - 1:27:02 PM] Received response 'textDocument/completion - (818)' in 7ms. Request failed: Internal Error - System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dafny.NodeExtensions.FindNodeChain(INode node, DafnyPosition position, LList`1 parent, Func`2 predicate)
   at Microsoft.Dafny.NodeExtensions.FindNodeChain(INode node, DafnyPosition position, LList`1 parent, Func`2 predicate)
   at Microsoft.Dafny.NodeExtensions.FindNodeChain(INode node, DafnyPosition position, LList`1 parent, Func`2 predicate)
   at Microsoft.Dafny.NodeExtensions.FindNodeChain(INode node, DafnyPosition position, LList`1 parent, Func`2 predicate)
   at Microsoft.Dafny.NodeExtensions.FindNodeChain(INode node, Uri uri, DafnyPosition position, LList`1 parent, Func`2 predicate)
   at Microsoft.Dafny.NodeExtensions.FindNodeChain(INode node, Uri uri, DafnyPosition position, LList`1 parent, Func`2 predicate)
   at Microsoft.Dafny.NodeExtensions.FindNodeChain(INode node, Uri uri, DafnyPosition position, LList`1 parent, Func`2 predicate)
   at Microsoft.Dafny.NodeExtensions.FindNode[T](INode root, Uri uri, DafnyPosition position)
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyCompletionHandler.CompletionProcessor.IsDotExpression()
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyCompletionHandler.CompletionProcessor.Process()
   at Microsoft.Dafny.LanguageServer.Handlers.DafnyCompletionHandler.Handle(CompletionParams request, CancellationToken cancellationToken)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.SemanticTokensDeltaPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at OmniSharp.Extensions.LanguageServer.Server.Pipelines.ResolveCommandPipeline`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
   at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
```

```dafny
class Queue<T> {
  var head : Node?<T>
  var tail : Node?<T>
  ghost var footprint : set<object>

  function Contents(): seq<T> {
    if head == null then [] else head.contents
  }

  function Spine(): set<Node<T>> {
    if head == null then {} else head.Elements()
  }

  function Footprint(): set<object> {
    if head == null then {this} else {this} + head.footprint
  }

  ghost function Valid() : bool
    reads this, Footprint()
  {
    this in footprint && 
    if (head == null) then
      tail == null && contents == []
    else 
      head.Valid() &&
      tail != null && 
      tail.next == null &&
      contents == head.contents
  }

  constructor()
    ensures Valid() && fresh(footprint - {this})
    ensures |contents| == 0
  {
    head := null;
    tail := null;
    contents := [];
    footprint := { this };
  }

  method Front() returns (d: T) 
    requires Valid()
    requires |contents| > 0
    ensures d == contents[0]
  {
    d := head.data;
  }

  method Dequeue ()
    requires Valid()
    requires 0 < |contents|
    modifies footprint
    ensures Valid() && fresh(footprint - old(footprint))
    ensures contents == old(contents)[1..]
  {
    var n := head.next;
    head := n;
    contents := n.tailContents;
  }

  method Enqueue(d: T)
    requires Valid()
    modifies footprint
    ensures Valid()  && fresh(footprint - old(footprint))
    ensures contents == old(contents) + [d]
  {
    if (head == null) {

      var n := new Node(d);
      head := n;
      tail := n;
      contents := n.contents;
      footprint := { this } + n.footprint;
      assert n.next == null;
      assert Valid();
    } else {
      var n := new Node(d);
      tail.next := n;
      tail := n;
      forall m <- Spine() {
        m.contents := m.contents + [d];
      }
      contents := head.contents;
      forall m <- Spine() {
        m.footprint := m.footprint + n.footprint;
      }
      footprint := footprint + n.footprint;
    }
  }
}

class Node<T> {
  var data: T
  var next: Node?<T>
  ghost var contents : seq<T>
  ghost var footprint : set<object>

  ghost function Elements(): set<Node<T>> {
    {this} + if next == null then {} else next.Elements()
  }

  ghost function Valid(): bool
    reads this, footprint
  {
    this in footprint &&
    if next == null
      then contents == [data]
      else next in footprint 
        && next.footprint < footprint // Remove?
        && next.Valid()
        && contents == [data] + next.contents // Remove ?
  }

  constructor(data: T)
    ensures Valid() && fresh(footprint - {this})
    ensures next == null
  {
    this.data := data;
    next := null;
    contents := [data];
    footprint := {this};
  }
}
```

**Comment by keyboardDrummer** [comment]
Closing because I could not reproduce this
