### ISSUE TITLE
StandardLibraries fail to load with `--allow-warnings` flag and throw NPE

### ISSUE THREAD

**Issue by ShubhamChaturvedi7** [dafny-lang/dafny#5145]
### Dafny version

master branch

### Code to produce this issue

```dafny
commit id: f2d6e5cab8d478ee5aed5991114f80ddb01af38e
```

### Command to run and resulting output

```code
Command:

dafny translate go --allow-warnings --standard-libraries dafny_go.dfy
```

Output:
```
CLI: Warning: cannot load /DafnyStandardLibraries-go.doo: --allow-warnings is set locally to True, but the library was built with False
CLI: Warning: cannot load /DafnyStandardLibraries.doo: --allow-warnings is set locally to True, but the library was built with False
Unhandled exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Dafny.DafnyFile.FileNames(IReadOnlyList`1 dafnyFiles) in /Users/scchatur/workspace/DafnyLang/dafny/Source/DafnyCore/DafnyFile.cs:line 207
   at Microsoft.Dafny.SynchronousCliCompilation.ProcessFilesAsync(IReadOnlyList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, DafnyOptions options, ProofDependencyManager depManager, Boolean lookForSnapshots, String programId) in /Users/scchatur/workspace/DafnyLang/dafny/Source/DafnyDriver/Legacy/SynchronousCliCompilation.cs:line 238
   at Microsoft.Dafny.SynchronousCliCompilation.Run(DafnyOptions options) in /Users/scchatur/workspace/DafnyLang/dafny/Source/DafnyDriver/Legacy/SynchronousCliCompilation.cs:line 62
   at Microsoft.Dafny.TranslateCommand.<>c__DisplayClass3_0.<<Create>b__0>d.MoveNext() in /Users/scchatur/workspace/DafnyLang/dafny/Source/DafnyDriver/Commands/TranslateCommand.cs:line 48
--- End of stack trace from previous location ---
   at Microsoft.Dafny.DafnyNewCli.<>c__DisplayClass5_0.<<SetHandlerUsingDafnyOptionsContinuation>g__Handle|0>d.MoveNext() in /Users/scchatur/workspace/DafnyLang/dafny/Source/DafnyDriver/DafnyNewCli.cs:line 116
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Dafny.DafnyNewCli.<>c__DisplayClass17_0.<<AddDeveloperHelp>b__0>d.MoveNext() in /Users/scchatur/workspace/DafnyLang/dafny/Source/DafnyDriver/DafnyNewCli.cs:line 270
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()

Process finished with exit code 1.

```
```


### What happened?

Either we need a version of StandardLibraries doo with `allow-warnings` set to true or / and we need to handle the resulting NPE if we decide to not load the library.

### What type of operating system are you experiencing the problem on?

Mac

**Comment by robin-aws** [comment]
There are two issues, possibly with separate root causes:
1. The compatibility check on `--allow-warnings` is backwards: it should be allowed for the library to have False, but the local context to have True, since False in this case is the more restrictive setting.
2. The crash should obviously not happen regardless. :)

**Comment by keyboardDrummer** [comment]
Here's a fix for (1):

Could you help me reproduce the crash @ShubhamChaturvedi7 ? What's the input file I should use?
