### ISSUE TITLE
Crash on running a program on the library backend

### ISSUE THREAD

**Issue by robin-aws** [dafny-lang/dafny#5156]
### Dafny version

4.4.0

### Code to produce this issue

```dafny
method Main() {
  print "Doesn't matter, doesn't even need to have a main method";
}
```

### Command to run and resulting output

```code
> dafny run -t:lib Scratch.dfy

Dafny program verifier finished with 3 verified, 0 errors
/Users/salkeldr/Documents/GitHub/dafny/Binaries/Dafny.dll, run, --target:cs, /Users/salkeldr/Documents/GitHub/libraries/src/Scratch.doo
Unhandled exception. System.AggregateException: One or more errors occurred. (One or more errors occurred. (StandardError has not been redirected.))
 ---> System.AggregateException: One or more errors occurred. (StandardError has not been redirected.)
 ---> System.InvalidOperationException: StandardError has not been redirected.
   at System.Diagnostics.Process.BeginErrorReadLine()
   at Microsoft.Dafny.Compilers.ExecutableBackend.RunTargetDafnyProgram(String targetFilename, TextWriter outputWriter, TextWriter errorWriter, Boolean verify) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyCore/Compilers/ExecutableBackend.cs:line 197
   at Microsoft.Dafny.Compilers.LibraryBackend.RunTargetProgram(String dafnyProgramName, String targetProgramText, String callToMain, String targetFilename, ReadOnlyCollection`1 otherFileNames, Object compilationResult, TextWriter outputWriter, TextWriter errorWriter) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyCore/Compilers/Library/LibraryBackend.cs:line 85
   at Microsoft.Dafny.DafnyDriver.CompileDafnyProgram(Program dafnyProgram, String dafnyProgramName, ReadOnlyCollection`1 otherFileNames, Boolean invokeCompiler) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyDriver/DafnyDriver.cs:line 948
   at Microsoft.Dafny.DafnyDriver.Compile(String fileName, ReadOnlyCollection`1 otherFileNames, Program dafnyProgram, PipelineOutcome oc, IDictionary`2 moduleStats, Boolean verified) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyDriver/DafnyDriver.cs:line 750
   at Microsoft.Dafny.DafnyDriver.ProcessFilesAsync(IReadOnlyList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, DafnyOptions options, Boolean lookForSnapshots, String programId) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyDriver/DafnyDriver.cs:line 448
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Dafny.DafnyDriver.ThreadMain(TextWriter outputWriter, TextWriter errorWriter, TextReader inputReader, String[] args) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyDriver/DafnyDriver.cs:line 142
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass11_0.<MainWithWriters>b__0() in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyDriver/DafnyDriver.cs:line 119
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.Dafny.DafnyDriver.MainWithWriters(TextWriter outputWriter, TextWriter errorWriter, TextReader inputReader, String[] args) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyDriver/DafnyDriver.cs:line 119
   at Microsoft.Dafny.DafnyDriver.Main(String[] args) in /Users/salkeldr/Documents/GitHub/dafny/Source/DafnyDriver/DafnyDriver.cs:line 106
   at Dafny.Dafny.Main(String[] args) in /Users/salkeldr/Documents/GitHub/dafny/Source/Dafny/Dafny.cs:line 7
/Users/salkeldr/Documents/GitHub/dafny/Scripts/dafny: line 35: 57365 Abort trap: 6           "$DOTNET" "$DAFNY" "$@"
```

### What happened?

No crash would be nice. :)

### What type of operating system are you experiencing the problem on?

Mac

**Comment by robin-aws** [comment]
The fix is a one-liner, but I'm hoping to also switch things to run all integration tests against the Library Backend as well, as a simple way to catch regressions like this.

**Comment by keyboardDrummer** [comment]
I'm not convinced we should run the integration tests against the library back-end. It would end up using another back-end as well and we'd be testing that one twice.

For fixing this bug, I suggest disallowing using `run` together with the lib target.
