### ISSUE TITLE
Internal error with datatype traits

### ISSUE THREAD

**Issue by erniecohen** [dafny-lang/dafny#5194]
### Dafny version

4.4.0

### Code to produce this issue

```dafny
trait TC {
    predicate myType?(o:TC) 
}
trait Num extends TC {
    function plus(n:Num):Num requires myType?(n) ensures myType?(plus(n))
}
datatype N extends Num = N(v:nat) {  // type N extends Num also causes a crash
    predicate myType?(o:TC)  { o is N }
    function plus(n:Num):Num  requires myType?(n)
}
```

### Command to run and resulting output

```code
vscode, with --type-system-refresh --general-traits=datatype
```

### What happened?

Dafny encountered an internal error. Please report it at <https://github.com/dafny-lang/dafny/issues>.
System.InvalidCastException: Unable to cast object of type 'Microsoft.Dafny.IndDatatypeDecl' to type 'Microsoft.Dafny.ClassLikeDecl'.
   at Microsoft.Dafny.BoogieGenerator.AddFunctionOverrideReqsChk(Function f, BoogieStmtListBuilder builder, ExpressionTranslator etran, Dictionary`2 substMap, Dictionary`2 typeMap)
   at Microsoft.Dafny.BoogieGenerator.AddFunctionOverrideCheckImpl(Function f)
   at Microsoft.Dafny.BoogieGenerator.AddFunction_Top(Function f, Boolean includeAllMethods)
   at Microsoft.Dafny.BoogieGenerator.AddClassMembers(TopLevelDeclWithMembers c, Boolean includeAllMethods, Boolean includeInformationAboutType)
   at Microsoft.Dafny.BoogieGenerator.DoTranslation(Program p, ModuleDefinition forModule)
   at Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier.<>c__DisplayClass3_0.<GetVerificationTasksAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Dafny.LanguageServer.Language.DafnyProgramVerifier.GetVerificationTasksAsync(ExecutionEngine boogieEngine, ResolutionResult resolution, ModuleDefinition moduleDefinition, CancellationToken cancellationToken)
   at Microsoft.Dafny.LanguageServer.Workspace.Compilation.<>c__DisplayClass47_0.<<VerifyUnverifiedSymbol>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Dafny.LanguageServer.Workspace.Compilation.VerifyUnverifiedSymbol(Boolean onlyPrepareVerificationForGutterTests, ICanVerify canVerify, ResolutionResult resolution)
   at Microsoft.Dafny.LanguageServer.Workspace.Compilation.VerifyUnverifiedSymbol(Boolean onlyPrepareVerificationForGutterTests, ICanVerify canVerify, ResolutionResult resolution)

### What type of operating system are you experiencing the problem on?

Mac

**Comment by erniecohen** [comment]
Fixed in 4.5
