### ISSUE TITLE
Unstable ChangedImportAffectsExport and ProjectFileDoesNotOwnAllSourceFilesItUses

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/dafny#5291]
For ChangedImportAffectsExport:

https://github.com/dafny-lang/dafny/actions/runs/8520037939/job/23335354897?pr=5284

The test had already received resolution started and was waiting to get a resolution finished notification, but it never came:
```
      Waited for 49 seconds for new notification.
      Last received notification was CompilationStatusParams {
        Uri = file:///home/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer.Test/bin/Debug/net6.0/n4dupj3j.lsi/dfyconfig.toml,
        Version = 1,
        Status = ResolutionStarted
      }
[xUnit.net 00:03:17.26]     Microsoft.Dafny.LanguageServer.IntegrationTest.Synchronization.CachingTest.ChangedImportAffectsExport [FAIL]
[xUnit.net 00:03:17.26]       System.OperationCanceledException : The operation was canceled.
```

For ProjectFileDoesNotOwnAllSourceFilesItUses:

The test had already received a parsing notification and was waiting to get a resolution finished notification, but it and resolution started:

```
info: default[0]
      Waited for 49 seconds for new notification.
      Last received notification was CompilationStatusParams {
        Uri = file:///var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/3daxm55m.q1m/dfyconfig.toml,
        Version = 1,
        Status = Parsing
      }
[xUnit.net 00:08:46.42]     Microsoft.Dafny.LanguageServer.IntegrationTest.ProjectFiles.CompetingProjectFilesTest.ProjectFileDoesNotOwnAllSourceFilesItUses [FAIL]
[xUnit.net 00:08:46.42]       System.OperationCanceledException : The operation was canceled.
[xUnit.net 00:08:46.42]       Stack Trace:
[xUnit.net 00:08:46.43]            at System.Threading.CancellationToken.ThrowOperationCanceledException()
[xUnit.net 00:08:46.43]            at System.Threading.SemaphoreSlim.WaitUntilCountOrTimeoutAsync(TaskNode asyncWaiter, Int32 millisecondsTimeout, CancellationToken cancellationToken)
[xUnit.net 00:08:46.43]         /Users/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer.Test/Util/TestNotificationReceiver.cs(58,0): at Microsoft.Dafny.LanguageServer.IntegrationTest.Util.TestNotificationReceiver`1.AwaitNextNotificationAsync(CancellationToken cancellationToken)
[xUnit.net 00:08:46.43]         /Users/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer.Test/Util/ClientBasedLanguageServerTest.cs(208,0): at Microsoft.Dafny.LanguageServer.IntegrationTest.Util.ClientBasedLanguageServerTest.WaitUntilResolutionFinished(TextDocumentItem documentId, CancellationToken cancellationToken)
```

**Comment by keyboardDrummer** [comment]
Resolved with https://github.com/dafny-lang/dafny/pull/5299
