### ISSUE TITLE
Unstable test due to timeout when executing Rust back-end

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/dafny#5321]
https://github.com/dafny-lang/dafny/actions/runs/8680288212/job/23800559477

```
[xUnit.net 00:09:42.93]         Previous command results:
  Failed dafny4/git-issue79.dfy [54 s]
  Error Message:
   System.AggregateException : One or more errors occurred. (Command returned non-zero exit code (255): dotnet /home/runner/work/dafny/dafny/dafny/Source/IntegrationTests/bin/Debug/net6.0/TestDafny.dll for-each-compiler --dafny /home/runner/work/dafny/dafny/unzippedRelease/dafny/dafny --refresh-exit-code=0 TestFiles/LitTests/LitTest/dafny4/git-issue79.dfy -- --relax-definite-assignment
Output:
Using legacy resolver and verifying...
Using refresh resolver and verifying...
Executing on C#...
Executing on C# (with --include-runtime:false)...
Executing on JavaScript...
Executing on Go...
Executing on Java...
Executing on Python...
Executing on C++...
Executing on Rust...
Execution failed, for reasons other than known unsupported features. Output:

Error:

Executing on ResolvedDesugaredExecutableDafny...

Error:
)
---- System.Exception : Command returned non-zero exit code (255): dotnet /home/runner/work/dafny/dafny/dafny/Source/IntegrationTests/bin/Debug/net6.0/TestDafny.dll for-each-compiler --dafny /home/runner/work/dafny/dafny/unzippedRelease/dafny/dafny --refresh-exit-code=0 TestFiles/LitTests/LitTest/dafny4/git-issue79.dfy -- --relax-definite-assignment
Output:
Using legacy resolver and verifying...
Using refresh resolver and verifying...
Executing on C#...
Executing on C# (with --include-runtime:false)...
Executing on JavaScript...
Executing on Go...
Executing on Java...
Executing on Python...
Executing on C++...
Executing on Rust...
Execution failed, for reasons other than known unsupported features. Output:

Error:

Executing on ResolvedDesugaredExecutableDafny...

Error:

  Stack Trace:
     at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
```

**Comment by MikaelMayer** [comment]
Probably related to #5537
