### ISSUE TITLE
Flaky test failure: dafny0/snapshots/Snapshots9.run.legacy.dfy

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#5396]
In the following run that broke the nightly:
https://github.com/dafny-lang/dafny/actions/runs/8925653489/job/24514822482
a test failed on only one backend.
@robin-aws  @keyboardDrummer  is creating this issue the best thing to do?

```
[xUnit.net 00:08:11.21]     dafny0/snapshots/Snapshots9.run.legacy.dfy [FAIL]
[xUnit.net 00:08:11.21]       System.AggregateException : One or more errors occurred. (Command returned non-zero exit code (1): %exits-with 4  /home/runner/work/dafny/dafny/unzippedRelease/dafny/dafny /vcsCores:2 /useBaseNameForFileName /compileVerbose:0 /rlimit:50000000 /timeLimit:300 /allowAxioms:1 /showSnippets:0 /compile:0 /verifySnapshots:3 /traceCaching:1 /home/runner/work/dafny/dafny/dafny/Source/IntegrationTests/bin/Debug/net6.0/TestFiles/LitTests/LitTest/dafny0/snapshots/Inputs/Snapshots9.dfy > /home/runner/work/dafny/dafny/dafny/Source/IntegrationTests/bin/Debug/net6.0/TestFiles/LitTests/LitTest/dafny0/snapshots/Output/Snapshots9.run.legacy.dfy.tmp
[xUnit.net 00:08:11.21]       Output:
[xUnit.net 00:08:11.21]       Warning: this way of using the CLI is deprecated. Use 'dafny --help' to see help for the new Dafny CLI format
[xUnit.net 00:08:11.21]       Processing command (at Snapshots9.v0.dfy(2,11)) assert {:id "id2"} ok#0;
[xUnit.net 00:08:11.21]         >>> DoNothingToAssert
[xUnit.net 00:08:11.21]       Snapshots9.v0.dfy(4,7): Error: a postcondition could not be proved on this return path
[xUnit.net 00:08:11.21]       Snapshots9.v0.dfy(2,10): Related location: this is the postcondition that could not be proved
[xUnit.net 00:08:11.21]       Processing command (at Snapshots9.v0.dfy(12,11)) assert {:id "id7"} ok#0;
[xUnit.net 00:08:11.22]         >>> DoNothingToAssert
[xUnit.net 00:08:11.22]       Snapshots9.v0.dfy(13,0): Error: a postcondition could not be proved on this return path
[xUnit.net 00:08:11.22]       Snapshots9.v0.dfy(12,10): Related location: this is the postcondition that could not be proved
[xUnit.net 00:08:11.22]       
[xUnit.net 00:08:11.22]       Dafny program verifier finished with 0 verified, 2 errors
[xUnit.net 00:08:11.22]       Processing command (at Snapshots9.v1.dfy(6,11)) assert {:id "id10"} ok#0;
[xUnit.net 00:08:11.22]         >>> RecycleError
[xUnit.net 00:08:11.22]       Snapshots9.v1.dfy(8,7): Error: a postcondition could not be proved on this return path
[xUnit.net 00:08:11.22]       Snapshots9.v1.dfy(6,10): Related location: this is the postcondition that could not be proved
[xUnit.net 00:08:11.22]       Processing command (at Snapshots9.v1.dfy(19,11)) assert {:id "id15"} ok#0;
Processing command (at Snapshots9.v1.dfy(6,11)) assert {:id "id10"} ok#0;
  >>> RecycleError
Snapshots9.v1.dfy(8,7): Error: a postcondition could not be proved on this return path
Snapshots9.v1.dfy(6,10): Related location: this is the postcondition that could not be proved
Processing command (at Snapshots9.v1.dfy(19,11)) assert {:id "id15"} ok#0;
  >>> RecycleError

Error:
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Boogie.ReadOnlyVisitor.VisitVariable(Variable node)
   at Microsoft.Boogie.ReadOnlyVisitor.VisitVariableSeq(List`1 variableSeq)
   at Microsoft.Boogie.ReadOnlyVisitor.VisitImplementation(Implementation node)
   at Microsoft.Boogie.Implementation.StdDispatch(StandardVisitor visitor)
   at Microsoft.Boogie.ReadOnlyVisitor.Visit(Absy node)
   at Microsoft.Boogie.ReadOnlyVisitor.VisitDeclarationList(List`1 declarationList)
   at Microsoft.Boogie.ReadOnlyVisitor.VisitProgram(Program node)
   at Microsoft.Boogie.Program.StdDispatch(StandardVisitor visitor)
   at Microsoft.Boogie.ReadOnlyVisitor.Visit(Absy node)
   at Microsoft.Boogie.BasicTypeVisitor..ctor(Absy absy)
   at Microsoft.Boogie.Checker.Target(Program prog, ProverContext ctx, Split split)
   at VC.CheckerPool.PrepareChecker(Program program, Split split, Checker checker)
   at VC.CheckerPool.FindCheckerFor(Program program, Split split, CancellationToken cancellationToken)
   at VC.SplitAndVerifyWorker.DoWork(Int32 iteration, Split split, CancellationToken cancellationToken)
   at VC.SplitAndVerifyWorker.DoWorkForMultipleIterations(Split split, CancellationToken cancellationToken)
   at VC.SplitAndVerifyWorker.WorkUntilDone(CancellationToken cancellationToken)
   at VC.VerificationConditionGenerator.VerifyImplementation(ImplementationRun run, VerifierCallback callback, CancellationToken cancellationToken)
   at VC.ConditionGeneration.VerifyImplementation2(ImplementationRun run, CancellationToken cancellationToken)
   at Microsoft.Boogie.ExecutionEngine.<>c__DisplayClass52_0.<<VerifyImplementationWithoutCaching>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Boogie.ExecutionEngine.VerifyImplementation(ProcessedProgram processedProgram, PipelineStatistics stats, ErrorReporterDelegate er, CancellationToken cancellationToken, Implementation implementation, String programId, TextWriter traceWriter)
   at Microsoft.Boogie.ExecutionEngine.EnqueueVerifyImplementation(ProcessedProgram processedProgram, PipelineStatistics stats, String programId, ErrorReporterDelegate errorReporterDelegate, Implementation implementation, CancellationToken cancellationToken, TextWriter taskWriter)
   at Microsoft.Boogie.ExecutionEngine.<>c__DisplayClass43_0.<<VerifyEachImplementation>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Boogie.ExecutionEngine.<>c__DisplayClass43_0.<<VerifyEachImplementation>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Boogie.ExecutionEngine.VerifyEachImplementation(TextWriter outputWriter, ProcessedProgram processedProgram, PipelineStatistics stats, String programId, ErrorReporterDelegate er, String requestId, Implementation[] stablePrioritizedImpls)
   at Microsoft.Boogie.ExecutionEngine.InferAndVerify(TextWriter output, Program program, PipelineStatistics stats, String programId, ErrorReporterDelegate er, String requestId)
   at Microsoft.Dafny.DafnyMain.BoogiePipelineWithRerun(DafnyOptions options, TextWriter output, ExecutionEngine engine, Program program, String bplFileName, String programId)
   at Microsoft.Dafny.DafnyMain.BoogieOnce(ErrorReporter errorReporter, DafnyOptions options, TextWriter output, ExecutionEngine engine, String baseFile, String moduleName, Program boogieProgram, String programId)
   at Microsoft.Dafny.SynchronousCliCompilation.BoogieOnceWithTimerAsync(ErrorReporter errorReporter, TextWriter output, DafnyOptions options, String baseName, String programId, String moduleName, Program program)
   at Microsoft.Dafny.SynchronousCliCompilation.<>c__DisplayClass9_0.<<BoogieAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Dafny.SynchronousCliCompilation.<>c__DisplayClass9_0.<<BoogieAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Dafny.SynchronousCliCompilation.BoogieAsync(ErrorReporter errorReporter, DafnyOptions options, String baseName, IEnumerable`1 boogiePrograms, String programId)
   at Microsoft.Dafny.SynchronousCliCompilation.ProcessFilesAsync(IReadOnlyList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, DafnyOptions options, ProofDependencyManager depManager, Boolean lookForSnapshots, String programId)
   at Microsoft.Dafny.SynchronousCliCompilation.ProcessFilesAsync(IReadOnlyList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, DafnyOptions options, ProofDependencyManager depManager, Boolean lookForSnapshots, String programId)
   at Microsoft.Dafny.SynchronousCliCompilation.Run(DafnyOptions options)
   at Dafny.Dafny.<Main>(String[] args)
Moreover the expected exit code was 4 but got 134

  Stack Trace:
     at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait(TimeSpan timeout)
   at XUnitExtensions.Lit.LitTestCase.Run(String filePath, LitTestConfiguration config, ITestOutputHelper outputHelper) in /home/runner/work/dafny/dafny/dafny/Source/XUnitExtensions/Lit/LitTestCase.cs:line 61
   at IntegrationTests.LitTests.LitTest(String path) in /home/runner/work/dafny/dafny/dafny/Source/IntegrationTests/LitTests.cs:line 251
----- Inner Stack Trace -----
   at XUnitExtensions.Lit.LitTestCase.Execute(ITestOutputHelper outputHelper) in /home/runner/work/dafny/dafny/dafny/Source/XUnitExtensions/Lit/LitTestCase.cs:line 101
  Standard Output Messages:
 Executing command: %exits-with 4  /home/runner/work/dafny/dafny/unzippedRelease/dafny/dafny /vcsCores:2 /useBaseNameForFileName /compileVerbose:0 /rlimit:[500](https://github.com/dafny-lang/dafny/actions/runs/8925653489/job/24514822482#step:24:501)00000 /timeLimit:300 /allowAxioms:1 /showSnippets:0 /compile:0 /verifySnapshots:3 /traceCaching:1 /home/runner/work/dafny/dafny/dafny/Source/IntegrationTests/bin/Debug/net6.0/TestFiles/LitTests/LitTest/dafny0/snapshots/Inputs/Snapshots9.dfy > /home/runner/work/dafny/dafny/dafny/Source/IntegrationTests/bin/Debug/net6.0/TestFiles/LitTests/LitTest/dafny0/snapshots/Output/Snapshots9.run.legacy.dfy.tmp
 Previous command results:
```

**Comment by MikaelMayer** [comment]
In either case, the null exception arise from the only dereference:

```
node.TypedIdent
```
which either means that "node" is null at this point, or that because of the contract, the internal field typedIdent is null.
Looking up in the trace, the call leading to this must have been in VisitVariableSeq:

```
        this.VisitVariable(cce.NonNull(variableSeq[i]));
```
Here it has checked that node is not `null`.
This means that `node.typedIdent == null`

Since `typeIdent` is set either by one of the two constructors or by the setter of `TypeIdent`, all of which have contracts that would have failed if `typeIdent` was null, contradiction.

So it looks like contracts are not enforced in this trace, and this means that `variableSeq[i]` was null. At this point, it becomes intractable to detect where the issue comes from.

@leino any way we can run contracts so that we could detect earlier what is wrong?
@robin-aws  once we know how to run contracts, could you enable it in your branch that runs Dafny 5 times in search of flaky tests?

**Comment by keyboardDrummer** [comment]
Closing since this seems to be a duplicate: https://github.com/dafny-lang/dafny/issues/4387

LMK if I made a mistake.
