### ISSUE TITLE
Flaky CI Test: LanguageServer.IntegrationTest.ProjectFiles.CompetingProjectFilesTest.ProjectFileDoesNotOwnAllSourceFilesItUses

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#5420]
Seen here:
https://github.com/dafny-lang/dafny/actions/runs/9033557172/job/24824185710?pr=5390

The meaningful error is this one:
```
  Failed Microsoft.Dafny.LanguageServer.IntegrationTest.ProjectFiles.CompetingProjectFilesTest.ProjectFileDoesNotOwnAllSourceFilesItUses [49 s]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at Microsoft.Dafny.LanguageServer.IntegrationTest.Util.TestNotificationReceiver`1.AwaitNextNotificationAsync(CancellationToken cancellationToken) in /Users/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer.Test/Util/TestNotificationReceiver.cs:line 58
   at Microsoft.Dafny.LanguageServer.IntegrationTest.Util.ClientBasedLanguageServerTest.WaitUntilResolutionFinished(TextDocumentItem documentId, CancellationToken cancellationToken) in /Users/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer.Test/Util/ClientBasedLanguageServerTest.cs:line 207
   at Microsoft.Dafny.LanguageServer.IntegrationTest.Util.ClientBasedLanguageServerTest.WaitUntilAllStatusAreCompleted(TextDocumentItem documentId, Nullable`1 cancellationToken, Boolean allowStale) in /Users/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer.Test/Util/ClientBasedLanguageServerTest.cs:line 179
   at Microsoft.Dafny.LanguageServer.IntegrationTest.Util.ClientBasedLanguageServerTest.GetLatestDiagnosticsParams(TextDocumentItem documentItem, CancellationToken cancellationToken, Boolean allowStale) in /Users/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer.Test/Util/ClientBasedLanguageServerTest.cs:line 214
   at Microsoft.Dafny.LanguageServer.IntegrationTest.Util.ClientBasedLanguageServerTest.GetLastDiagnostics(TextDocumentItem documentItem, DiagnosticSeverity minimumSeverity, Nullable`1 cancellationToken, Boolean allowStale) in /Users/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer.Test/Util/ClientBasedLanguageServerTest.cs:line 229
   at Microsoft.Dafny.LanguageServer.IntegrationTest.ProjectFiles.CompetingProjectFilesTest.ProjectFileDoesNotOwnAllSourceFilesItUses() in /Users/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer.Test/ProjectFiles/CompetingProjectFilesTest.cs:line 33
--- End of stack trace from previous location ---
```

Note that there are a lot of caught errors (~60) like this, which look suspicious
```
fail: Microsoft.Dafny.Compilation[0]
      Caught error in statusUpdates observable.
      System.Exception: CheckerPool was already disposed
         at VC.CheckerPool.FindCheckerFor(Program program, Split split, CancellationToken cancellationToken)
         at Microsoft.Boogie.VerificationTask.StartRun(CancellationToken cancellationToken)+MoveNext()
         at Microsoft.Boogie.VerificationTask.StartRun(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
         at System.Linq.AsyncEnumerable.ToObservableObservable`1.<>c__DisplayClass2_0.<<Subscribe>g__Core|0>d.MoveNext() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/ToObservable.cs:line 50
  Passed Microsoft.Dafny.LanguageServer.IntegrationTest.Synchronization.LookupMigrationTest.MigrationMovesLinesOfSymbolsAfterWhenChangingInTheMiddle [572 ms]
  Passed Microsoft.Dafny.LanguageServer.IntegrationTest.Unit.TextDocumentLoaderTest.LoadReturnsCanceledTaskIfOperationIsCanceled [84 ms]
  Passed Microsoft.Dafny.LanguageServer.IntegrationTest.Unit.TextDocumentLoaderTest.LoadReturnsFaultedTaskIfAnyExceptionOccured [8 ms]
  Passed Microsoft.Dafny.LanguageServer.IntegrationTest.Refinement.RefinementTests.RefinedLemmaNewEnsuresIsVerified [780 ms]
  Passed Microsoft.Dafny.LanguageServer.IntegrationTest.ProjectFiles.CompetingProjectFilesTest.NewProjectFileGrabsSourceFileOwnership 
```

**Comment by MikaelMayer** [comment]
Just hit this one again here:
https://github.com/dafny-lang/dafny/actions/runs/9084945479/job/24967092885?pr=5442

**Comment by keyboardDrummer** [comment]
https://github.com/dafny-lang/dafny/actions/runs/9086218954/job/24971402176?pr=5419

**Comment by keyboardDrummer** [comment]
Could not reproduce locally by repeatedly running the test

**Comment by MikaelMayer** [comment]
Most of times I can't reproduce these flaky tests locally too.

**Comment by MikaelMayer** [comment]
Just hit this one once more here:
https://github.com/dafny-lang/dafny/actions/runs/9086459983/job/24972200624?pr=5441

**Comment by MikaelMayer** [comment]
This this one once more here:
https://github.com/dafny-lang/dafny/actions/runs/9084945479/job/24970423788?pr=5442

**Comment by MikaelMayer** [comment]
Hit that one again.
https://github.com/dafny-lang/dafny/actions/runs/9098279864/job/25008387659?pr=5442

**Comment by MikaelMayer** [comment]
Hi that one again in another PR.
https://github.com/dafny-lang/dafny/actions/runs/9098667133/job/25009913970?pr=5440

**Comment by keyboardDrummer** [comment]
There's a concurrency fix in https://github.com/dafny-lang/dafny/pull/5444 that has a chance of fixing this. 

Also, that PR improves the logging so the log contains less garbage, which is still present in the last reported log. If this reoccurs please report the log.
