### ISSUE TITLE
Unstable test ChangingTheDocumentStopsOnChangeVerification

### ISSUE THREAD

**Issue by keyboardDrummer** [dafny-lang/dafny#5436]
Timeout: https://github.com/dafny-lang/dafny/actions/runs/9075070562/job/24934982834?pr=5429

```
      Waited for 49 seconds for new notification.
      Last received notification was SymbolStatus, Uri: file:///tmp/0oq3xvzl.lbt/ChangingTheDocumentStopsOnChangeVerification.dfy, Version: 1, NamedVerifiables: NamedVerifiableStatus { NameRange = [start: (0, 23), end: (0, 26)], Status = Running }, NamedVerifiableStatus { NameRange = [start: (11, 32), end: (11, 36)], Status = Running }
[xUnit.net 00:01:10.35]     Microsoft.Dafny.LanguageServer.IntegrationTest.Various.CancelVerificationTest.ChangingTheDocumentStopsOnChangeVerification [FAIL]
[xUnit.net 00:01:10.35]       System.Threading.Tasks.TaskCanceledException : A task was canceled.
[xUnit.net 00:01:10.35]       Stack Trace:
[xUnit.net 00:01:10.35]         /home/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer.Test/Util/TestNotificationReceiver.cs(58,0): at Microsoft.Dafny.LanguageServer.IntegrationTest.Util.TestNotificationReceiver`1.AwaitNextNotificationAsync(CancellationToken cancellationToken)
[xUnit.net 00:01:10.35]         /home/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer.Test/Various/CancelVerificationTest.cs(88,0): at Microsoft.Dafny.LanguageServer.IntegrationTest.Various.CancelVerificationTest.AssertNothingIsQueued(TextDocumentItem documentItem)
[xUnit.net 00:01:10.35]         /home/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer.Test/Various/CancelVerificationTest.cs(27,0): at Microsoft.Dafny.LanguageServer.IntegrationTest.Various.CancelVerificationTest.ChangingTheDocumentStopsOnChangeVerification()
[xUnit.net 00:01:10.35]         --- End of stack trace from previous location ---
  Failed Microsoft.Dafny.LanguageServer.IntegrationTest.Various.CancelVerificationTest.ChangingTheDocumentStopsOnChangeVerification [49 s]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at Microsoft.Dafny.LanguageServer.IntegrationTest.Util.TestNotificationReceiver`1.AwaitNextNotificationAsync(CancellationToken cancellationToken) in /home/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer.Test/Util/TestNotificationReceiver.cs:line 58
   at Microsoft.Dafny.LanguageServer.IntegrationTest.Various.CancelVerificationTest.AssertNothingIsQueued(TextDocumentItem documentItem) in /home/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer.Test/Various/CancelVerificationTest.cs:line 88
   at Microsoft.Dafny.LanguageServer.IntegrationTest.Various.CancelVerificationTest.ChangingTheDocumentStopsOnChangeVerification() in /home/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer.Test/Various/CancelVerificationTest.cs:line 27
```

**Comment by keyboardDrummer** [comment]
Might be resolved by https://github.com/dafny-lang/dafny/pull/5444

**Comment by keyboardDrummer** [comment]
Reoccurred: https://github.com/dafny-lang/dafny/actions/runs/9447211352/job/26018557643?pr=5548
