### ISSUE TITLE
Flaky Test: LanguageServer.IntegrationTest.Lookup.DocumentSymbolTest.CanResolveSymbolsForMultiFileProjects 

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#5443]
Seen here:

https://github.com/dafny-lang/dafny/actions/runs/9084945479/job/24967092653?pr=5442

```
Microsoft.Dafny.LanguageServer.IntegrationTest.Lookup.DocumentSymbolTest.CanResolveSymbolsForMultiFileProjects [FAIL]
[xUnit.net 00:09:15.91]       OmniSharp.Extensions.JsonRpc.Server.RequestCancelledException : 2
[xUnit.net 00:09:15.91]       Stack Trace:
[xUnit.net 00:09:15.91]            at OmniSharp.Extensions.JsonRpc.ResponseRouter.ResponseRouterReturnsImpl.Returning[TResponse](CancellationToken cancellationToken)
[xUnit.net 00:09:15.91]         D:\a\dafny\dafny\dafny\Source\DafnyLanguageServer.Test\Util\ClientBasedLanguageServerTest.cs(63,0): at Microsoft.Dafny.LanguageServer.IntegrationTest.Util.ClientBasedLanguageServerTest.CreateOpenAndWaitForResolve(String source, String filePath, Int32 version, Nullable`1 cancellationToken)
[xUnit.net 00:09:15.91]         D:\a\dafny\dafny\dafny\Source\DafnyLanguageServer.Test\Lookup\DocumentSymbolTest.cs(68,0): at Microsoft.Dafny.LanguageServer.IntegrationTest.Lookup.DocumentSymbolTest.CanResolveSymbolsForMultiFileProjects()
```

**Comment by keyboardDrummer** [comment]
https://github.com/dafny-lang/dafny/actions/runs/9092347847/job/24988886184?pr=5437

**Comment by keyboardDrummer** [comment]
Might be resolved by https://github.com/dafny-lang/dafny/pull/5444
