### ISSUE TITLE
Flaky test: LanguageServer.IntegrationTest.Lookup.SignatureHelpTest.SignatureHelpOnOpeningParenthesesReturnsSignatureOfClosestFunction 

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#5460]
Seen here
https://github.com/dafny-lang/dafny/actions/runs/9132642319/job/25114417074?pr=5442

```
Microsoft.Dafny.LanguageServer.IntegrationTest.Lookup.SignatureHelpTest.SignatureHelpOnOpeningParenthesesReturnsSignatureOfClosestFunction [FAIL]
[xUnit.net 00:00:57.14]       Assert.NotNull() Failure
[xUnit.net 00:00:57.15]       Stack Trace:
[xUnit.net 00:00:57.15]         D:\a\dafny\dafny\dafny\Source\DafnyLanguageServer.Test\Lookup\SignatureHelpTest.cs(28,0): at Microsoft.Dafny.LanguageServer.IntegrationTest.Lookup.SignatureHelpTest.RequestSignatureHelpAsync(TextDocumentItem documentItem, Position position, Boolean allowNull)
[xUnit.net 00:00:57.15]         D:\a\dafny\dafny\dafny\Source\DafnyLanguageServer.Test\Lookup\SignatureHelpTest.cs(149,0): at Microsoft.Dafny.LanguageServer.IntegrationTest.Lookup.SignatureHelpTest.SignatureHelpOnOpeningParenthesesReturnsSignatureOfClosestFunction()
[xUnit.net 00:00:57.15]         --- End of stack trace from previous location ---
[xUnit.net 00:00:57.15]       Output:
[xUnit.net 00:00:57.15]         diagnostics: [
[xUnit.net 00:00:57.15]           Diagnostic { Range = [start: (0, 0), end: (0, 0)], Severity = Error, Code = OmniSharp.Extensions.LanguageServer.Protocol.Models.DiagnosticCode, CodeDescription = CodeDescription { Href = https://dafny.org/dafny/HowToFAQ/Errors#p_internal_exception }, Source = Parser, Message = [internal error] Parser exception: Collection was modified; enumeration operation may not execute., Tags = , RelatedInformation = OmniSharp.Extensions.LanguageServer.Protocol.Models.Container`1[OmniSharp.Extensions.LanguageServer.Protocol.Models.DiagnosticRelatedInformation], Data =  }
[xUnit.net 00:00:57.15]         ]
```

**Comment by keyboardDrummer** [comment]
Seems to be the same issue as: https://github.com/dafny-lang/dafny/issues/5292
