### ISSUE TITLE
`dafny run` crashes on `print @"\";`

### ISSUE THREAD

**Issue by dnezam** [dafny-lang/dafny#5677]
### Dafny version

4.7.0+769d1572fdd799c7bf76b78a3bc9cb94d18aac59

### Code to produce this issue

```dafny
method Main() {
    print @"\";
}
```

### Command to run and resulting output

```code
dafny run crash.dfy

Dafny program verifier finished with 0 verified, 0 errors
Unhandled exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Microsoft.Dafny.Util.TokensWithEscapes(String p, Boolean isVerbatimString)+MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.String.Join(String separator, IEnumerable`1 values)
   at Microsoft.Dafny.Util.ReplaceTokensWithEscapes(String s, Regex pattern, MatchEvaluator evaluator)
   at Microsoft.Dafny.Util.ExpandUnicodeEscapes(String s, Boolean lowerCaseU)
   at Microsoft.Dafny.Compilers.CsharpCodeGenerator.EmitStringLiteral(String str, Boolean isVerbatim, ConcreteSyntaxTree wr)
   at Microsoft.Dafny.Compilers.SinglePassCodeGenerator.TrStringLiteral(StringLiteralExpr str, ConcreteSyntaxTree wr)
   at Microsoft.Dafny.Compilers.CsharpCodeGenerator.EmitLiteralExpr(ConcreteSyntaxTree wr, LiteralExpr e)
   at Microsoft.Dafny.Compilers.SinglePassCodeGenerator.EmitExpr(Expression expr, Boolean inLetExprBody, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts)
   at Microsoft.Dafny.Compilers.SinglePassCodeGenerator.Expr(Expression expr, Boolean inLetExprBody, ConcreteSyntaxTree wStmts)
   at Microsoft.Dafny.Compilers.CsharpCodeGenerator.EmitPrintStmt(ConcreteSyntaxTree wr, Expression arg)
   at Microsoft.Dafny.Compilers.SinglePassCodeGenerator.TrStmt(Statement stmt, ConcreteSyntaxTree wr, ConcreteSyntaxTree wStmts)
   at Microsoft.Dafny.Compilers.SinglePassCodeGenerator.TrStmtList(List`1 stmts, ConcreteSyntaxTree writer)
   at Microsoft.Dafny.Compilers.SinglePassCodeGenerator.CompileMethod(Program program, Method m, IClassWriter cw, Boolean lookasideBody)
   at Microsoft.Dafny.Compilers.SinglePassCodeGenerator.CompileClassMembers(Program program, TopLevelDeclWithMembers c, IClassWriter classWriter)
   at Microsoft.Dafny.Compilers.SinglePassCodeGenerator.EmitModule(Program program, ConcreteSyntaxTree programNode, ModuleDefinition module)
   at Microsoft.Dafny.Compilers.SinglePassCodeGenerator.Compile(Program program, ConcreteSyntaxTree wrx)
   at Microsoft.Dafny.ExecutableBackend.Compile(Program dafnyProgram, String dafnyProgramName, ConcreteSyntaxTree output)
   at Microsoft.Dafny.SynchronousCliCompilation.<>c__DisplayClass20_1.<CompileDafnyProgram>b__1()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at Microsoft.Dafny.SynchronousCliCompilation.CompileDafnyProgram(Program dafnyProgram, String dafnyProgramName, ReadOnlyCollection`1 otherFileNames, Boolean invokeCompiler)
   at Microsoft.Dafny.SynchronousCliCompilation.Compile(String fileName, ReadOnlyCollection`1 otherFileNames, Program dafnyProgram, PipelineOutcome oc, IDictionary`2 moduleStats, Boolean verified)
   at Microsoft.Dafny.SynchronousCliCompilation.ProcessFilesAsync(IReadOnlyList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, DafnyOptions options, ProofDependencyManager depManager, Boolean lookForSnapshots, String programId)
   at Microsoft.Dafny.SynchronousCliCompilation.Run(DafnyOptions options)
   at Microsoft.Dafny.RunCommand.<>c.<<Create>b__6_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Dafny.DafnyNewCli.<>c__DisplayClass5_0.<<SetHandlerUsingDafnyOptionsContinuation>g__Handle|0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
   at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Dafny.DafnyNewCli.<>c__DisplayClass17_0.<<AddDeveloperHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
   at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
```

### What happened?

Instead of crashing, I would have assumed that the method prints \\.

### What type of operating system are you experiencing the problem on?

Linux

**Comment by robin-aws** [comment]
Thanks for the report! Interestingly this only affects the C# backend. Looks like it's been wrong for quite a few versions as well.
