### ISSUE TITLE
Sequence eq comparison during map comprehension crash

### ISSUE THREAD

**Issue by kbuaaaaaa** [dafny-lang/dafny#5736]
### Dafny version

Starting from c9cd3b61cd5463e8669e22d7c3202d2e4ed39f15

### Code to produce this issue

```dafny
method Main(){
    var i8 := 4;
    var v1 := multiset{1,2,3,4};
    var v2 := map v3 : int | v3 in v1 :: if (| seq(1, i8  =>  0) | in v1) then v1[| seq(1, i8  =>  8) |] else 0 := 0;
}
```

### Command to run and resulting output

```code
dafny run crash.dfy


Process terminated. Assumption failed.
	   at Microsoft.Dafny.Triggers.ExprExtensions.ShallowEq(LambdaExpr expr1, LambdaExpr expr2) in /dafny/Source/DafnyCore/Triggers/TriggerExtensions.cs:line 272
	   at Microsoft.Dafny.Triggers.ExprExtensions.ShallowEq(ComprehensionExpr expr1, ComprehensionExpr expr2) in /dafny/Source/DafnyCore/Triggers/TriggerExtensions.cs:line 329
	   at Microsoft.Dafny.Triggers.ExprExtensions.ShallowEq_Top(Expression expr1, Expression expr2) in /dafny/Source/DafnyCore/Triggers/TriggerExtensions.cs:line 193
	   at Microsoft.Dafny.Triggers.ExprExtensions.ExpressionEq(Expression expr1, Expression expr2) in /dafny/Source/DafnyCore/Triggers/TriggerExtensions.cs:line 86
	   ...
	   at System.Threading.Thread.StartCallback()
	/dafny/Scripts/dafny: line 35: 87808 Abort trap: 6           "$DOTNET" "$DAFNY" "$@"
```

### What happened?

Should not crash. Did not crash up until c9cd3b61cd5463e8669e22d7c3202d2e4ed39f15.

### What type of operating system are you experiencing the problem on?

Linux

**Comment by zetzschest** [comment]
Can confirm the error with 4.8.1 on my Mac. This slight variation of above program does not throw the error:
```
method Main(){
    var i8 := 4;
    var v1 := multiset{1,2,3,4};
    var xs := seq(1, i8  =>  0);
    var v2 := map v3 : int | v3 in v1 :: if (|xs| in v1) then v1[| seq(1, i8  =>  8) |] else 0 := 0;
}
```
