### ISSUE TITLE
Flaky test: OpeningDocumentWithTimeoutReportsTimeoutDiagnostic 

### ISSUE THREAD

**Issue by MikaelMayer** [dafny-lang/dafny#5753]
Seen in https://github.com/dafny-lang/dafny/actions/runs/10727797023/job/29753637855?pr=5750

```
[xUnit.net 00:03:34.60]     Microsoft.Dafny.LanguageServer.IntegrationTest.Synchronization.DiagnosticsTest.OpeningDocumentWithTimeoutReportsTimeoutDiagnostic [FAIL]
[xUnit.net 00:03:34.60]       The collection was expected to contain a single element, but it contained 2 elements.
[xUnit.net 00:03:34.60]       Stack Trace:
[xUnit.net 00:03:34.60]         D:\a\dafny\dafny\dafny\Source\DafnyLanguageServer.Test\Diagnostics\DiagnosticsTest.cs(1008,0): at Microsoft.Dafny.LanguageServer.IntegrationTest.Synchronization.DiagnosticsTest.OpeningDocumentWithTimeoutReportsTimeoutDiagnostic()
[xUnit.net 00:03:34.60]         --- End of stack trace from previous location ---
  Failed Microsoft.Dafny.LanguageServer.IntegrationTest.Synchronization.DiagnosticsTest.OpeningDocumentWithTimeoutReportsTimeoutDiagnostic [3 s]
  Error Message:
   The collection was expected to contain a single element, but it contained 2 elements.
  Stack Trace:
     at Microsoft.Dafny.LanguageServer.IntegrationTest.Synchronization.DiagnosticsTest.OpeningDocumentWithTimeoutReportsTimeoutDiagnostic() in D:\a\dafny\dafny\dafny\Source\DafnyLanguageServer.Test\Diagnostics\DiagnosticsTest.cs:line 1008
```

**Comment by MikaelMayer** [comment]
Reappeared here.
https://github.com/dafny-lang/dafny/actions/runs/10741114678/job/29797509071?pr=5668

**Comment by MikaelMayer** [comment]
Reappeared here:
https://github.com/dafny-lang/dafny/actions/runs/10881945935/job/30191964015?pr=5757

**Comment by MikaelMayer** [comment]
Good news, the issue also appeared in the same PR that was supposed to help diagnose it.
https://github.com/dafny-lang/dafny/actions/runs/10839439156/job/30080084116?pr=5754

Here are the two diagnostics
```
[xUnit.net 00:00:11.14]       System.Exception : There should be only one diagnostic, got :
Diagnostic { Range = [start: (0, 23), end: (0, 26)], Severity = Error, Code = , CodeDescription = , Source = , Message = The operation has timed out., Tags = , RelatedInformation = , Data =  }(The operation has timed out.),
Diagnostic { Range = [start: (11, 7), end: (11, 11)], Severity = Error, Code = , CodeDescription = , Source = , Message = The operation has timed out., Tags = , RelatedInformation = , Data =  }(The operation has timed out.)
```
So there are two timed out diagnostic instead of one.
