### ISSUE TITLE
Test suite fails on Synchronization.ProjectManagerDatabaseTest.ChangeAndUndoProjectWithMultipleFiles

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#5901]
### Dafny version

master branch, 6 Nov 2024

### Code to produce this issue

```dafny
DafnyLanguageServer Tests fail in CI, see the trace below. This failure is on xunit-tests/osx. I've seen several similar failures recently.

https://github.com/dafny-lang/dafny/actions/runs/11708454051/job/32610268756?pr=5891
```

### Command to run and resulting output

```code
[xUnit.net 00:07:59.94]         /Users/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer.Test/Synchronization/ProjectManagerDatabaseTest.cs(44,0): at Microsoft.Dafny.LanguageServer.IntegrationTest.Synchronization.ProjectManagerDatabaseTest.ChangeAndUndoProjectWithMultipleFiles()
[xUnit.net 00:07:59.94]         --- End of stack trace from previous location ---
  Failed Microsoft.Dafny.LanguageServer.IntegrationTest.Synchronization.ProjectManagerDatabaseTest.ChangeAndUndoProjectWithMultipleFiles [49 s]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at Microsoft.Dafny.LanguageServer.IntegrationTest.Util.TestNotificationReceiver`1.AwaitNextNotificationAsync(CancellationToken cancellationToken) in /Users/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer.Test/Util/TestNotificationReceiver.cs:line 58
   at Microsoft.Dafny.LanguageServer.IntegrationTest.Util.ClientBasedLanguageServerTest.WaitUntilAllStatusAreCompleted(TextDocumentItem documentId, Nullable`1 cancellationToken, Boolean allowStale) in /Users/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer.Test/Util/ClientBasedLanguageServerTest.cs:line 188
   at Microsoft.Dafny.LanguageServer.IntegrationTest.Util.ClientBasedLanguageServerTest.GetLatestDiagnosticsParams(TextDocumentItem documentItem, CancellationToken cancellationToken, Boolean allowStale) in /Users/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer.Test/Util/ClientBasedLanguageServerTest.cs:line 219
   at Microsoft.Dafny.LanguageServer.IntegrationTest.Util.ClientBasedLanguageServerTest.GetLastDiagnostics(TextDocumentItem documentItem, DiagnosticSeverity minimumSeverity, Nullable`1 cancellationToken, Boolean allowStale) in /Users/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer.Test/Util/ClientBasedLanguageServerTest.cs:line 234
   at Microsoft.Dafny.LanguageServer.IntegrationTest.Synchronization.ProjectManagerDatabaseTest.ChangeAndUndoProjectWithMultipleFiles() in /Users/runner/work/dafny/dafny/dafny/Source/DafnyLanguageServer.Test/Synchronization/ProjectManagerDatabaseTest.cs:line 44
--- End of stack trace from previous location ---
```

### What happened?

See above

### What type of operating system are you experiencing the problem on?

Mac

**Comment by keyboardDrummer** [comment]
If you look at the stack trace in the log file, you can see it times out on a line with 
```c#
fileVerificationStatus = await verificationStatusReceiver.AwaitNextNotificationAsync(cancellationToken.Value);
```

If you then look at the invoked method.
```c#
    public async Task<TNotification> AwaitNextNotificationAsync(CancellationToken cancellationToken) {
      var start = DateTime.Now;
      try {
        return await notifications.Dequeue().WaitAsync(cancellationToken);
      } catch (OperationCanceledException) {
        var last = History.Any() ? History[^1].Stringify() : "none";
        logger.LogInformation($"Waited for {(DateTime.Now - start).Seconds} seconds for new notification.\n" +
                              $"Last received notification was {last}");
        throw;
      }
    }
``` 

You see it calls `logger.LogInformation` on a timeout. However, LogInformation is not recorded by default, because the severity level is too low.

If you go to the constructor of the test file with the failing test:
```c#
  public ProjectManagerDatabaseTest(ITestOutputHelper output) : base(output) {
  }
```

and then change that into:
```c#
  public ProjectManagerDatabaseTest(ITestOutputHelper output) : base(output, LogLevel.Information) {
  }
```

Then you'll get log output next time this failure occurs, and that log output will tell you what happened before the timeout so you can debug further.

**Comment by keyboardDrummer** [comment]
I think I know what the problem is, but the fix is rather involved. I'll work on a PR
