### ISSUE TITLE
toString member causes crash in JavaScript

### ISSUE THREAD

**Issue by RustanLeino** [dafny-lang/dafny#705]
The following program, when compiled to JavaScript and run, causes a crash:

``` dafny
datatype MyDataType = AAA {
 function method toString(): int { 222 }
}

method Main() {
  var dt: MyDataType;
  print dt, "\n";
}
```

The crash output starts as follows:

```
TypeError [ERR_INVALID_ARG_TYPE]: The "chunk" argument must be one of type string or Buffer. Received type object
    at validChunk (_stream_writable.js:263:10)
    at WriteStream.Writable.write (_stream_writable.js:297:21)
    ...
```

The problem is Dafny already generates a `toString()` method for the datatype, and the user-defined `toString` gets the same name. The problem is detected by the `$module.toString(a)` function in the Dafny runtime for JavaScript.

There may be similar problems with other members that Dafny adds to all datatypes, like `equals`. In fact, perhaps there are also similar problems with the compilation of `newtype`, which can also have user-defined members in Dafny.

**Comment by acioc** [comment]
Relates to https://github.com/dafny-lang/dafny/issues/450

**Comment by davidcok** [comment]
In the case of toString -- is it reasonable to state a rule (for Dafny) that toString is a pre-defined method, which can be replaced by the user, but must have no arguments and must return a value of type string?

**Comment by davidcok** [comment]
This sort of conflict will happen whenever a user name is the same as an internally generated name. In addition, as in this example, a dafny name(toString) may collide with names used by the target language (Java defines toString). Because of the latter is not a solution to rename the generated name for the internal compiler name; instead we have to choose a non-colliding name for the user-defined entity. There will still be a problem if the user forces a colliding name by using :extern.  PR#803
