### ISSUE TITLE
dafny crashes trying to cast a function to a prefixLemma

### ISSUE THREAD

**Issue by erniecohen** [dafny-lang/dafny#847]
The following crashes 3.0.0.20820 (

``` dafny
trait O {
    var rep:set<O>
    function union<T>(s:set<set<T>>):set<T> { set o,o1 | o in s && o1 in o :: o1 }
    inductive predicate ag() reads * { rep=={} || (forall o:O | o in rep :: o.ag())}
    predicate ldp(n:ORDINAL) reads *  { ag#[n]() && (forall n1:ORDINAL | n1 < n:: !ag#[n1]()) }
    function ld(n:ORDINAL):ORDINAL reads * requires ag#[n]() ensures ldp(ld(n)) {
        if ldp(n) then n else var n1:ORDINAL :| n1 < n && ag#[n1](); ld(n1) }
    function level():ORDINAL reads fr() requires ag() ensures ldp(level()) { var n:ORDINAL :| ag#[n](); ld(n) }
    inductive lemma l1() requires ag() ensures forall o:O | o in rep :: o.level() < level() decreases level() {}
    function  fr():set<O> requires ag() reads * decreases level() { {this} + union(set o:O | o in rep :: l1(); o.fr()) }
} 
```

The error message is

```
Unhandled Exception: System.InvalidCastException: Unable to cast object of type 'Microsoft.Dafny.Function' to type 'Microsoft.Dafny.PrefixLemma'.
   at Microsoft.Dafny.Translator.ProcessCallStmt(IToken tok, Dictionary`2 tySubst, List`1 tyArgs, Expression dafnyReceiver, Expr bReceiver, Method method, List`1 Args, List`1 Lhss, List`1 LhsTypes, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /Users/leino/Source/dafny/Source/Dafny/Translator.cs:line 12233
   at Microsoft.Dafny.Translator.TrCallStmt(CallStmt s, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran, IdentifierExpr actualReceiver) in /Users/leino/Source/dafny/Source/Dafny/Translator.cs:line 12086
   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /Users/leino/Source/dafny/Source/Dafny/Translator.cs:line 10470
   at Microsoft.Dafny.Translator.TrStmt(Statement stmt, BoogieStmtListBuilder builder, List`1 locals, ExpressionTranslator etran) in /Users/leino/Source/dafny/Source/Dafny/Translator.cs:line 10426
   at Microsoft.Dafny.Translator.CheckWellformedWithResult(Expression expr, WFOptions options, Expr result, Type resultType, List`1 locals, BoogieStmtListBuilder builder, ExpressionTranslator etran) in /Users/leino/Source/dafny/Source/Dafny/Translator.cs:line 7879
...
```

**Comment by RustanLeino** [comment]
A strongly connected component in a Dafny call graph must consist of
* all inductive predicates,
* all co-inductive predicates,
* all inductive lemmas,
* all co-inductive lemmas, or
* none of the above (that is, only ordinary functions, methods, and lemmas). 

In other words, any mutual recursion must be contained without one of the 5 categories above (that is, mutual recursion is not allowed to span more than one of the categories above).

The example above includes mutual recursion between `fr`, `level`, and `l1`. This should be disallowed, but apparently the resolver in Dafny doesn't detect it. That is a bug and should be fixed.

(Curiously, by the time Dafny gets to the translator in the verifier, it has the information that these three routines are mutually recursive. This is computed by the resolver, so I don't understand why the resolver didn't complain about it.)

Note, once the bug has been fixed, the example above will not be allowed.
